### ISSUE TITLE
Inline markup shouldn't greedily consume trailing whitespace.

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#100]
The parser currently introduces an awkward situation by greedily consuming whitespace trailing the command. This is fine for many cases where the whitespace will be insignificant, but in the case of inline markup this ruins the typesetting of the line.

For example in the current SILE manual on page 8 (section 1.3) the following code:

    into \em{frames} on

…is rendering without a space after the italicized word 'frames':

> into *frames*on

**Comment by simoncozens** [comment]
I've just run SILE on the documentation file again, and I do get a space after "frames". I think what happened was that I was fiddling with the documentation and also the regression tests while still working on getting the grammar correct, and I must have accidentally checked in a version of the manual compiled while the grammar was still broken. But the manual is also broken for other reasons (text overflowing the frame at the bottom of that page, for instance), so I'll sort it separately.

Anyway, the grammar is correct, I think:

```
local lineEndLineStartSpace = (lpeg.S(" ")^0 * lpeg.S("\r\n")^1 * lpeg.S(" ")^0)^-1
```
