### ISSUE TITLE
insertion issues with large numbers of footnotes per page

### ISSUE THREAD

**Issue by jtauber** [simoncozens/sile#106]
I'm building a SILE backend for https://github.com/jtauber/greek-reader (see <https://github.com/jtauber/greek-reader/issues/7>) and have hit some problems given the large number of footnotes it can produce.

I'll describe two cases here, one with 21 footnotes and one with 200.

**Comment by jtauber** [comment]
The 21 footnote case has this source file: <https://gist.github.com/jtauber/aacd71b7ac4d9bcddfd6>

**Comment by jtauber** [comment]
The 200 footnote case has this source file: https://gist.github.com/jtauber/9727a900947220c73800

**Comment by simoncozens** [comment]
OK, I think I have fixed this now. Please try again!
