### ISSUE TITLE
Script does not work if preceded by comment

### ISSUE THREAD

**Issue by strepon** [simoncozens/sile#117]
[This commit](https://github.com/simoncozens/sile/commit/a99508fe9857d9f5c096973d9ca0c2c545eed606) broke using of script environment if it is preceded by comment.
This code:
```
\begin[papersize=a4]{document}
%nice script from SILE book
\begin{script}for i=1,10 do
SILE.typesetter:typeset(i .. " x " .. i .. " = " .. i*i .. ". ")
SILE.typesetter:leaveHmode()
SILE.call("smallskip")
end
\end{script}
\end{document}
```
does not work unless the second line with comment is removed.

**Comment by alerque** [comment]
This may or may not be related to #99 code wise, but comments should be allowed _anywhere_ in the input data.
