### ISSUE TITLE
Git branch/merge technique

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#120]
Hey just a quick question / suggestion. The SILE commit history to date has a bunch of merge commits that have nothing to do with changes to the project code base, only indicators of your personal workflow. These add a a bit of clutter, especially when using a local branch graph to untangle what's going on and what effects what in the code base.

Most of theme seem to be a result of using merges instead of rebases when pulling down other people's contributions from Github into your local repository. Can I first ask why you are not using the rebase option for your pulls? Second perchance this is not a conscious choice and you don't have another reason, can I suggest that you make that your normal workflow by setting the flag at least for your master branch:

     git config branch.master.rebase true

You can also make this the default for new branches:

    git config branch.autosetuprebase always

Even better (if you have no projects that call for merges) you can make it the default for all your git pulls in `~/.gitconfig`:

    [pull]
        rebase = true

It's a simple thing but will keep the commit history just a bit less tangled.

**Comment by simoncozens** [comment]
Yep, no reason for it other than lack of git-fu. I have applied your changes to my git config. :-)
