### ISSUE TITLE
PDF bookmark encoding screwed up

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#121]
As demonstrated in `tests/pdf.sil`, bookmarks are indeed generated by `packages/pdf`, but the character encoding of the titles is goofed up. PDF requires some crazy encapsulation for that data (you can't just cram plain text in that field). I can't remember exactly it has to be done, but I do remember having this problem back in the day when I wrote my own PDF library. In any case the current output of that test is actually a borked PDF.

**Comment by simoncozens** [comment]
Huh. I thought we'd fixed that - @shirat74 added UTF8 to UTF16-BE conversion, and UTF-16 should be acceptable. The PDF (and bookmarks) look fine here in Preview and in Adobe Acrobat, and I can't get any of the Acrobat preflight checks to show any errors. In what sense borked?

**Comment by alerque** [comment]
Borked as in neither Acrobat or Evince show a readable index:

![_027](https://cloud.githubusercontent.com/assets/173595/8429791/9c0967e6-1f33-11e5-809e-dcd5979e3cf9.png)

**Comment by simoncozens** [comment]
Huh. What Lua version and do you have the utf8 library installed?

**Comment by alerque** [comment]
I default Lua runtime that I'm using for everything but regression testing is 5.3.1. And I have [luautf8](https://luarocks.org/modules/xavier-wang/luautf8) installed (although it's 1.0 not 1.1) but not [utf8](https://luarocks.org/modules/dannote/utf8). BTW should that be an install time dependency? If it matters for the core packages to function as expected I think it should be...shall I add it to #119?

**Comment by simoncozens** [comment]
If you're using 5.3, then it comes with the utf8 library baked in. And I don't trust it yet, because it was throwing strange errors like [this](https://travis-ci.org/simoncozens/sile/jobs/68787735). (That was actually failing to decode a `"\n"`)

**Comment by alerque** [comment]
So is the utf8 luarock required for lua < 5.3?

**Comment by simoncozens** [comment]
Should not be required; lua 5.3 contains a [utf8 library](http://www.lua.org/manual/5.3/manual.html#6.5), which has a compatible interface to [luautf8](https://github.com/starwing/luautf8), but different code.

**Comment by alerque** [comment]
My question was about for Lua 5.2 etc. Do the lower versions of lua have an extra dependency that 5.3 doesn't? In other words should we be installing something more as a luarock for systems with older Lua versions?

**Comment by simoncozens** [comment]
No. `utilities.lua` contains implementations of all the UTF8 functions we need; Paul K noticed that these could also be implemented by the utf8 library, so if that library (either the 5.3 built-in one, or the luautf8 rock) is available its functions are used instead. But our functions are available as a fallback.

**Comment by alerque** [comment]
Got it. So where does that leave my long strings of Arabic hanging off the page?  But I guess we should go back to #123 for that since that's a different issue.

**Comment by simoncozens** [comment]
OK, so _revenons à nos moutons_, I have PDF bookmarks working on Lua 5.2, but you don't have them working on 5.3. Could you try (again) disabling the `require("utf8")` in utilities.lua and seeing if that helps? If not, could you then try printing out the value of `ustr` in `pdf.lua:28` (piping through hexdump or moral equivalent if necessary) and seeing if it is correctly encoded UTF-16BE?

**Comment by alerque** [comment]
Commenting out `require("utf8")` has no effect.

Dumping the value of `ustr` does not net me a valid UTF16BE string as far as I can tell. Lua dumps it to the console as `feff000100020003000400050006000700080009000a000b`, and if I have Lua write it to a process pipe `inconv` declares it to be bogus:

    local fp = io.popen("iconv -f UTF-16BE -t ASCII", "w")
    fp:write(ustr)

Gives:

> iconv: illegal input sequence at position 0

On the other hand feeding `title` to `iconv` and asking it to convert from UTF-8 works as expected.

**Comment by simoncozens** [comment]
It's the utf8 library again. Specifically, `utf8.codes` does not have the same interface as the `utilities.utf8codes` that we supply, so the fallback line:

`utilities.utf8codes = utf8.codes or function (ustr) ... end`

is false. Lua 5.2:

```
> for uchr in SU.utf8codes("hello") do print(uchr) end
104
101
108
108
111
```

Lua 5.3:

```
> for uchr in utf8.codes("hello") do print(uchr) end
1
2
3
4
5
```

**Comment by simoncozens** [comment]
I've removed the calls out to the utf8 library in [master cad2fe4].

**Comment by alerque** [comment]
Confirmed fix working for me here.

At some point the PDF package needs to be compatible with the debug outputter so we can test it. It's not yet. I started to get it setup the other day but I think I started at the wrong end of the stick. Then got sidetracked.
