### ISSUE TITLE
Minor suggestion re: underlining

### ISSUE THREAD

**Issue by biggnome** [simoncozens/sile#1259]
(Not to downplay the horribleness of underlines as a typographical practice or anything...)

The way the \underline command draws a line immediately beneath the text butted right up against the bottom of the letters strikes me as especially ugly. I've played with altering the "lower" value (on line 39 of rules.lua) from 'height - 0.5pt' to either between 'height - 1.5pt' and '2pt' (I like the look of 1.667 personally); or alternatively 1/10th that value in em. Pt maintains a consistent position of the underline whereas em scales its relative distance from the bottom of the letters nicely with the font size (likewise, changing the hrule height from 0.5pt to something like 0.0375 scales the "weight" of the underline with the font size). Either way seems to me an improvement on the current implementation (likewise, changing the hrule height on line 40 from 0.5pt to something like 0.0375em scales the "weight" of the underline with the font size). Food for thought anyway...

**Comment by alerque** [comment]
@simoncozens Is there an easy/robust way to query fonts for their underline distance metric?

**Comment by alerque** [comment]
If you figure out a way to fetch a value or NULL I'm sure we can cast it to a measurement and use that as the offset, perhaps with a fallback default relative to the font size for the NULL case. The raise/lower can then be relative to that, perhaps with an optional flag to ignore the value and use absolute positioning.
