### ISSUE TITLE
Errors and typos in The SILE Book

### ISSUE THREAD

**Issue by shirat74** [simoncozens/sile#127]
I found several errors and typos in sile.sil.

l.1426 skip -> shrink
l.1430 plus 3pt minus 6pt -> plus 6pt minus 3pt
l.1528 fine -> line

The followings are missing backslashes before braces in the verbatim environment:

l.1946 missing backslashes
l.1961 missing backslashes
l.2071 missing backslashes
l.2250 missing backslashes
l.2335 missing backslashes
l.2338 missing backslashes
l.2553 missing backslashes
l.2559 missing backslashes
l.2581 missing backslashes
l.2583 missing backslashes
l.2835 missing backslashes
l.2846 missing backslashes
l.2848 missing backslashes
l.2851 missing backslashes

**Comment by alerque** [comment]
Can I ask what version (git commit level?) you are looking at. These line numbers don't line up with either the last released v0.9.2 manual or current HEAD. It would be easy for me to fix these if I know what commit you were looking at and could just breeze through them with a patch to that version, then rebase it.

**Comment by alerque** [comment]
Scratch that request. I wasn't looking at the right HEAD ... I'm lined up now.

**Comment by shirat74** [comment]
Sorry I forgot to mention that. I don't know how to specify it precisely but it is
the latest one after commit

    b3c305bae7021f2058e6e3e4b171393a1f08de09

**Comment by alerque** [comment]
@shirat74 That's how you specify it alright. And you can even truncate it to the first 7+ characters, if you drop it in GIthub markdown without the code block it will even link it for you, like this: b3c305b

Note I made the fixed and submitted a PR now linked above^^^.

**Comment by simoncozens** [comment]
Thanks, both!
