### ISSUE TITLE
Bidirectionality misfeature?

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/sile#137]
@khaledhosny, how would you expect this to render:

```
\begin[papersize=a5]{document}
\font[family=Scheherazade,size=12pt,language=ar,script=Arab]
\thisframeRTL

العَرَبِيةُ‎‎ العَرَبِيةُ‎‎ \font[family=Arial]{The Unicode Conference} العَرَبِيةُ‎‎ 

العَرَبِيةُ‎‎ العَرَبِيةُ‎‎ \font[family=Arial]{The אבג Conference} العَرَبِيةُ‎‎ 

\end{document}
```

I think intuitively I would expect to see "The אבג Conference" as an LTR unit containing some RTL text. But the bidi algorithm sees this as a switch from RTL to LTR at "The" and then back to RTL at "אבג", and then back to LTR, giving us:

![screen shot 2015-07-17 at 09 05 40](https://cloud.githubusercontent.com/assets/106728/8737919/0b12d14a-2c63-11e5-991a-30070f40e185.png)

Bug? Working as defined? Misfeature? Do we need explicit markup for this situation?

**Comment by khaledhosny** [comment]
Yes, working as expected here. You need to surround “The אבג Conference” with LRE and PDF control characters (or better LRI instead of LRE when the latest BiDi algorithm is supported).

But I see a different problem in the image, there should be space on both sides of the English text, but it seems to be accumulated on one side.

**Comment by simoncozens** [comment]
OK, this one *is* a bidirectionality misfeature:

![screen shot 2015-07-20 at 17 58 50](https://cloud.githubusercontent.com/assets/106728/8781776/054bafc2-2f09-11e5-9e4d-fd18959ffd15.png)

The Hebrew text should be הרח שלי מלאה בצלופחים - in other words, "הרחפת שלי" should be the first words and appear on the first line. The bidi algorithm is doing the right thing in reordering the glyphs, but then line breaks are being computed afterwards. UAX#14 says "In bidirectional text, line breaks are determined before applying rule L1 of the Unicode Bidirectional Algorithm." But how can you determine line breaks when your glyphs are not in the right order?

**Comment by khaledhosny** [comment]
I think you have to shape the paragraph as a single line, then do line breaking afterwards.

**Comment by simoncozens** [comment]
That's what we're doing, and that's why it's breaking. It looks like we need to do line breaking on the logical order of characters (and that means you need to do shaping *first* in order to get the widths), then do the bidi reordering, and then even if this changes the widths a bit you just have to go with it. (See [this thread](http://lists.gnu.org/archive/html/freetype/2004-10/msg00033.html).) So that's going to need a bit of reworking.

**Comment by khaledhosny** [comment]
I have’t read this new document fully yet, but I think it might help with general BiDi requirements: http://www.w3.org/TR/2015/NOTE-html-bidi-20150721/
