### ISSUE TITLE
Sile logo

### ISSUE THREAD

**Issue by raphaelbastide** [simoncozens/sile#14]
Here is a quick graphic cleaning on the logo. It is now more simple and clear and based on a custom font that gives a unique subtle identity. Feel free to ask the SVG source file and I’ll make a pull request.

![export](https://cloud.githubusercontent.com/assets/193122/4475496/fa1facfc-496c-11e4-85b4-8757fed462fd.png)

![export-m](https://cloud.githubusercontent.com/assets/193122/4475518/3a3e2aac-496d-11e4-80a6-fc555562c52e.png)

 ![export-s](https://cloud.githubusercontent.com/assets/193122/4475511/1a660740-496d-11e4-8ac8-6bc210611ed5.png)

**Comment by bakirov** [comment]
@simoncozens, if those triangles around "S" emphasize that SILE is designed for print primarily and represent a "paper" or a "document", how about using unicode corner symbols instead? I.e. "Top|Bottom Left|Right Corner" unicode characters around "S", e.g. http://www.fileformat.info/info/unicode/char/231e/index.htm
Maybe, this way, it will be also possible to implement logo purely in SILE itself (a-la bootstrap mode).

**Comment by raphaelbastide** [comment]
I agree with @bakirov.
I can do some tests in this direction if you want me to @simoncozens
