### ISSUE TITLE
Move travis to container-based infrastructure

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/sile#146]
See [this](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade). A job for @alerque, I think.

**Comment by alerque** [comment]
I actually already poked at it some, but there are a few blockers. The docker based containers don't give you root access to install software to the system. Yet. It might be possible to install all of our dependencies at the per-user level, but it would require quite a bit of manual downloading and extractions and then a lot of setting non-standard library paths and other variables to get it all tied together.

Hopefully Travis gets the feature set straightened out before we have to bite the bullet and do all that!

**Comment by simoncozens** [comment]
It looked like there were ways to install apt packages and custom apt sources, so it shouldn't be too nasty. Better make you an Official Contributor if I'm going to assign it then. :-)

**Comment by alerque** [comment]
You can install apt packages, but only against a whitelist of allowed packages which doesn't include some of the things we'd need. They do review additions to the list though so there is hope even if they don't open up `sudo` access as before (which it sounds like they plan on anyway). Fonts can be run from the user account without too much trouble. That leaves a few issues with lua rocks (ug) and needing to link to a harfbuzz build that's not in the system path where it belongs. Again all doable it's just going to take some fiddling.

**Comment by simoncozens** [comment]
I'm doing some fiddling on this with a simplified build. Just for my notes, when it's time to make it more complex again, this will help: https://github.com/moteus/lua-travis-example

**Comment by simoncozens** [comment]
OK, this is done!
