### ISSUE TITLE
Segfault issues in latest commit

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#151]
I don't know where the problem was introduced, but testing at 6aa9afa produces a lot of issues for me. Running some of the tests produces segfaults as in `alignment.sil` while others throw other errors like a "double free or corruption" dump from `centering.sil` or invalid UTF8 sequence errors from `bug-124_upstream.sil` or "realloc(): invalid next size" from `bug-76.sil`.

**Comment by alerque** [comment]
Using `git bisect` the first bad commit turns up as ddad04f. I wonder if there is an ICU dependency version mismatch or something.

**Comment by simoncozens** [comment]
I think it's more likely there are bugs in my ICU code.

**Comment by alerque** [comment]
What would be useful for me to provide in the way of debug information?

**Comment by alerque** [comment]
Commit 1896a8f does indeed fix the issue for me.
