### ISSUE TITLE
Right alignment broken

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#154]
In updating the tests for #152, I noticed an anomaly in the output `tests/alignment.sil`. The test is passing but I don't think it _should_ be. There is some sort of issue with the last line of the ragged right paragraph. For some reason the last line overflows into the margin that it should be starting from.

![selection_037](https://cloud.githubusercontent.com/assets/173595/9271082/d7ff78b6-427f-11e5-8316-00eee9a6db8b.png)

**Comment by simoncozens** [comment]
There is a bug somewhere in the line ratio code; you can see it in the Conan Doyle test, as there are spaces at the end of lines which are meant to be justified. I think it may have come in after the changes to discretionaries.
