### ISSUE TITLE
Output vanished

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#157]
In updating tests for #152 I noticed a new issue with `tests/balanced.sil` (besides the still outstanding #118 related to overflowing columns). The updated shaper lines things up differently enough that in the second set of columns it is actually able to fit an extra line of text on the page. So far so good. But for whatever reason even though there is now more space to work with, the final line of text is just gone. It doesn't wrap to the next page and or the previous column, it's just gone.

![selection_040](https://cloud.githubusercontent.com/assets/173595/9271619/07be4fd8-4284-11e5-8461-cef978ca64b7.png)

This should continue with “him when they heard about the things he had done.” as in the source file but that text is nowhere to be found in the PDF.

**Comment by alerque** [comment]
Bizarrely this issue went away with 2a63f38. Does that make any sense at all? Is this actually fixed or did the dust just get sirred up and we're no longer triggering whatever the bug actually was?

**Comment by simoncozens** [comment]
I think this is gone, but I've now also done some fixes to the `finish` function and added asserts that all typesetter output is flushed before finishing.
