### ISSUE TITLE
Spaces typeset at end of line

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#161]
Visible in several places but going off of `tests/alignment.sil`, it appears that even when a line breaks at a space the space is getting typeset at the end of the line.

![selection_043](https://cloud.githubusercontent.com/assets/173595/9278847/416370b4-42bc-11e5-9a56-89e68325b935.png)

Possibly related to (but predates fix for) #154 and possibly also relevant to discussion on #105.

**Comment by simoncozens** [comment]
I think what's happening is that hyphens are getting hung into the margin. After the #154 fix, I'm now getting this:
![screen shot 2015-08-14 at 17 44 30](https://cloud.githubusercontent.com/assets/106728/9278956/29f6dbf6-42ac-11e5-8cb7-c733234d070e.png)

**Comment by alerque** [comment]
Either way. My red line was draw in a screen shot tool so I don't know what it's relative to. Either way I tested it before and after the fix for 154 and got the same results which made me think it was unrelated.

**Comment by simoncozens** [comment]
Yeah, but this is exactly the same bug as #156.

**Comment by alerque** [comment]
Huh. I had that _déjà vu_ feeling working up this report but couldn't put my finger on why. I suppose I was too distracted making sure the original hyphenation problem was still being tested to notice the similarity.

**Comment by alerque** [comment]
This is _mostly_ fixed but not quite. Most of the test cases I checked seem to be fine now, but one in `tests/bug-79.sil` is still tripping.

![selection_044](https://cloud.githubusercontent.com/assets/173595/9287515/4337a0a8-4321-11e5-9fa8-ba7f4fb94c1e.png)

Notably before all the lines except the hyphenated one had an issue. Now the lines ending with `h` and `a` are correct, but the one ending `á` still has something going on after it.

**Comment by simoncozens** [comment]
I have to admit I don't immediately understand what's going on here. There isn't a glue node at the end of the line; the problem is that the line ratio calculate isn't correct. But why is it correct for everything else apart from that line in that one text? (Playing with the spacing in the document moves the problem around.) And it's not a particularly bad line; it's just that the reported natural width is about 6 points too little.

**Comment by alerque** [comment]
Does it have something to do with the presence of diacritic marks? Is some mark composed of parts rather than a single Unicode code point? Perhaps the width of some mark(s) are being removed from the line more than once. Just speculating here.

**Comment by simoncozens** [comment]
Replacing all the "funny" characters with plain old Latin-1 versions leads to the same result.

**Comment by alerque** [comment]
If it's any consolation I have an ongoing problem I tried and failed to solve years ago with LaTeX where the presence of certain character sequences and formatting (the extent of possible combinations eludes me although I have many duplicable cases) screws up the line length calculation and the lines overflow the box they should be fitting in no matter what the available break points are. Quite often emergency stretch will get applied as if it is desperate to expand a line to fit the space, but the whole while it's actually showing stuff into the margin. Computing line length is harder than one would think.

**Comment by simoncozens** [comment]
Here's the plot thickening:

```TeX
\font[size=10pt, family=Linux Libertine O, language=xx]
zana Bourova, zapolila ve ctyrech zavodech, nejlepe se umistila na Be-{}necku na 4. miste. Magdalena Chrastova skoncila na miste sedmnactem, Barbora Sulcova byla hned za

\font[size=10pt, family=Linux Libertine O, language=cs]
zana Bourova, zapolila ve ctyrech zavodech, nejlepe se umistila na Be-\goodbreak{}necku na 4. miste. Magdalena Chrastova skoncila na miste sedmnactem, Barbora Sulcova byla hned za
```

![screen shot 2015-08-15 at 09 16 02](https://cloud.githubusercontent.com/assets/106728/9288114/4fb1abdc-432e-11e5-8043-8fa3f2c16e0b.png)

Why is the third line of the second paragraph shorter? Because the period after "miste" has disappeared.

**Comment by alerque** [comment]
Oh that's special.

**Comment by alerque** [comment]
I think this has just become a different bug.

**Comment by simoncozens** [comment]
It's a bidi bug, and here's a MWE:

```
\begin[papersize=a5]{document}
\font[language=cs]
4 miste.

\bidi-off

4 miste.

\end{document}
```
