### ISSUE TITLE
Kerning fixes broke bidi test

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#171]
Commit 1f6a2fd which was to fix issue #170 broke `tests/mini-arabic.sil`. The four digit Arabic numeral dates are getting broken up and moved around in funny ways.

![selection_046](https://cloud.githubusercontent.com/assets/173595/9304490/6607a336-44f1-11e5-9f4f-49f16271a146.png)

**Comment by simoncozens** [comment]
This is a bit weird. It works fine on my computer with ICU enabled. (In #172, you mention that [travis fails](https://travis-ci.org/alerque/sile/jobs/75917937) but that's not moving about the dates; it's a couple of minor Y-coordinate mismatches. I don't know *why* there are Y-coordinate mismatches though.)

**Comment by alerque** [comment]
As far as the debug output of the test  goes, the couple of minor Y coordinates mismatches that show up on Travis are exactly the output I get on my system. It's only on visual review of the PDF that it is apparent that more is broken that the debug output suggests.

**Comment by simoncozens** [comment]
OK. I don't know what to do about this. I'm reverting parts of the kerning fix and reopening that bug.
