### ISSUE TITLE
Use ICU for bidi

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/sile#173]
ICU has a more complete and up to date implementation of the UBA than the Lua library SILE is currently using, and since ICU is already used for line breaking, it would be nice to use it (optionally at least) for bidi as well.

**Comment by simoncozens** [comment]
I would like to do this but I am not sure how. The problem I have is that we work in nodes that carry additional information, whereas the bidi algorithm works on strings. If you have input like "العربية a\color[color=red]{b}\em{c}d", how should we maintain the information about "b" and "c" while they are being reordered?

That is the specific problem, but I think there is a more general problem: I am not convinced in what order the various operations of tokenizing, breaking into nodes, bidi reordering, shaping, hyphenating, and line breaking should be applied. What we have at the moment works in most cases but I don't know if there is a better way to do it.

**Comment by behdad** [comment]
You apply things in the order you listed :).

It's not hard to modify FriBidi to expose the linked-list API, such that you don't have to compose a full array of bidi types to pass to it. Basically you apply the bidi algorithm and get back a linked-list of run *levels*.  You can attach the levels to your nodes at this time, and split nodes into multiple ones where levels change.  After you break lines, for each line there's a small additional modification to the run levels to be done (to whitespace at the end of line only), and after that.  In the end, you reorder nodes in the line using an algorithm like this:

https://github.com/behdad/linear-reorder/blob/master/linear-reorder.c

(Note, I have proved that implementation to be correct, but never tested it.  I should port Pango to use it.)

**Comment by simoncozens** [comment]
> You apply things in the order you listed :).

That's what we did before. But then, if you have eg RTL text within a LTR paragraph then the line breaking affects the bidi reordering - see #137. So now we do reordering after line breaking.

**Comment by behdad** [comment]
Yes, reordering happens at the very end.  Bidi is not a one-off operation.  It happens in stages.

**Comment by khaledhosny** [comment]
What Behdad said, and it is not different from what is done now; the code in `unicode-bidi-algorithm.lua` works on text strings as well (that is why it has a `node_to_table()` function; the idea was that it would make it easier to swap the Lua implementation with a native one). So I think would you need is:
* Convert node list to a string, using 0xFFFC for anything that is not a character.
* Use ICU to get the embedding levels of the string and assign them back to each node.
* Use the embedding levels to reorder the nodes, which I think can be done after line breaking.

**Comment by simoncozens** [comment]
OK. I think: 

* We have something which more or less works, and uses the right strategy, already.
* Using ICU would be nice but would require quite a bit of work.
* I don't know any of cases which are broken at the moment which would be fixed with ICU.

So I don't think I'm going to work on this, but I'd happily merge a patch which implemented it.
