### ISSUE TITLE
Bidi should not depend on frame direction

### ISSUE THREAD

**Issue by khaledhosny** [simoncozens/sile#175]
In this example:
```tex
\begin[papersize=a4]{document}
\font[language=ar,family=Amiri]
\thisframedirection[direction=RTL]
خالد
\end{document}
```
If I comment the frame direction line, the Arabic word is left aligned, which is correct, but the characters are reversed which is obviously wrong.

**Comment by khaledhosny** [comment]
Seems like `has_mixed_direction_material()` is the culprit, since bidi algorithm will not run if returns false which it obviously do here.

**Comment by simoncozens** [comment]
Yes, it should also check if there are nodes which are not the same directionality as the frame direction.

**Comment by khaledhosny** [comment]
I think the fact that frame direction has any say in the reversal of characters is a bug in itself.

**Comment by simoncozens** [comment]
OK, my current plan is to get SILE to always run the bidi algorithm, whether it's "needed" or not. This has the advantage of showing some bugs in the `reorder` function...

**Comment by simoncozens** [comment]
OK, we now do bidi everywhere. Let me know of any Arabic/RTL bugs you spot.
