### ISSUE TITLE
examples/japanese.pdf shows vertical Japanese, the one created by sile not

### ISSUE THREAD

**Issue by christianhorn** [simoncozens/sile#183]
- extracting sile-0.9.3.tar.bz2 , accessing examples/japanese.pdf shows vertical Japanese kanji
- ./configure && make -j6
- replacing "family=Hiragino Mincho Pro" in examples/japanese.sil with "Noto Sans JP" or other fonts
- running "./sile examples/japanese.sil", created japanese.pdf contains horizontal kanji

**Comment by simoncozens** [comment]
Hi Christian. I am currently working on ruby support in tate environments, so it's not quite working at the moment. However, to get vertical Japanese, set `layout=tate` in your document class settings. i.e. change:

    \begin[papersize=a4,class=jplain]{document}%

to

    \begin[papersize=a4,class=jplain,layout=tate]{document}%

**Comment by christianhorn** [comment]
Hi Simon,
indeed, thanks!
The examples are extremely useful for looking up ways to accomplish something. I was irritated getting a result differently from the shipped japanese.pdf .
Great work, thanks!
