### ISSUE TITLE
Class search path should include location of input file

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#184]
Trying to compile a sil file that is not in CWD is tricky if it references a special document class. The CWD is searched for `classes/<class>.lua`, but this is relative from the CWD. In many cases the desired path will be relative to the target sil file. That should be included in the standard set of paths searched.

**Comment by deepakjois** [comment]
This caused a regression. Please check my comments in #181.

**Comment by deepakjois** [comment]
I have temporarily fixed the regression like this:
https://github.com/deepakjois/sile/commit/5b346a6db7a430591424a8e17983dd0686e88df6
