### ISSUE TITLE
document.parindent setting not working at the beginning of document

### ISSUE THREAD

**Issue by deepakjois** [simoncozens/sile#188]
Using sile at HEAD:

```
\begin[papersize=a4]{document}%
\font[family=Kohinoor Devanagari,language=hi]
\set[parameter=document.parindent,value=0pt]
\font[style=Light]
दीपक जोइस

\font[style=Medium]
दीपक जोइस

\font[style=Bold]
दीपक जोइस
\end{document}
```

Produces output:
<img width="201" alt="screenshot 2015-11-10 10 07 01" src="https://cloud.githubusercontent.com/assets/5342/11054513/0221d046-8793-11e5-9c54-72835b4b0d9e.png">

I was expecting the first paragraph to not be intended as well.

**Comment by deepakjois** [comment]
looking at the code – it seems that when `document.parindent` is first set, `current.parindent` is not being updated, and this causes issues in the `newPar` function in `baseclass.lua`.

The workaround is to set `current.parindent` at the same time as document.parindent
```
\set[parameter=document.parindent,value=0pt]
\set[parameter=current.parindent,value=0pt]
```

**Comment by deepakjois** [comment]
It seems the right way to do it is to not set `current.parindent` to the `document.parindent` value as soon as it is declared (in the `init` function of `baseclass.lua`). It should be set to `nil`. The newPar function should first check if if `current.parindent` setting is non-nil. If it isn’t (i.e. it _is_ `nil`), then it should just use `document.parindent`.

**Comment by deepakjois** [comment]
I see that there are a lot of places in the packages, where `current.parindent` is being set, and then reset to `document.parindent`. If this change is acceptable, then we will need to change those places as well to remove the code that reset `current.parindent` to `document.parindent`

**Comment by simoncozens** [comment]
I don't see why we need to remove the code which reset it. `document.parindent` is essentially the "base" setting of the indentation for a document, If you change the indentation for a paragraph, it should go back to `document.parindent` after you've finished.

**Comment by deepakjois** [comment]
We could remove the code to reset it, because it is redundant. If you look at the change I made, this line in `newPar` already does the resetting:

```
typesetter:pushGlue(SILE.settings.get("current.parindent") or SILE.settings.get("document.parindent"))
```

**Comment by simoncozens** [comment]
OK, this make sense. Could you update your PR?

**Comment by deepakjois** [comment]
Sure. But it will take a while. Will do this weekend.
