### ISSUE TITLE
Hyphenation algorithm not UTF8-clean

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#195]
I haven't looked into _how_ this got allowed yet, but I just spotted a stray single-character hyphenation in a Turkish book I'm reviewing.

![selection_081](https://cloud.githubusercontent.com/assets/173595/11123997/51e237ae-896b-11e5-8249-bcb7a9e63ba6.png)

Also worth reviewing is whether breaking after a single syllable ending in a soft-g is allowed. It might be but I have an idea it's less than ideal:

![selection_082](https://cloud.githubusercontent.com/assets/173595/11124052/96c7102e-896b-11e5-977e-b8567a56fdea.png)

**Comment by simoncozens** [comment]
Looks like the first issue is a Unicode bug. In fact, the _hyphenate subroutine assumes that each character in the string is a byte long. The minimum left-hand of the string to be maintained before hyphenation is two bytes, but two bytes here is one character.

**Comment by simoncozens** [comment]
SILE now gives the same answers as TeX does. TeX: öǧ-re-ni-yo-ruz İmanlı

```lua
This is SILE 0.9.4-unreleased
> showHyphenationPoints("öǧreniyoruz", "tr")
"öǧ-re-ni-yo-ruz"
> showHyphenationPoints("İmanlı", "tr")
"İmanlı"

```
