### ISSUE TITLE
Forward slashes unexpectedly emiting line breaks

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#198]
So I was trying to typeset a URL just now:

	\begin{center}
	Via Christus Yayınları\break
	\url{https://www.viachristus.com}\break
	\url{viachristusyayinlari@gmail.com}
	\end{center}

But much to my surprise it came out like this:

![selection_083](https://cloud.githubusercontent.com/assets/173595/11154465/2f6715ea-8a48-11e5-8051-c98c784b8189.png)

The goose chase took me to the URL package [line 21](https://github.com/simoncozens/sile/blob/master/packages/url.lua#L21) from a2325d8.

    local breakpat = options.breakpat or "/"

Can I ask when one would want to break URL's on forward slashes?

**Comment by simoncozens** [comment]
These should be `\goodbreak`s - decent places to break the line - but for some reason they are being interpreted as mandatory breaks.

**Comment by simoncozens** [comment]
Here's a minimal test:

    \begin[papersize=a4]{document}
    Good\penalty[penalty=-500]break

    \set[parameter=document.rskip,value=0 plus 10000pt]
    Good\penalty[penalty=-500]break
    \end{document}

**Comment by simoncozens** [comment]
And TeX does the same thing. That's annoying.

**Comment by alerque** [comment]
Color me surprised._‹/sarcasm›_

**Comment by simoncozens** [comment]
Think I've got it. TeX's URL package uses positive, not negative, penalties. Testing now.
