### ISSUE TITLE
Nesting inline functions doesn't behave as expected

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#199]
I'm a little confused about how nested inline markup functions are supposed to work. Here is a MWE that does something different than I expected and I'm not sure how to do properly: 

	\begin{document}
	\begin{script}
	local inputfilter = SILE.require("packages/inputfilter").exports
	SILE.registerCommand("uppercase", function(options, content)
	SILE.process(inputfilter.transformContent(content, string.upper))
	end, "Typeset the enclosed text as uppercase")
	\end{script}
	\define[command=wrapper]{\uppercase{How is this \process}}
	Normal casing.

	\uppercase{Upper cased.}

	\wrapper{line cased?}
	\end{document}

I would have expected the last line to be fully in upper case. Instead it's only half there:

![selection_085](https://cloud.githubusercontent.com/assets/173595/11163579/b9357b78-8add-11e5-9a75-3d3929861cd7.png)

What's going on here?

**Comment by simoncozens** [comment]
I think what is happening here is that inputfilter only filters input. `\process` is implemented as a command; inputfilter doesn't operate on the output of commands, just on the input text.
