### ISSUE TITLE
Can Lua functions be locale enabled?

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#200]
How can a Lua function be made locale aware? I have a string processing function that needs to be aware of the language. Ideally the current document output language value would be passed, but even if the system locale value was being obeyed this would work:

	local inputfilter = SILE.require("packages/inputfilter").exports
	SILE.registerCommand("uppercase", function(options, content)
	SILE.process(inputfilter.transformContent(content, string.upper))
	end, "Typeset the enclosed text as uppercase")

Currently calling this function from my section typesetter:

    SILE.call("uppercase", {}, content)

…on content like this:

    \section{Müjdeyi Bilmek}

…turns out this catastrophe:

![selection_086](https://cloud.githubusercontent.com/assets/173595/11163640/bfe1a26a-8adf-11e5-966e-783e7b03ee47.png)

This is what needs to have happened:

![selection_087](https://cloud.githubusercontent.com/assets/173595/11163641/c36277fc-8adf-11e5-9a38-abeb28589a0a.png)

How can I make a document language (or locale) aware string processing function?

**Comment by simoncozens** [comment]
If you are on lua 5.3, then `utf8 = require("utf8")` and use `utf8.upper` instead of (the dumb, character-by-character, non-UTF8-aware) `string.upper`.

**Comment by khaledhosny** [comment]
Also, being locale dependent in not a good idea for typesetting software (change the locale e.g. process the document on a different machine, and you get different output). If some code needs to be aware of the language, it should use the document language.

**Comment by alerque** [comment]
@khaledhosny Good point.

**Comment by alerque** [comment]
@simoncozens You sure about that? The Lua 5.3 [documentation for the utf8 module](http://www.lua.org/manual/5.3/manual.html#6.5) does not include a `utf8.upper()` command at all, nor was I able to get one.

I installed the luarock for [lua-utf8](https://github.com/starwing/luautf8) and got `utf8.upper()` out of it, but I was unable to figure out a way to set the language. As a result it was able to uppercase `ü` to `Ü` but not knowing the string was Turkish it transformed `i` to `I` instead of `İ`.

@starwing perhaps you have some input into this?

**Comment by simoncozens** [comment]
Sorry, you're right, it's the lua-utf8 module you want. I thought the utf8 library included in 5.3 was compatible, but it's not.

And yes, I don't know of any Lua Unicode library that does full Unicode CLDR-aware case mapping. You would basically need to wrap ICU to get that. The luatex people would love it if you did, too.

**Comment by alerque** [comment]
Ouch, that burns.

I bludgeoned my way through today's problem with this hacktastic function:

	local utf8 = require("lua-utf8")
	local inputfilter = SILE.require("packages/inputfilter").exports
	SILE.registerCommand("uppercase", function(options, content)
	  content[1] = content[1]:gsub("i", "İ")
  	  SILE.process(inputfilter.transformContent(content, utf8.upper))
	end, "Typeset the enclosed text as uppercase")

But long term I guess making the luatex folks happy is on the menu.

**Comment by simoncozens** [comment]
Here you go, as of db1afa2:

```
This is SILE 0.9.4-unreleased
> icu = require("justenoughicu")
> icu.case("ismir", "en", "upper")
"ISMIR"
> icu.case("ismir", "tr", "upper")
"İSMİR"
>
```

**Comment by alerque** [comment]
Happy dance!
