### ISSUE TITLE
Pullquote package has developed issues

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#202]
Recent changes to the typesetting engine seem to have broken the `pullquote` package. I see two things that are failing:

1. In the stand alone example, the first line of quotes are getting offset. This isn't a normal paragraph indent (which should be off anyway) because it's running over the end of the line:

   ![selection_088](https://cloud.githubusercontent.com/assets/173595/11164000/d300033e-8aec-11e5-8454-de60e87764bb.png)

1. In the embeded documentation example, the first problem is showing up but there is another one—the quote marks are duplicated:
 
   ![selection_089](https://cloud.githubusercontent.com/assets/173595/11164001/db934420-8aec-11e5-8513-722a943a9f60.png)

**Comment by simoncozens** [comment]
Any chance you could bisect for me?

**Comment by alerque** [comment]
Sure but it will be a couple days.

**Comment by simoncozens** [comment]
Bisected to "[bfc14ec068d371fa2d93f458574549d40a149b3d] I am unsure about this change. It doesn’t seem to break anything, which shows that we need a lot more tests for hbox".

Commit message says it all.
