### ISSUE TITLE
What the font? It's all downhill from here…

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#203]
Starting at commit c3fc882 some of my fonts are unable to stand upright. Crimson for example, is perpetually falling over. Yes, it has a Roman style. Furthermore some font weights no longer work. Montserrat for example is always normal no matter what weight you request; 600 would normally load the bold and 800 would load the black faces. No longer.

	\begin[papersize=a7]{document}
	\begin{raggedright}
	\font[family=Montserrat,weight=600]{One two}\break
	\font[family=Libertine Serif]{buckle my shoe}

	\font[family=Montserrat,weight=600]{Three four}\break
	\font[family=Crimson]{buckle my shoe}
	\end{raggedright}
	\end{document}

![selection_092](https://cloud.githubusercontent.com/assets/173595/11164915/5c67cd40-8b07-11e5-93ab-a062404f2cb9.png)

Here is a reference of how this should have rendered:

![selection_091](https://cloud.githubusercontent.com/assets/173595/11164916/6c16b4fe-8b07-11e5-8842-48fe0e7ccc24.png)

My system font list looks something like this:

	❯❯❯ fc-list | pcregrep '(Crimson|Montserrat|Libertine Serif)' | sort
	/usr/share/fonts/OTF/Crimson-BoldItalic.otf: Crimson:style=BoldItalic
	/usr/share/fonts/OTF/Crimson-Bold.otf: Crimson:style=Bold
	/usr/share/fonts/OTF/Crimson-Italic.otf: Crimson:style=Italic
	/usr/share/fonts/OTF/Crimson-Roman.otf: Crimson:style=Roman
	/usr/share/fonts/OTF/Crimson-SemiboldItalic.otf: Crimson:style=SemiboldItalic
	/usr/share/fonts/OTF/Crimson-Semibold.otf: Crimson:style=Semibold
	/usr/share/fonts/OTF/libertineserif-bolditalic.otf: Libertine Serif:style=Bold Italic
	/usr/share/fonts/OTF/libertineserif-bold.otf: Libertine Serif:style=Bold
	/usr/share/fonts/OTF/libertineserifdisplay-regular.otf: Libertine Serif Display:style=Regular
	/usr/share/fonts/OTF/libertineserifinitials-regular.otf: Libertine Serif Initials:style=Initials
	/usr/share/fonts/OTF/libertineserif-italic.otf: Libertine Serif:style=Italic
	/usr/share/fonts/OTF/libertineserif-regular.otf: Libertine Serif:style=Regular
	/usr/share/fonts/OTF/libertineserif-semibolditalic.otf: Libertine Serif:style=Semibold Italic
	/usr/share/fonts/OTF/libertineserif-semibold.otf: Libertine Serif:style=Semibold
	/usr/share/fonts/TTF/MontserratAlternates-Bold.ttf: Montserrat Alternates:style=Bold
	/usr/share/fonts/TTF/MontserratAlternates-Regular.ttf: Montserrat Alternates:style=Regular
	/usr/share/fonts/TTF/Montserrat-Black.ttf: Montserrat:style=Black
	/usr/share/fonts/TTF/Montserrat-Bold.ttf: Montserrat:style=Bold
	/usr/share/fonts/TTF/Montserrat-Light.ttf: Montserrat,Montserrat Light:style=Light,Regular
	/usr/share/fonts/TTF/Montserrat-Regular.ttf: Montserrat:style=Regular
	/usr/share/fonts/TTF/MontserratSubrayada-Bold.ttf: Montserrat Subrayada:style=Bold
	/usr/share/fonts/TTF/MontserratSubrayada-Regular.ttf: Montserrat Subrayada:style=Regular
	/usr/share/fonts/TTF/Montserrat-Thin.ttf: Montserrat:style=Thin

**Comment by alerque** [comment]
Desperate to use new goodies appearing in HEAD without cherry-picking a stream of commits, I hacked on this a little bit and discovered that if I add `style=Roman` to any and all font calls that use Crimson and `style=bold` or `style=Black` to all calls for Montserrat I can get the correct faces and weights. I'm still not sure why this is a breaking change for these fonts when others continue to work as before, but for now I can tweak my documents to keep compiling.

**Comment by simoncozens** [comment]
Perhaps the answer is to set the default style in font.lua to the blank string (and also in fontconfig.c) and only add the style pattern to the match if it's set to something other than blank. If fontconfig is sensible it will choose the upright by default.

**Comment by alerque** [comment]
Fontconfig does default to the correct font:

    ❯❯❯ fc-match Crimson
    Crimson-Roman.otf: "Crimson" "Roman"

**Comment by simoncozens** [comment]
Try that patch, then. If it does the right thing for you, I'll fix up the tests.

**Comment by alerque** [comment]
That's negative on this one. Looking at the patch I'm even more confused. In testing this, the weight issue seems to have been resolved for Montserrat, but the style issue for Crimson & Libertine Serif is the same, both of them default to italic unless I specify Roman & Regular respectively.

**Comment by alerque** [comment]
For the record, the patch from #286 does fix the Italic/Roman issue with Crimson. It doesn't touch the weight issue. However if I cherry pick 6d71f77 back into the mix the weight issue is also resolved, so both together make my MWE above (and a few other combos tested) work as expected.

**Comment by alerque** [comment]
This is behaving entirely as expected for me now.
