### ISSUE TITLE
Lua throwing error in new frame:isAbsoluteConstraint() function

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#209]
I haven't been able to replicate this yet in a MWE but in a big example with a custom class file the latest SILE HEAD version is throwing this at me:

> Error detected:  
> /usr/local/share/sile/core/frame.lua:167: attempt to index a number value (local 'c')

Would it be helpful if I work on paring down a minimal case to replicate this or is it obvious to somebody else what is tripping up this code?

**Comment by simoncozens** [comment]
Try that patch.

**Comment by alerque** [comment]
Works, thanks! And I only know that because I just beat on it and came up almost the same thing in dd2921e and came here to PR it.
