### ISSUE TITLE
Value of rskip inside quote environment carried over into first footnote on page

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#210]
Check out this three page spread:

![selection_101](https://cloud.githubusercontent.com/assets/173595/11263420/3cd176cc-8e93-11e5-9e68-d86c7ebfd885.png)

The first page is all good. So is the second really, but note that the page break between two and three happens in the middle of a quote environment. Now check out the indentation of the first footnote on the third page (footnote 80).

**Comment by simoncozens** [comment]
Could you try adding `SILE.settings.reset()` into the footnote package here:

    local material = SILE.Commands["vbox"]({}, function()
      SILE.Commands["font"]({size = "9pt"}, function()
        SILE.settings.reset() -- this line
        SILE.call("noindent")
        SILE.typesetter:typeset(SILE.formatCounter(SILE.scratch.counters.footnote)..".")
        SILE.call("qquad")
        SILE.process(content)
      end)
    end
    )

Let me know if it breaks other stuff.

**Comment by alerque** [comment]
Edit: this isn't actually a page break issue, I just realized it's happening when the `\footnote` marker is inside the quote.

(Trying your code now…)

**Comment by alerque** [comment]
No change when adding `SILE.settings.reset()` to my footnote function.

**Comment by alerque** [comment]
Here's some output with the reset in place. It's also from the middle of a page and note the only one affected is the one marked from inside the quote. The font size is wrong, but otherwise everything is the same as before.

![selection_103](https://cloud.githubusercontent.com/assets/173595/11263972/6a0e2766-8e98-11e5-83a8-aa1ab7b34efa.png)

**Comment by alerque** [comment]
Hey that's better. Thanks!
