### ISSUE TITLE
No (apparent) way to set baselineskip inside footnote frame

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#211]
Setting the line spacing between footnotes works:

    SILE.scratch.insertions.classes.footnote.interInsertionSkip = SILE.length.parse("0.5ex")

But no value I can find and set even from the footnote function itself seems to effect the baselineskip value used when footnote content wraps. The value from the document body is used all the time. This isn't very obviously bad in the default settings where the footnote font size is only slightly smaller than the body and the inter-footnote size is comparable. But increase the baseline skip in the main document, reduce the inter-footnote spacing and footnote font size and suddenly you have an eye-sore. See for example what happens in footnote 58 here:

![selection_102](https://cloud.githubusercontent.com/assets/173595/11263589/c31c5660-8e94-11e5-9233-5293a6693b1f.png)

Here is a MWE to play with:

	\begin[papersize=a7,class=book]{document}
	\begin{script}
	SILE.settings.set("document.baselineskip", SILE.nodefactory.newVglue("4ex"))
	SILE.scratch.insertions.classes.footnote.interInsertionSkip = SILE.length.parse("0.5ex")
	\end{script}
	This\footnote{And by "this" I mean the .sil file} is just a test\footnote{Actually it's not a test so much as a demonstration or minimum working example in an attempt to figure out how the baselineskip value it set in footnotes.}. It doesn't work\footnote{Yet.}. But maybe if a brain with more values pre-loaded were to look at the code…
	\end{document}

**Comment by alerque** [comment]
So after the fix for #210, I found one way that actually gets the job done. I'm not sure if this is the right—or even a sane— way to do this, but setting the line spacing method after the reset actually allows the leading to be adjusted. My current footnote over-rides look like this:

  local insertions = SILE.require("packages/insertions")
  SILE.registerCommand("footnote", function(options, content)
    SILE.call("footnotemark")
    local opts = SILE.scratch.insertions.classes.footnote
    local f = SILE.getFrame(opts["insertInto"])
    local oldT = SILE.typesetter
    SILE.typesetter = SILE.typesetter {}
    SILE.typesetter:init(f)
    SILE.typesetter.pageTarget = function () return 0xFFFFFF end
    SILE.settings.pushState()
    SILE.settings.reset()
    SILE.settings.set("linespacing.method", "fit-font")
    SILE.settings.set("linespacing.fit-font.extra-space", "0.3ex")
    local material = SILE.Commands["vbox"]({}, function()
      SILE.Commands["book:footnotefont"]({}, function()
        SILE.call("noindent")
        SILE.typesetter:typeset(SILE.formatCounter(SILE.scratch.counters.footnote)..".")
        SILE.call("quad")
        SILE.process(content)
      end)
    end)
    SILE.settings.popState()
    SILE.typesetter = oldT
    insertions.exports:insert("footnote", material)
    SILE.scratch.counters.footnote.value = SILE.scratch.counters.footnote.value + 1
  end)

  SILE.scratch.insertions.classes.footnote.topSkip = SILE.length.parse("3ex plus 0 minus 0")
  SILE.scratch.insertions.classes.footnote.interInsertionSkip = SILE.length.parse("0.5ex plus 0 minus 0")

**Comment by simoncozens** [comment]
Merging with #204.
