### ISSUE TITLE
Inter-footnote spacing gets pushed around

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#212]
Besides the issue in #211 with the baseline skip, sometimes the value of `interInsertionSkip` gets pushed around. I think sometimes it expands, but it definitely gets squished for no apparent reason. See for example the two marked instances here:

![selection_105](https://cloud.githubusercontent.com/assets/173595/11264183/3e2e62bc-8e9a-11e5-8623-c201f8c5633b.png)

On the second page there it's hard to tell what happened, but it's possible that the whole footnote  moved down creating both a too-large and too-small space.

I've attempted to set a value that shouldn't shrink, but it still keeps happening:

    SILE.scratch.insertions.classes.footnote.interInsertionSkip = SILE.length.parse("0.5ex plus 0 minus 0")

**Comment by simoncozens** [comment]
I think this is the same bug as #213, and if not, at least the title of that bug is general enough to cover both issues...
