### ISSUE TITLE
Allowed length formats inconsistent

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#215]
I've noticed that I frequently have to use trial and error to figure out how to send length parameters. I'm sure there are reasons the format varies, but as an end user it's rather confusing. For example consider:

    SILE.settings.set("linespacing.fit-font.extra-space", ".5em")

Great. But now how about:

    SILE.settings.set("linebreak.emergencyStretch", "1em")

Nope. That won't work, you need this:

    SILE.settings.set("linebreak.emergencyStretch", SILE.length.parse("1em"))

But that's not all. Some frequently user set values that (to my mind) are lengths actually need to be passed glue objects with the length already set. 

    -- Wrong:
    SILE.settings.set("document.rskip", "1em")
    -- Wrong:
    SILE.settings.set("document.rskip", SILE.length.parse("1em"))
    -- Right:
    SILE.settings.set("document.rskip", SILE.nodefactory.newGlue("1em"))

Unless of course your using tex-like markup, then a length value gets made into a glue for you

    \set[parameter=document.rskip,value=1em]

So in the first example we had a decimal value less than 1. It worked fine there; but just try it here:

    \skip[height=.5em]

Nope. You have to prefix it with leading zero to be recognized as a number:

    \skip[height=0.5em]

Some measure of consistency to how length parameters are parsed would go a long way towards increasing usability.

**Comment by simoncozens** [comment]
I've fixed the last part (numbers don't need a leading zero), and done some reworking on the linespacing settings, so I think this is now fixed. Yes, when you are calling `SILE.settings.set` you don't get automatic type conversion. Think of it as a means to ensure you know what you're actually doing. ;-)
