### ISSUE TITLE
Error building bibtex.sil example

### ISSUE THREAD

**Issue by Earnestly** [simoncozens/sile#218]
* sile version: https://github.com/simoncozens/sile/commit/683c0d7a37429b3b5c11ad08376a0f8cd14b54b9

During my initial exploration with this tool I was building all of the example sil files and came across this error when building `bibtex.sil`:

```
% sile bibtex.sil 
This is SILE 0.9.4-unreleased
<bibtex.sil>

Error detected:
/usr/share/sile/packages/bibtex.lua:27: attempt to index a nil value (local 'fh')
```

**Comment by simoncozens** [comment]
That's an error opening the file. I've added a check and message for the error; see what it's giving you.

**Comment by Earnestly** [comment]
That fixed it.  And now the error is clear as many other packages also depended on the relative path `examples/asset` which was worked around by moving up into the project root and running `sile examples/foo.sil`.

Thanks again
