### ISSUE TITLE
Bigger infinity causes libtexpdf crash

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#227]
Using the latest HEAD commit, I'm getting funny errors from some of my documents:

    This is SILE 0.9.4-unreleased
    <mujdenin_gucu-kitap.sil>
    [1] [2] [3] 
    libtexpdf:fatal: CFF: Parsing CFF DICT failed. (error=-1)

I tried narrowing it down to something in the document, and got as far as these:

    \titlepage
    \publicationpage
    \tableofcontents

I found that if I removed `\publicationpage` _AND_ either `\titlepage` or `\tableofcontents` I could compile the rest fine. Oddly enough removing just the publication page doesn't seem to do the trick. All of these pages involve either `\vfill` or `\hfill`.

Reverting 69a63b7 fixes this crash (but obviously re-opens the issue it was meant to solve).

**Comment by simoncozens** [comment]
Wow. I was trying to track that down (Travis tests are failing). I had *no* idea that would be the cause. Could you try naking infinity progressively smaller until the strangeness goes away?

**Comment by simoncozens** [comment]
1E13 seems to be infinite enough to fix 226; does it cause CFF errors?

**Comment by alerque** [comment]
My CFF error starts somewhere between 1e107 and 1e108.

**Comment by alerque** [comment]
I just ran into this again. Apparently 1e100 doesn't actually keep us safe. The funny thing is the EXACT same document works with larger page sizes it's only when the page size is at a certain size (below a certain point) that this blows up.

**Comment by simoncozens** [comment]
Have you tried 1e13?

**Comment by alerque** [comment]
I'm experimenting with values right now.

**Comment by alerque** [comment]
In my particular case, 1e98 worked, 1e99 died. I tested the test case from issue #122 and 1e7 seemed to be the magic order of magnitude that mashed the math into line. Just a few orders orders of magnitude on that should be plenty, and if not something else is likely broken. So 1e13 sounds fine to me.
