### ISSUE TITLE
Footnote separators can get separated from their footnotes

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#229]
So I was playing around with extreeme values trying to figure out what gets pushed around by what and ran into some cases where the new `\footnote:separator` command's contents can get split. First a real life context:

![selection_125](https://cloud.githubusercontent.com/assets/173595/11457700/52c057d2-96b8-11e5-9c4e-23f9d35ddb46.png)

Then an MWE:

	\begin[papersize=a7,class=book]{document}
	\script[src=packages/rules]
	\footnote:separator{\hrule[width=20pt,height=0.5pt]\skip[height=10ex]}
	Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\footnote{Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco.} Foobar baz quux quuux.
	\end{document}

![selection_122](https://cloud.githubusercontent.com/assets/173595/11457697/4c698e4e-96b8-11e5-8e4b-a33afdfdaf10.png)

**Comment by simoncozens** [comment]
OK, I think I have fixed this in new-insertions. Give it a go.
