### ISSUE TITLE
Body font reset after footnote marker

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#231]
Footnote markers are resetting the main typesetter's font attributes.

	\begin[papersize=200pt x 100pt,class=book]{document}
	\nofolios
	\font[family=Architects Daughter,size=20pt]
	Alice\footnote{not Bob}in Wonderland\footnote{not Carol's}
	\end{document}

![selection_127](https://cloud.githubusercontent.com/assets/173595/11469311/19b3a01a-975e-11e5-978a-fcc557ff09cf.png)

**Comment by simoncozens** [comment]
Closed (hopefully) by your PR.
