### ISSUE TITLE
\dotfill spacing inconsistent when only two dots are required

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#243]
If the space requires many dots it works great. It also works if it can't fit any, and the case of one ends up nicely centered. However if space for two dots is allocated, the dots end up off center.

![selection_135](https://cloud.githubusercontent.com/assets/173595/11609459/b1f27678-9b8f-11e5-941c-0d5508c25a46.png)

**Comment by simoncozens** [comment]
Does this look better? I think it's not just a "repetitions==2" bug but an odd/even bug:
![screen shot 2015-12-07 at 13 24 43](https://cloud.githubusercontent.com/assets/106728/11619014/f0ec7e9e-9ce5-11e5-852a-566b70aa86eb.png)

**Comment by alerque** [comment]
Yes that looks better; but it doesn't look great either. Any one of those by themselves looks fine, but in the common use-case of a TOC there will be a bunch of them together as above and the inconsistent start/end points depending on the amount the space stretches looks bad. I'm wondering the prettiest way wouldn't be to calculated the width of the leading and trailing spaces as fixed width (i.e. no stretching allowed). In that case the single dot becomes a special case but everything after that becomes increments of `<fixed space><dot>(<flexible space><dot>)*<fixed space>`.

**Comment by simoncozens** [comment]
Current attempt: 
![screen shot 2016-03-21 at 23 24 15](https://cloud.githubusercontent.com/assets/106728/13918520/25791da6-efbc-11e5-82e1-b1778d600b08.png)

**Comment by alerque** [comment]
I like it and can't think of how I'd improve it. On a case by case basis there might be more optimal settings  but this seems to strike a good balance and looks good out of the box.
