### ISSUE TITLE
latin-in-tate broken

### ISSUE THREAD

**Issue by shirat74** [simoncozens/sile#244]
The following example

    \begin[papersize=a4,class=jplain,layout="tate"]{document}
    \latin-in-tate{Hello world.}
    \end{document}

gives an error:

    Error detected:
    /usr/local/share/sile/packages/tate.lua:96: attempt to compare number with table

The comparison

    nodes[i].width > 0

seems to be giving an error.

**Comment by simoncozens** [comment]
This is driving me crazy. It works on my development machine (OS X), but it fails on Travis (and on your machine). But on Linux VM I have set up to mirror the Travis environment, it works.

**Comment by shirat74** [comment]
I got the error on Ubuntu with Lua version 5.1.
Now tried on Windows10 with Lua 5.2 and found no error...

 I don't know what is the problem exactly but maybe it depends on Lua version?

**Comment by simoncozens** [comment]
I think I've fixed it now. We test Lua versions 5.1, 5.2 and 5.3 in the Travis build. The reason the test wasn't working nicely for me before was that it was giving a (different) error which the test framework wasn't picking up.
