### ISSUE TITLE
Turkish hyphenation screws up punctuation that English gets right

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#247]
Somehow the English language knows about not breaking before quotation marks whereas the Turkish does not. This causes some bad wraps, such as this one:

![selection_137](https://cloud.githubusercontent.com/assets/173595/11632689/c650c098-9d10-11e5-9b2d-d8841877ed1b.png)

Here is a MWE:

	\begin[papersize=a7,class=book]{document}
	\script{SILE.scratch.counters.footnote.value = 1234567890}
	\set[parameter=linebreak.emergencyStretch,value=2em]
	\font[language=en]
	This is a test line where I quote Bob as saying, “I didn't say tiddlysquat.”\footnote{I made this up.}

	\font[language=tr]
	This is a test line where I quote Bob as saying, “I didn't say tiddlysquat.”\footnote{I made this up.}
	\end{document}

**Comment by alerque** [comment]
Here's another example of a bad breakpoint:

![selection_138](https://cloud.githubusercontent.com/assets/173595/11659111/30722110-9dcf-11e5-80ca-1382c231bc45.png)

(That's a real Unicode ellipsis (…))

Also I found the same example as above (closing curly quote then footnote reference at the end of a paragraph) that wrapped to the next page all by itself! Mustn't have that!

**Comment by simoncozens** [comment]
Yeah, it's not separating out punctuation from the rest of the text. A fix is needed to the Lua Unicode tokenizer. I *think* if you have ICU compiled it will work.

**Comment by simoncozens** [comment]
Actually now looking at the English tokeniser, that doesn't seem to care about splitting tokens according to punctuation either - which means if your English examples work it's only by chance. So maybe we should just scrap the "basic" tokeniser and concentrate on making the Unicode one work.

**Comment by simoncozens** [comment]
OK, I'm very confused by this. I don't see a bad break in your Turkish MWE above. And replacing the basic nodemaker with the Unicode one shows that that *does* correctly separate out punctuation from the text nodes. So if anything was broken, it would have been English...

**Comment by alerque** [comment]
My MWE compiles differently now than it did 2 days ago. Something since then changed this behavior and now English fails too where it seemed to be working before. I can't think of any case where a break should happen just before a closing quote mark where there is no whitespace before the mark. Footnotes are correctly not breaking between the marker and what comes before them, but line are getting split in the middle of sequences like `."` and `?"`.

**Comment by simoncozens** [comment]
OK, I can see one myself now, in `examples/test.sil` page 17. Will try and work out what the tokenizer is up to.
