### ISSUE TITLE
Inhibit line breaks on non-breaking spaces

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#249]
As long as SILE is starting to respect assorted Unicode conventions, it would be nice if it respected and refused to break lines on non-breaking space characters such as [`\U+00A0`](https://en.wikipedia.org/wiki/Non-breaking_space). There are whole categories of breaking vs. non-breaking whitespace characters and the tokenizer could be made aware of them.

**Comment by simoncozens** [comment]
Looks like the non-ICU thingy makes a nonbreaking space, but the ICU one inserts a penalty because it's seeing the NBS as a word break. Bah.
