### ISSUE TITLE
Each footnote causes some lost space in content frame

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#252]
This may or may not be related to issue #234, but the more footnotes are on a page, the more space is lost. An MWE explains it best:

    \begin[papersize=a7,class=book]{document}
    \script[src=packages/frametricks]
    \script[src=packages/lorem]
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}.
    This is a test\footnote{What happens to frames?}. \lorem[words=10]
    This is a test\footnote{What happens to frames?}. \lorem[words=10]
    This is a test\footnote{What happens to frames?}. \lorem[words=10]
    This is a test\footnote{What happens to frames?}. \lorem[words=10]
    This is a test\footnote{What happens to frames?}. \lorem[words=10]
    This is a test\footnote{What happens to frames?}. \lorem[words=150]
    \end{document}

If you do something (such as [this patch](https://github.com/simoncozens/sile/files/65688/showframe.patch.txt)) that will show the location of frames for each page, you'll see that the content and footnote frames overlap by an amount linearly related to how many footnotes are on that page:

![selection_142](https://cloud.githubusercontent.com/assets/173595/11876330/d3d95dcc-a4f1-11e5-9790-e0b502c6dc71.png)

**Comment by simoncozens** [comment]
Grr. OK, insertions are still not quite right. I will keep looking at this. By the way, if you debug insertions (`--debug=insertions`) then it will automatically show you the frames on the page.

**Comment by alerque** [comment]
Thanks for the debug tip. Let me know if there is anything I can do to further this.
