### ISSUE TITLE
Whitespace handling off inside temporary settings

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#254]
I reported something similar regarding right alignment in #154 which was fixed, but I've just noticed it still does something similar inside temporary settings. In the [attached MWE](https://github.com/simoncozens/sile/files/76299/mwe.zip), you can see this in the quotation block. For reference, the sources I'm using here are `mwe.sil` and `mwe.lua`:

----

    \begin[papersize=a5,class=book]{document}
    \script[src=packages/linespacing]
    \set[parameter=linespacing.method,value=fit-font]
    \set[parameter=linespacing.fit-font.extra-space,value=1.40ex]
    \script[src=packages/lorem]
    \script[src=mwe]
    \font[language=tr]
    “Kutsal Tanrımız’ın yüce müjdesi”nin, kırpılmış bir müjde veya daha az
    yücelik içeren bir müjde ile yer değiştirdiğini gördüğümüzde yakında
    duruyor ve hiçbir şey yapmıyorsak bu bizi ne laik kişiler ne de müjde
    hizmetkârı haline getirir.\footnote{1. Timoteos 1:11} Bu gerçeğin
    kâhyası olarak korumamız, onu herkese cesaretle ve açıkça vaaz etmemiz
    gereken gerçek bir müjde vardır. Charles Haddon Spurgeon’un sözlerine
    kulak verirsek iyi ederiz:

    \begin{quote}
    Bugünlerde kendimi müjdenin temel gerçeklerinin tekrar tekrar üzerinden
    geçmeye mecbur hissediyorum. Huzurlu zamanlarda, kendimizi uzaklardaki
    ilginç bölgelere doğru gezinti yapmakta özgür hissederiz. Ama şimdi evde
    kalmalı ve imanın ilk ilkelerini savunarak kilisenin yüreğini ve evini
    korumalıyız. Çağımızda kilisenin içinde, sapkınca şeyler söyleyen
    insanlar ortaya çıktı. Felsefeleri ve alışılmadık yorumları ile bizi
    sıkıntıya sokacak, ortaya koydukları öğretim ile doktrini inkâr edecek
    ve sürdürmeye söz verdikleri imanı baltalayacak birçok insan olacaktır.
    Bazılarımızın neye inandığımızı bilmesi, sözlerimizde herhangi gizli bir
    anlamın bulunmaması iyi bir şey, ayaklarımızı yere indirip duruşumuzu
    korumalıyız, yaşam sözünü vaaz etmeli ve yalın bir şekilde İsa Mesih’in
    müjdesinin temel gerçeklerini ilan etmeliyiz.\footnote{Charles H.
      Spurgeon, \font[style=italic]{The Metropolitan Tabernacle Pulpit}
      (repr., Pasadena, Tex.: Pilgrim Publication), 32:285.}
    \end{quote}

    Müjdenin Korunması serisi bütün sistematik müjdeyi temsil etmemesine
    rağmen, çok sayıda temel unsuru adres göstermektedir, bunlar özellikle
    de çağdaş Hristiyanlık tarafından en çok ihmal edilen unsurlardır.
    Umudum o ki, bu sözler, müjdeyi utancı ve kurtaran gücü dahil bütün
    güzelliği ile yeniden keşfetmeniz için bir rehber olur. Duam, böyle bir
    yeniden keşfin yaşamlarınızı değiştirmesi, müjde vaazınızı güçlendirmesi
    ve Tanrı’ya en büyük yüceliği getirmesidir.

    Tanınmış din adamı ve ilahi yazarı keşiş Augustus Toplady, ünlü ilahisi
    Çağların Kayası’nda aynı güçlü duyguları dile getirir:

    \begin{quote}
    \poetry Ellerimin işleri\break
    Senin yasanın buyruklarını yerine getiremez.\break
    Çabamın hiçbir anlamı yoktur,\break
    Ya da akıttığım gözyaşlarımın\break
    Bunlar ödeyemez günahın bedelini\break
    Yalnızca Sen kurtarabilirsin, ya Rab.

    Getirebileceğim hiçbir şey yok ellerimde,\break
    Yalnızca çarmıha sığınabilirim.\break
    Çıplak geldim sana giysi için,\break
    Çaresiz, lütfun için;\break
    Boş, kaynaktan dolmak için,\break
    Yıka beni kurtarıcım, yoksa öleceğim.
    \end{quote}
    \end{document}

-----

    SILE.registerCommand("quote", function(options, content)
      local setback = options.setback or "20pt"
      SILE.call("medskip")
      SILE.settings.temporarily(function()
        SILE.settings.set("document.rskip", SILE.nodefactory.newGlue(setback))
        SILE.settings.set("document.lskip", SILE.nodefactory.newGlue(setback))
        SILE.settings.set("current.parindent", SILE.nodefactory.zeroGlue)
        SILE.settings.set("document.parindent", SILE.nodefactory.zeroGlue)
        SILE.settings.set("document.parskip", SILE.nodefactory.newVglue("10pt"))
        SILE.process(content)
        SILE.typesetter:pushGlue(SILE.nodefactory.hfillGlue)
        SILE.call("par")
      end)
      SILE.call("medskip")
    end)

    SILE.registerCommand("poetry", function()
        SILE.settings.set("document.lskip", SILE.nodefactory.newGlue("30pt"))
        SILE.settings.set("document.rskip", SILE.nodefactory.hfillGlue)
        SILE.settings.set("typesetter.parfillskip", SILE.nodefactory.zeroGlue)
    end)

----

Note also if you remove the rskip setting from the above the result is even more broken.

Additionally (and this may or may not be related) there is extra space being applied after `\break` commands that goofs up my attempt at a poetry environment.

![selection_146](https://cloud.githubusercontent.com/assets/173595/12074961/ae9ef614-b178-11e5-8ac9-4ed0db7379ab.png)

**Comment by alerque** [comment]
I still don't know if this is one issue or two, but here is a simpler MWE for the space-at-beginning-of-line part:

	\begin[papersize=a5]{document}
	\raggedright{
	\font[weight=600]{This} is a sample of bogus\break
	extra space.

	\font[weight=600]{This} doesn't have\break
	{}extra space.
	}
	\end{document}

Note the `\raggedright` isn't even necessary for this demonstration as the space before "extra" shows up either way, that only makes it easier to see.

**Comment by alerque** [comment]
To add insult to injury, I just realized I can't even add an glue object there if I wanted one:

	\begin[papersize=a5]{document}
	\raggedright{
	Why can't I even manually add a space after a break as in\break
	\qquad{}here.
	}
	\end{document}

That's right, there is unwanted space there if you take out the `\qquad` but adding that command removes the space.

**Comment by simoncozens** [comment]
Not sure what I am meant to be seeing here:

![Uploading Screen Shot 2016-01-10 at 15.12.33.png…]()

**Comment by simoncozens** [comment]
The second problem (manually adding a glue object at the start of a line) is caused by the vbox output routine, which eats initial spaces and penalties. Normally at the start of a line, there is a dummy hbox inserted, but `\break` doesn't do this. Maybe it should. On the other hand, removing the glue-eater from the vbox output routine doesn't seem to break any tests, so maybe it would be more predictable to do it that way instead. I am not sure.

**Comment by alerque** [comment]
Wait what? That's the MWE above and nothing else? Because I get this:

![selection_148](https://cloud.githubusercontent.com/assets/173595/12220310/a2c70a12-b776-11e5-80cd-edc7a7ca0715.png)

**Comment by simoncozens** [comment]
Oh boy it's an ICU bug.

**Comment by alerque** [comment]
Oh lovely.

**Comment by alerque** [comment]
I'm not sure how related these two issues are or aren't, but #255 has similarities (with justification not working out right) but with the added twist not seen in this issue that hyphenation goes away.
