### ISSUE TITLE
Some content breaks hyphenation in my quote environments

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#255]
As of yet I have been unable to put together a MWE for this one, so here is a 2m video instead. I'm on SILE head from this morning.

https://youtu.be/_0H3-ni2JDI

Some content on the first line doesn't trigger this. Some does. The some content later in the paragraph doesn't beak, only messing with the first line seems to trigger this. This example isn't very egregious and it almost looks like it doesn't _need_ hyphenation, but there are other cases where my emergency stretch is running out and things are ending up very ugly.

@simoncozens You have the source to this document (and I'll post it for anybody else wanting to take a look). Roughly my quote environment looks like this:

	SILE.registerCommand("quote", function(options, content)
	local setback = options.setback or "20pt"
	SILE.call("medskip")
	SILE.settings.pushState()
	SILE.settings.temporarily(function()
		SILE.settings.set("document.rskip", SILE.nodefactory.newGlue(setback))
		SILE.settings.set("document.lskip", SILE.nodefactory.newGlue(setback))
		SILE.settings.set("current.parindent", SILE.nodefactory.zeroGlue)
		SILE.settings.set("document.parindent", SILE.nodefactory.zeroGlue)
		SILE.settings.set("document.parskip", SILE.nodefactory.newVglue("1.5ex"))
		SILE.process(content)
		SILE.settings.set("document.parskip", SILE.nodefactory.zeroVglue)
		SILE.typesetter:pushGlue(SILE.nodefactory.hfillGlue)
		SILE.call("novbreak")
		SILE.call("par")
		SILE.call("novbreak")
	end)
	SILE.settings.popState()
	SILE.call("medskip")
	SILE.call("novbreak")
	end, "Typeset quototion blocks")

**Comment by alerque** [comment]
Issue #254 is actually pretty similar to this, but it's showing an alignment issue even when hyphenation works. It's possible than the alignment isn't working in either case, but only when the hyphenation goes away is it becomes more obvious.

**Comment by alerque** [comment]
I suspect this is another outcropping of the same underlying issue, but I'm not sure. For some reason SILE has decided it's okay to break words at punctuation marks. But again the only place I'm seeing this is inside environments where the right alignment has gone haywire (could this be related to me setting `rskip`?). Here's one example:

![selection_150](https://cloud.githubusercontent.com/assets/173595/12296925/45212452-ba13-11e5-96ab-c2bf67553274.png)

**Comment by simoncozens** [comment]
Still not investigated yet but that screams ICU bug to me.

**Comment by simoncozens** [comment]
No, it's not an ICU bug. It's a bug related to (the use of) "emergencyStretch". You've told the line breaker that there is an additional 3em of stretchiness available on each line, but with a narrow environment like your quote, there isn't ever going to be that much total stretch available between the words. Hence, the words don't get justified. They aren't being hyphenated because if there were as much stretch available as SILE thinks there is, they wouldn't need to be - there'd just be really big spaces between unhyphenated words.

3em is the default for a "sloppy" environment in TeX, so I think that's probably too much for a default setting of a document, and doubly so for a narrow column. Try reducing the emergencyStretch setting in your quote environment (perhaps to zero).

**Comment by alerque** [comment]
Interesting. This brings us to an interesting impasse though because I found I had to add the emergency stretch in the first place because a was getting a tone of hangovers. This way gives some bad lines but was bearable, the out of frame stuff wasn't. I'll have another go at fixing that issue without resorting to sloppy mode, but overall something isn't quite right.

**Comment by simoncozens** [comment]
I've had a play with it, and I think the problem is that the spaces in the font are insufficiently stretchable and shrinkable, and SILE can't find enough hyphenation breakpoints in Turkish to get good line justification all of the time. Instead of using emergency stretch, try making the space value more flexible. I got good results with `\set[parameter=document.spaceskip,value=2.5pt plus 2.5pt minus 1pt]`.

**Comment by alerque** [comment]
Thanks for looking into this and specifically playing with my document. It's getting better and it's going to be good. However I think you're on the wrong track with this bug. Don't get me wrong—the settings you've suggested definitely help the typesetting overall, but they don't fix this bug. This isn't unique to this font or unique to narrow content widths (which I don't think this even qualifies for) and it isn't just a Turkish problem. The justification is simply not working at all. Really nice settings can make it look like its getting close but at the end of the day it's not aligning.

Here's the thing. Take a paragraph—any paragraph in any document, language and font you like. Play with it until you have at least a couple hyphens going on. Now wrap it in

    SILE.settings.pushState()
    SILE.settings.temporarily(function()
	SILE.settings.set("document.rskip", SILE.nodefactory.newGlue("0pt"))
    SILE.process(content)
    end)
    SILE.settings.popState()

As far as line wrap and justification go, this should net zero change. Nothing relevant should be getting changed. The thing is, for me this breaks justification. Hyphens end up outside the margin, things that lined up just a second ago suddenly don't.

If I take out the left and right skip values from my quote environment everything works perfectly. But if I touch it at all—even to make it negative and thus wider or zero as in above—the line break stops getting justified.

Somewhere there is another bug. Why does changing the rskip cause unrelated functions to process differently than with an unset value?

**Comment by simoncozens** [comment]
You might be right but I'm having real trouble seeing it. This document is what you describe, but both sets of output are identical.

```
\begin[papersize=a6]{document}
\script[src=packages/frametricks]
\script{
SILE.registerCommand("donothing", function(o,c)
  SILE.settings.pushState()
SILE.settings.temporarily(function()
  SILE.settings.set("document.rskip", SILE.nodefactory.newGlue("0pt"))
  SILE.process(c)
  SILE.call("par")
end)
SILE.settings.popState()
end)
}

\set[parameter=document.spaceskip,value=2.5pt plus 2.5pt minus 1pt]

experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation

\begin{donothing}
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
\end{donothing}
\showframe[id=all]
\end{document}
```

**Comment by alerque** [comment]
My bad, I plead dyslexia. Change rskip to lskip in my last comment above. It testing your example above setting lskip instead of rskip does change the rendering.

**Comment by simoncozens** [comment]
OK, it does, and I have a test case! But in this case, it is putting the hyphen at the start of lines as well as the end (and I know why, so that's easily fixed). But you hadn't mentioned line-initial hyphens before - perhaps this is a different bug?

**Comment by alerque** [comment]
@simoncozens I only saw the line-initial hyphens in this test case, not in my document. Playing with it now I do see hyphens end up on the next line by setting a negative r/l skip value, but in that case they are not duplicated they are just moved and sometimes are not even the first character on the new line. It looks like the line break is getting applied before the lskip value and then the line is getting re-broken but not re-spaced? Or something like that.

**Comment by simoncozens** [comment]
What's happening is the lskip/rskip glue is ending up at the end (or start) of the line, and hence the prebreak/postbreak components of the discretionary are no longer at their expected places at the end or start of the line, so SILE is not marking them correctly for output. It *might* fix the initial issue but I'll deal with it tomorrow.

**Comment by simoncozens** [comment]
How is this looking now? With the latest version, better space stretchiness and less emergency stretch, are you still getting badly justified lines?

**Comment by alerque** [comment]
Something is still off here. It changed, but it's still broken. Now either lskip or rskip seem to behave fine on their own, but in combination they still  break the alignment mechanism. Check out this variant of the MWE above:

```
\begin[papersize=a6]{document}
\script[src=packages/frametricks]
\script{
SILE.registerCommand("donothing", function(o,c)
  SILE.settings.pushState()
SILE.settings.temporarily(function()
  SILE.settings.set("document.lskip", SILE.nodefactory.newGlue("19pt"))
  SILE.settings.set("document.rskip", SILE.nodefactory.newGlue("1pt"))
  SILE.process(c)
  SILE.call("par")
end)
SILE.settings.popState()
end)
}

\set[parameter=document.spaceskip,value=2.5pt plus 2.5pt minus 1pt]

experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation

\begin{donothing}
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation experimental hyphenation
\end{donothing}
\showframe[id=all]
\end{document}
```

Play with the 19/1 combo. Unset either value and change the other value to 20 (so that different widths isn't a factor) and watch how it lines up perfectly, but when both values are set to a positive amount it goes splat.

**Comment by simoncozens** [comment]
Thanks, that's a great test case!

**Comment by alerque** [comment]
Close but not quite. This works for the test case above where rskip is explicitly set to 0, but setting it to a non-zero value (as in a real use-case) does nothing: the value is discarded and the text is typeset flush against the right of the frame.

**Comment by alerque** [comment]
@simoncozens Closing this as from my perspective this seems to be fixed now. Don't worry I'll make noise if I find something else broken, but the use cases I have seem to be rendering as expected now. MUCH thanks!
