### ISSUE TITLE
Font-relative lengths are being absolutized

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#261]
Post #255 being fixed, I figured it was time to see if I really needed the `spaceskip` hack mentioned there. I was having trouble with headings and figured removing it would make things work again. It didn't.

What I discovered instead is that the logic of when spaceskip gets set is all out of whack. The biggest issue is that it isn't scoped to the current font size. I understand the confusion caused by setting in manually as opposed to leaving it be calculated from the font —hence the need to reset it in for example the `\ragged…` functions— but when not setting it manually it needs to be a bit more adaptive.

Check for example this MWE:

```
\begin[papersize=a6]{document}
\raggedright{
\font[size=4pt]
This is a test of spaces.\break
\font[size=30pt]
This is a test of spaces.
}
\end{document}
```
![selection_154](https://cloud.githubusercontent.com/assets/173595/12783955/080c9bc0-ca8d-11e5-92ee-4929756aee72.png)

In normal usage I can't think of any reason that changing the font size shouldn't also change the size of spaces to match. In my use case I'm over-riding the font's space size with a more flexible size to get out of hyper-hyphenation-hell. This works for the body, but all my headings, title pages, etc. are smashed together with the space size from the base document. Unless I wrapper them all in temporary settings environments and manually reset the value they look horrible.

**Comment by mhosken** [comment]
Does specifying the dimension in em rather than pt help?

**Comment by alerque** [comment]
@mhosken No, it doesn't. I tried that early on thinking that as the deal and it didn't change anything.

**Comment by simoncozens** [comment]
This one is due to the fact that "relative" sizes (such as em sizes) are immediately turned into points and then forgotten about. In fact, all lengths are.They should ideally be stored in a data structure which remembers that they are ems.

**Comment by alerque** [comment]
I'm not sure the unit of measure matters here so much as the fact that the measure isn't getting re-calculated after a font size change. Even when it's NEVER been set and is being calculated from the font, that only works once, then sticks no matter the font size changes.

**Comment by jvgaultney** [comment]
I'm having trouble with the same bug. I'm constructing a class for font proofing and testing and it's vital that the space be accurately calculated. I'm setting everything ragged, so currently everything is wrongly spaced.

**Comment by simoncozens** [comment]
Just a quick hit-and-run as I still haven't had time to look into this: note that the `linespacing` package avoids this issue by storing the sizes as strings. (As does TeX) This may or may not be the most elegant solution - it's obviously simpler than storing a tagged data structure, but it's a bit cruder. But basically, everywhere you see `toPoints` in the core should be considered potential sources of this bug.

**Comment by simoncozens** [comment]
Please test branch `relative-lengths`. If this works we can also set the default interline space to be 1.2em, for example, and have that change nicely with font size.

**Comment by alerque** [comment]
@simoncozens That branch is bombing for me with a message like this:

```
Error detected:
/usr/local/share/sile/core/nodefactory.lua:252: attempt to perform arithmetic on a table value (field 'length')
```

**Comment by simoncozens** [comment]
What's happening is that relative lengths should now be absolutized at point of use, but I'm not sure I've caught all the points of use yet.

**Comment by simoncozens** [comment]
I've just merged this. Cry havoc and let slip the dogs of war!
