### ISSUE TITLE
Font-relative lengths picking up the wrong base size

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#266]
Using the current state of the `relative-lengths` branch, I'm getting strange results inserting glue objects.

```
\begin[papersize=a6]{document}

\font[size=20pt]
\center{
\glue[width=1ex]WORD\break
TO THE WISE
}
\medskip

\font[size=1pt]

\center{
\font[size=20pt]
\glue[width=1ex]WORD\break
TO THE WISE
}
\medskip

\center{
\font[size=20pt]
\glue[width=10pt]WORD\break
TO THE WISE
}

\end{document}
```

![selection_160](https://cloud.githubusercontent.com/assets/173595/13049020/8d18d04a-d3f2-11e5-9050-bd46c4137c35.png)

Note the `\font[size=1pt]` in the middle of that (outside of the center environments). Note that changing that value will push around the size of the 1ex glue in both the previously output block (in spite of the `\font[size=20pt]` above it) _AND_ the one following it that has a local font size declaration of its own.

**Comment by simoncozens** [comment]
Fixed (I think)
