### ISSUE TITLE
Update Harfbuzz version in Travis build

### ISSUE THREAD

**Issue by brawer** [simoncozens/sile#267]
In the Travis build for SILE, would it make sense to update [HARFBUZZ_BASE](https://github.com/simoncozens/sile/blob/master/.travis.yml#L18)? Currently it is set to 1.0.4, which is quite old. The most recent [release](https://www.freedesktop.org/software/harfbuzz/release/) is 1.1.3.

**Comment by alerque** [comment]
True story. The only thing I would add is that we should wait until we get the test suite passing again (there are currently some other issues) before adding this in there just so that we can see if anything breaks.

**Comment by simoncozens** [comment]
We're up to 1.2.3 now, so that's what we'll test against.
