### ISSUE TITLE
Pages aligned with \vfill broken

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#268]
Commit af5d008 has broken my page layouts that rely of `\vfill` to typeset blocks at the bottom of the page content frame. By having a `\vfill` tacked onto the end of the page makes it balance out to the center of the page rather than the end. That's not to say my usage was correct, just that something that seemed to Work For Me™ no longer does.

My two main use cases are for

* a publisher credits page, several paragraphs but aligned to end at the bottom of the page rather than start at the top
* a title page with the publisher logo pushed down to the bottom of the page rather than being just below the title

Either of these could be manually tweaked another way, but I'm generating layouts for several page sizes and `\vfill` was the most logical solution I could come up with.

**Comment by simoncozens** [comment]
I think your usage was wrong (sorry). Use a `\par\break` instead to eject the page without pushing the material up the page I think this is consistent with TeX usage too.

**Comment by alerque** [comment]
Roger that.
