### ISSUE TITLE
Wrong language tag for “undefined”

### ISSUE THREAD

**Issue by brawer** [simoncozens/sile#270]
Currently, there’s a few places in the SILE source code where `xx` indicates an undefined or unknown language. However, assuming that SILE wants to use the same [IETF BCP-47 language tag system](https://www.w3.org/International/articles/language-tags/) as XML and pretty much everyone else these days, the correct tag for “unknown/undefined” would be `und`.

https://github.com/simoncozens/sile/search?utf8=%E2%9C%93&q=xx

**Comment by alerque** [comment]
Sticking with that standard makes a lot of sense to me. The `xx` has always bothered me but I didn't know there was even a standard tag for undefined. I put together a PR with the necessary changes.

**Comment by simoncozens** [comment]
Good catch, and nice fix. Thank you both!
