### ISSUE TITLE
Document how to use font fallbacks

### ISSUE THREAD

**Issue by brawer** [simoncozens/sile#279]
Could the SILE manual document how to use `font-fallback.lua`?

I’m trying to typeset a multilingual document with fonts from a local directory (not installed on the system). However, I’m not sure how to make fallbacks work within this set of fonts.

**Comment by simoncozens** [comment]
Font fallbacks is an open problem, as it currently doesn't work with bidirectionality. See #191.

And at the moment it doesn't work with local directory fonts; it should do that, if we can find a nice syntax.

**Comment by alerque** [comment]
In most cases for a multi-lingual document you will need more than the font to change. You also need other things like the hyphenation routine to know what language being used. Given that this is currently set as an argument to the same function that sets the font, I'm not quite sure why you couldn't set the font at the same time you tag the language of the content. For documents where I switch back and forth a lot I've created 'alias' commands that set all the necessary properties for every language switch.

Given that the font fallback system isn't really fully developed yet I'd be curious to know what use case you have for this. Having a few use cases spelled out might help development along in a way that will prove useful in the end. Surely emoji isn't the only use case where setting the language does not also need to be done anyway. What does a "multilingual document" look like for you @brawer?
