### ISSUE TITLE
Call FcWeightFromOpenType() for mapping CSS weights

### ISSUE THREAD

**Issue by brawer** [simoncozens/sile#281]
Currently, SILE maps CSS font weights to a fixed set of fontconfig enums; see [source code](
https://github.com/simoncozens/sile/blob/83a0f17f5e6b284b0e2392ed0f36f32ebd6619b6/src/justenoughfontconfig.c#L48). To support arbitrary font weights, could SILE call [FcWeightFromOpenType()](https://www.freedesktop.org/software/fontconfig/fontconfig-devel/fcweightfromopentype.html)? See [freedesktop bug 81453](https://bugs.freedesktop.org/show_bug.cgi?id=81453) for justification.

Note that `FcWeightFromOpenType()` has been added in fontconfig version 2.11.91, which was released in December 2014. Perhaps it might be good to check whether the function is available, and fall back to the current code if SILE is compiled/linked against an older version of fontconfig.

**Comment by simoncozens** [comment]
Sounds like a good idea; you can check the `FC_MAJOR/FC_MINOR/FC_REVISION` ifdefs to ensure the version. Send me a pull request?
