### ISSUE TITLE
XML: tag vs. command

### ISSUE THREAD

**Issue by ff2000** [simoncozens/sile#288]
I want to record (longer) notes I read in an ordered way. (I also want to try something new and get more into SILE ;)) I thought this would be easy with sile, as it has an XML-flavour. Well... ;)
I want to store certain properties, that don't fit into a key/value-pair in a still readable way, so I want to put them into a text-node. But (as I understand it) those end up being SILE-commands.
This would not be a big issue in theory. Just define simple commands (as explained in the docs) and I am done.
BUT: I want to output those properties in a given order, and I probably want to change the order without having to change the XML file.
In tex I simply wrote a small python-program that parsed the data file and printed latex, defined a latex-command, that ran the program. I definitely can do the same with SILE, but I wanted to utilize the built-in XML-support - if possible. So - is that possible?

**Comment by alerque** [comment]
SILE's XML format isn't meant to be a data storage format, it's meant to be a representative of a typeset document. It is an output format, not an input or storage format. It sounds like you probably want to create your own data format and then use and XML parser to transform it to the way you want it to be arranged before shipping it off for typesetting.

**Comment by ff2000** [comment]
Ok, thx for the clarification. I already thought this would be the way to go, but one never knows :)
