### ISSUE TITLE
./configure ends with: error: cannot find Lua libs

### ISSUE THREAD

**Issue by pepa65** [simoncozens/sile#296]
On Ubuntu 14.04, cloned the git repo, made sure libharfbuzz, libfreetype6, fontconfig, lua-lpeg-dev, lua-expat-dev, lua-filesystem wera all installed. Bootstrap ran fine, libtoolize gave a number of warnings:
```
libtoolize: `build-aux/ltmain.sh' is newer: use `--force' to overwrite
libtoolize: `m4/libtool.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltoptions.m4' is newer: use `--force' to overwrite
libtoolize: `m4/ltversion.m4' is newer: use `--force' to overwrite
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.

```
./configure ended in: `configure: error: cannot find Lua libs`

Very interested in trying out Sile, looking forward to some pointers..!

**Comment by pepa65** [comment]
After reading https://github.com/simoncozens/sile/pull/275 I got this idea:
`ln -s /usr/lib/x86_64-linux-gnu/liblua5.2.so /usr/lib/x86_64-linux-gnu/liblua.so`
Now `./configure && echo OK` end OK, but
`sudo make install` has justenoughharfbuzz_la-justenoughharfbuzz.lo not finding lua.h
I thought this would solve it, but it didn't:
```
mkdir /usr/include/lua
ln -s /usr/include/lua5.2/lua.h /usr/include/lua/
```

**Comment by alerque** [comment]
I'm a little confused by these errors, I'm note sure those libtoolize warnings have anything to do with your real problem as returned in the final exit code. Are there any lines in the output specific to lua libraries?

**Comment by alerque** [comment]
Also, do you know if Ubuntu has some sort of wrapper or environment hacking going on that allows you to toggle the default `lua` interpreter version?

**Comment by pepa65** [comment]
It would be nice if autoconf would take setups into account that have lua5.1 and lua5.2 but not plain lua.
Unfortunately, I don't yet know much about lua...

**Comment by pepa65** [comment]
Funny... When I do `lua -v` it answers `Lua 5.1.5` -- I had assumed it would default to 5.2

**Comment by alerque** [comment]
You said you installed lua-lpeg-dev, lua-expat-dev, and lua-filesystem, but were those packages for your system default of lua of version 5.1?

**Comment by simoncozens** [comment]
Try this:

./configure LUA=`which lua` LUA_INCLUDE=-I/usr/local/include/lua5.2/ LUA_LIB=-llua.5.2

**Comment by pepa65** [comment]
Well... After trying the different permutations for:
`./configure LUA=$(which lua) LUA_INCLUDE=-I/usr/local/include/lua5.?/ LUA_LIB=-llua5.?`
I found lua5.2 wasn't installed itself... After that both the 1/2 and the 2/2 variety came through configure OK.
```
But after both cases, when I do `sudo make install` it ends here:
libtool: compile:  gcc -DPACKAGE_NAME=\"SILE\" -DPACKAGE_TARNAME=\"sile\" -DPACKAGE_VERSION=\"0.9.3\" "-DPACKAGE_STRING=\"SILE 0.9.3\"" -DPACKAGE_BUGREPORT=\"simon@simon-cozens.org\" -DPACKAGE_URL=\"\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DHAVE_LUA_H=1 -DHAVE_LUALIB_H=1 -DHAVE_LAUXLIB_H=1 -DHAVE_LUACONF_H=1 -DLIBTHAI=1 -DICU=1 -DSILE_PATH=\"/usr/local/share/sile\" -DSILE_LIB_PATH=\"/usr/local/lib/sile\" -I. -I/usr/include/freetype2 -I/usr/include/lua5.2/ -I/usr/include/harfbuzz -g -O2 -MT fontmetrics_la-fontmetrics.lo -MD -MP -MF .deps/fontmetrics_la-fontmetrics.Tpo -c fontmetrics.c  -fPIC -DPIC -o .libs/fontmetrics_la-fontmetrics.o
fontmetrics.c:3:23: error: missing binary operator before token "("
 #if HB_VERSION_ATLEAST(1,1,3)
                       ^
make[1]: *** [fontmetrics_la-fontmetrics.lo] Error 1
make[1]: Leaving directory `/home/pp/git/sile/src'
make: *** [install-recursive] Error 1
```

**Comment by pepa65** [comment]
I guess people on Ubuntu is sort of an edge case for you guys. It would be nice if Sile would just be in the repos. Or even on a PPA.

**Comment by alerque** [comment]
@pepa65 Ubuntu is not an edge case, the release process just hasn't been through very many iterations. I've gotten packaging working on the Linux distro I use,  and poked at a couple others. However there has only been one release since I got involved and we still need to work out a lot of things about the  whole release cycle and packaging. Having an Ubuntu PPA or at least a deb package seems like a reasonable thing. Along these lines I'd like to see a few more point releases (even if they are much smaller steps than the last few) so that we can have the release process worked out before tagging it 1.0.0. Ease of getting up and running is going to be nearly as important as how the typesetter works in encouraging adoption.

**Comment by pepa65** [comment]
That sounds very reasonable. Glad to hear Ubuntu's not an edge case, because it's the main OS (in its variations) I use. Are you on Arch?

**Comment by alerque** [comment]
Yes, Arch Linux here. There are currently `sile` and `sile-git` packages in the AUR.

I also setup a Homebrew package for Mac, but there are outstanding issues with Lua there too (#143).

**Comment by simoncozens** [comment]
We use Travis to test SILE on every commit, and Travis uses Ubuntu, so we have to and we do support Ubuntu! However Travis is on Ubuntu 12.02 - maybe something is different in Trusty. I'd like to get Travis doing integration checks on its beta environment too, which runs 14.04.

In particular it looks like something is going weird evaluating the Harfbuzz version check macro.  (Ping @behdad)

Which version of Harfbuzz is being installed?

**Comment by pepa65** [comment]
```
dpkg -l |grep harfbuzz
ii libharfbuzz-dev 0.9.27-1ubuntu1 amd64 Development files for OpenType text shaping engine
ii libharfbuzz-gobject0:amd64 0.9.27-1ubuntu1 amd64 OpenType text shaping engine ICU backend (GObject library)
ii libharfbuzz-icu0:amd64 0.9.27-1ubuntu1 amd64 OpenType text shaping engine ICU backend
ii libharfbuzz0b:amd64 0.9.27-1ubuntu1 amd64 OpenType text shaping engine (shared library)
ii libharfbuzz0b:i386 0.9.27-1ubuntu1 i386 OpenType text shaping engine (shared library)
```

**Comment by simoncozens** [comment]
Bah, before 0.9.30, the macro used to be called `HB_VERSION_CHECK`:

    commit 2b051c6057920c564c13c5d6a3e6dca93446fa12
    Author: Behdad Esfahbod <behdad@behdad.org>
    Date:   Fri Jun 20 14:09:57 2014 -0400

      Rename HB_VERSION_CHECK and hb_version_check to "atleast"

      HB_VERSION_CHECK's comparison was originally written wrongly
      by mistake.  When API tests were written, they were also written
      wrongly to pass given the wrong implementation... Sigh.

      Given the purpose of this API, there's no point in fixing it
      without renaming it.  As such, rename.

      API changes:

        HB_VERSION_CHECK -> HB_VERSION_ATLEAST
        hb_version_check -> hb_version_atleast

Oh boy. How do we work around this one?

**Comment by behdad** [comment]
Do this:

```
#ifndef HB_VERSION_ATLEAST
#define HB_VERSION_ATLEAST(major,minor,micro) \
        ((major)*10000+(minor)*100+(micro) <= \
         HB_VERSION_MAJOR*10000+HB_VERSION_MINOR*100+HB_VERSION_MICRO)
#endif
```
and use that one instead of HB_VERSION_CHECK().

**Comment by pepa65** [comment]
In my local tree, the only occurrence of HB_VERSION is in `src/fontmetrics.c`:
`#if HB_VERSION_ATLEAST(1,1,3)`
There is no HB_VERSION_CHECK here...

**Comment by simoncozens** [comment]
Yeah, I was using `HB_VERSION_ATLEAST` but that wasn't available for older HB versions. Now I've added the definition for  `HB_VERSION_ATLEAST` if it's not provided, into `fontmetrics.c`, so please update and try a build again.

**Comment by pepa65** [comment]
OK, pulled, built and installed. On run:
```
This is SILE 0.9.4-unreleased

! libtexpdf backend not available! at nil
/usr/bin/lua: core/utilities.lua:18: attempt to index field 'outputter' (a nil value)
stack traceback:
	core/utilities.lua:18: in function 'error'
	core/sile.lua:46: in function 'init'
	/usr/local/bin/sile:11: in main chunk
	[C]: in ?
```

**Comment by simoncozens** [comment]
So the `libtexpdf` backend built, but couldn't be loaded. Could you do:

     % sile
    This is SILE 0.9.4-unreleased
    > require("justenoughlibtexpdf")

and tell me what the error is?

**Comment by pepa65** [comment]
I don't understand the instructions. Where do I put the `require("justenoughlibtexpdf")`? Note that after running sile on the commandline, it dumps.

**Comment by simoncozens** [comment]
Ah, of course; it wouldn't get as far as the REPL. OK, I'm going to look at this in a few days when I can play with a Trusty image myself. Sorry about this - this really is the kind of environment where it should just work, which makes it doubly confusing when it doesn't.

**Comment by pepa65** [comment]
Great, thanks for working on this.

**Comment by mvz** [comment]
@pepa65 did you end up installing a lua dev package (e.g. `liblua5.1-0-dev`)? This is what I had to do to get SILE to build on Debian.

@simoncozens what is the reason for compiling Lua on Travis instead of using Ubuntu's lua packages?

**Comment by simoncozens** [comment]
Until recently Travis only supported Ubuntu Precise, which doesn't have any lua packages.

**Comment by pepa65** [comment]
Sorry, I've migrated (am migrating) to 16.04, haven't gotten around to trying anything with Sile. Anybody tried this yet?

**Comment by mvz** [comment]
@pepa65 I have SILE 0.9.3 working on Debian. In addition to the lua dev package, I had to manually run `sudo ldconfig` to allow it to find `libtexpdf.so.0` when run outside of the checked out source.

**Comment by simoncozens** [comment]
Yeah, I bet you `ldconfig` is the answer. It only works on Travis because we set `LD_...` environment paths manually.

**Comment by olivierberten** [comment]
In case it's useful, I put up a rough packaging at https://launchpad.net/~olivier-berten/+archive/ubuntu/sile

As I'm definitely no packaging expert, feel free to give me improvement advices ;-)

**Comment by pepa65** [comment]
Thank you Olivier. I installed sile after adding your PPA, and it pulled in lua5.2, but did nothing on the harfbuzz front. What is the purpose of the harfbuzz package in your PPA? (I can't even find it when I do apt search harfbuzz...)
Also, isn't it good to include the lua classes in git/tests as well?

**Comment by Rombersoft** [comment]
Repositor

> In case it's useful, I put up a rough packaging at https://launchpad.net/~olivier-berten/+archive/ubuntu/sile
> 
> As I'm definitely no packaging expert, feel free to give me improvement advices ;-)

Repository is unreachable

**Comment by pepa65** [comment]
When executing `sudo add-apt-repository ppa:olivier-berten/sile` it ends with:
```
E: The repository 'http://ppa.launchpad.net/olivier-berten/sile/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```
It is a great pity that such a promising project is proving so hard to install...
