### ISSUE TITLE
Corrupt PDF files

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#297]
Something is off in the encoding of PDF files. For the last month or more I've been seeing intermittent issues with PDFs being generated that don't open in all PDF readers. Whatever the problem is it  doesn't happen all the time and it doesn't trip up all readers, only some of them. Whenever it fails, it fails across the same set of programs. Usually once it starts happening, it will keep generating corrupt  files until I twiddle something in the document, then it has a chance of coming up clean again. Long/complex documents turn up corrupt more often, but I can't put my finger on what the trigger is.

Always can read:

* Zathura & other MuPDF based readers
* Adobe Reader DC
* Chrome's internal reader

Always fail on "corrupt" files:

* OSX Preview
* Evince & other Poppler based readers
* Firefox's internal & other PDF.js based readers

I have not been able to come up with an MWE. I could send a sample of a "corrupt" file in but it's unpublished work so I don't want to post it publicly yet.

**Comment by alerque** [comment]
Message from PDF.js on failed files is:

> PDF.js v1.1.469 (build: f06aa6a)  
> Message: Invalid PDF structure

**Comment by alerque** [comment]
Zathura successfully opens the 'corrupt' PDFs when using the MuPDF backend (the optional Poppler one dies), but it does report this to the console which might be useful:

> (zathura:11951): Gtk-WARNING **: Failed to set text from markup due to error parsing markup: Error on line 1 char 18: Odd character '>', expected a '=' after attribute name 'Title' of element 'No'

**Comment by alerque** [comment]
The `diffpdf` utility won't open the 'corrupt' files. The GUI error isn't very informative, but these did come to the console:

> "Error: Couldn't find trailer dictionary" 
> "Error: Couldn't find trailer dictionary" 
> "Error: Couldn't read xref table" 
> "Error: Couldn't find trailer dictionary" 
> "Error: Couldn't find trailer dictionary" 
> "Error: Couldn't read xref table"

**Comment by simoncozens** [comment]
Can you email me one?

**Comment by alerque** [comment]
Sent.

**Comment by alerque** [comment]
I just ran into this  with two consecutive runs on the same host with exactly the same source. Run 1 came up corrupt (wouldn't open in Evince, opened in Zathura). I ran it again without having done anything else and it came up clean. Like an idiot I forgot to stash a copy of the corrupt version before re-running so I don't have that pair to compare, but it does rule out a lot of potential sources for this to have the same system give different results back to back.

**Comment by simoncozens** [comment]
It's fine; I should be able to debug it with the examples you sent me. I have become rather adept at reading PDFs in a text editor...

**Comment by alerque** [comment]
Sadly that didn't fix didn't resolve this. I'm still getting bad builds.

**Comment by alerque** [comment]
Ignore the above (and the email I just sent). I was testing the wrong commit.
