### ISSUE TITLE
Why is the line height not being considered before hbox's?

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#298]
In my quest for typesetting books directly from Markdown I'm I'm trying to come up with a basic function for typesetting series pages using meta yaml data. For some series this data has authors, for some it doesn't so there are two forms.  The Pandoc template is feeding SILE code that looks like this:

``` TeX
\seriespage:series{Müjde Koalisyonu}
\seriespage:title[author=Philip Graham Ryken]{Aklanma}
\seriespage:title[author=Richard D. Phillips]{Gerçeği Bilebilir Miyiz?}
\seriespage:title[author=Reddit Andrews III]{Günah ve Düşüş}
\seriespage:title[author=Sam Storms]{Her Şeyin Yenilenmesi}
\seriespage:title[author=Tim Savage]{Kilise: Tanrı’nın Yeni Halkı}
\seriespage:title[author=Kevin L. DeYoung]{Kutsal Ruh}
\seriespage:title[author=Sandy Willson]{Mesih'in Kefareti}
\seriespage:title[author=D. A. Carson ve Timothy Keller]{Müjde Merkezli Hizmet}
\seriespage:title[author=Bryan Chapell]{Müjde Nedir?}
\seriespage:title[author=Mike Bullmore]{Müjde ve Kutsal Yazılar: Kutsal Kitap'ı Nasıl Okumalıyız?}
\seriespage:title[author=Colin S. Smith]{Plan}
\seriespage:title[author=Stephen T. Um]{Tanrı'nın Krallığı}
\seriespage:title[author=Thabiti Anyabwile ve J. Ligon Duncan]{Vaftiz ve Rab'bin Sofrası}
\seriespage:title[author=Andrew M. Davis]{Yaratılış}
```

Some of these will fit nicely on one line, some will not. If necessary I wanted it to wrap before the author rather than anywhere else in the line so I wrapped the author in an hbox.

``` Lua
SILE.registerCommand("seriespage:series", function(options, content)
  SILE.call("center", {}, function()
    SILE.call("book:chapterfont", {}, function()
      SILE.process(content)
      SILE.typesetter:typeset(" Serisi’ndeki Kitaplar") 
      SILE.call("book:chapter:post")
    end)
  end)
end)

SILE.registerCommand("seriespage:title", function(options, content)
  SILE.call("raggedright", {}, function()
    SILE.settings.set("current.parindent", SILE.nodefactory.newGlue("-2em"))
    SILE.settings.set("document.lskip", SILE.nodefactory.newGlue("2em"))
    if not options.author then
      SILE.call("font", { style="Italic", language="und" }, content)
      SILE.call("medskip")
    else
      SILE.call("font", { style="Bold", language="und" }, content)
      SILE.typesetter:typeset(" ") 
      SILE.call("hbox", {}, function()
        SILE.typesetter:typeset("— ") 
        SILE.call("font", { style="Italic", language="und" }, function() 
          SILE.typesetter:typeset(options.author) 
        end)
      end)
      SILE.call("smallskip")
    end
  end)
end)
```

This _almost_ worked. The breaks are happening at the right place. First the author drops to the next line and only if necessary does the title also get split. However the leading is all wrong:

![selection_187](https://cloud.githubusercontent.com/assets/173595/14109077/0d0cfaa4-f5c9-11e5-867a-f504655fef29.png)

What value controls the leading in a situation like this? Or am I perhaps approaching this all wrong? Or is SILE tripping up on something?

**Comment by alerque** [comment]
Would this be a reasonable use of small negative penalties?

    SILE.call("penalty", { penalty=-1 })

i.e. _Please_ break here if you break anywhere?

**Comment by simoncozens** [comment]
Yes, I would use penalties here to control line breaking. You could try using `\goodbreak`, which is defined as being a penalty of -500.

As far as the `\hbox`, it's not necessarily a *bad* way to do it, although it means if you have a very long author name that won't get split at all when perhaps you might want it to. I don't know why that doesn't work. `\hbox` should set its height to the height of the highest contained box; in fact, reading the code, it does. But I wonder if you are using the `linespacing` package, and something in there is not reading the heights correctly. What linespacing mode are you using?

**Comment by alerque** [comment]
For some reason `\goodbreak` didn't work for me when I first started tinkering, which is what led me to `\hbox` and I forgot about penalties for a while. On reviewing today I tried the penalty manually and found that -1 does what I was hoping for. Anything more (e.g. -100) and it forces a break even if the line doesn't need one at all.

Yes I'm using `line-spacing` with a value of `fit-font`.

**Comment by simoncozens** [comment]
Yep, so fit-font scans the line for any hint of how big the font is, but all it sees on the line is one big ol' opaque hbox. There's no actual glyphs on the line, so the line has a font height of zero, hence what you are seeing.

Broken as designed, unfortunately.
