### ISSUE TITLE
Page break fruitcake with a side of ragged

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#301]
I've been trying to isolate an elusive problem with paragraph alignments in a long document and failing for months. I finally pinned it down to an MWE. There are two symptoms that can be reproduced here—a third that I think involves insertion splitting is still too jello-y to even describe.

``` TeX
\begin[papersize=a7,class=book]{document}
\script[src=packages/linespacing]
\set[parameter=linespacing.method,value=fit-font]
\set[parameter=linespacing.fit-font.extra-space,value=1.15ex plus 0.5pt minus 0.5pt]
A line of stuff in a paragraph here that wraps one line.

\hfill The undersigned,

\hfill John Hancock

\skip[height=14em] % Change this to 13 em and the next right align gets applied to the wrapped half of the paragraph preceding it

A line of stuff in a paragraph that wraps on the page following the one it started on.

\rightalign{The undersigned,}

\rightalign{John Hancock}

\skip[height=16em]

The problem with hfills on the next page doesn't repro if you try to do it on this page.

\skip[height=15em] % Change this to 14em and the next hfill breaks

A line of stuff in a paragraph that wraps not just one but two lines on the page following the one it started on.

\hfill The undersigned,

\hfill John Hancock

\end{document}
```

Here is the expected rendering:

![selection_189](https://cloud.githubusercontent.com/assets/173595/14203497/01e8d31a-f807-11e5-9046-094581b24a99.png)

Here it is again with a slightly different document shape that triggers broken renderings.

![selection_190](https://cloud.githubusercontent.com/assets/173595/14203500/0724319e-f807-11e5-848d-0482b308264f.png)

**Comment by alerque** [comment]
Possibly related to #262?

**Comment by alerque** [comment]
This can play out in really bizarre ways. Check out this two page spread:

![selection_196](https://cloud.githubusercontent.com/assets/173595/14487396/f2f260a2-016a-11e6-859c-568d02bcbb67.png)

The content on the left is from the previous chapter and should be left justified. The chapter title, subtitle and quotation at the chapter on the right is centered. At least they are centered for all the other 94 chapters in the book. This one seems to has passed it's center alignment to the wrapped line on the previous page and adopted the left justification for itself. It also picked up the line spacing settings from the previous chapter and applied them to the chapter title which should be in an isolated settings environment—explaining why the reference is overlapping the quote there.

**Comment by alerque** [comment]
Given the similarity in when nudging things around in the test case works and doesn't work, I can't imagine this _not_ being related to #262.

**Comment by simoncozens** [comment]
The test seems to pass as of HEAD. (1d6b065) "The undersigned" stays on the right, in all three occurrences.

**Comment by alerque** [comment]
The test I put in the tests folder or the MWE above? Because the MWE was hacked to work and you have to change it to show the bug. The test I adjusted to fail, but it doesn't have an expect yet.

**Comment by simoncozens** [comment]
The test in the repo.

**Comment by alerque** [comment]
I just tested HEAD and the test is not displaying correctly for me. On page 2 the first line SHOULD NOT be right aligned and an page 4 the second line SHOULD be.

**Comment by simoncozens** [comment]
Here's what I got: 
[bug-301.pdf](https://github.com/simoncozens/sile/files/298791/bug-301.pdf)

**Comment by alerque** [comment]
That has rather different font and line metrics than my version and the breaks are coming at a different place.

**Comment by simoncozens** [comment]
Aargh, how can this be? I'm using original Gentium, version 1.03. What does your `--debug=versions` say?

**Comment by alerque** [comment]
For grins here is the output you requested, but the font version is not the problem:

```
❯❯❯ sile --debug=versions tests/bug-301.sil
This is SILE 0.9.4-unreleased
<tests/bug-301.sil>
[1] 
! Overfull content for frame folio
[2] 
! Overfull content for frame folio
[3] 
! Overfull content for frame folio
[4] 
! Overfull content for frame folio

Harfbuzz version: 1.2.7
Shapers enabled: graphite2, ot, fallback
ICU support enabled

Fonts used:
/usr/share/fonts/TTF/Gentium-R.ttf:0    Version 1.03; 2011; OFL 1.1 release
```

The reason you couldn't recreate this is because the way leading was calculated was massively different and you had a newer version of SILE (or Harfbuzz?) than I did at the time. I submitted a PR to fix the test so it's properly broken.
