### ISSUE TITLE
Return list of files used in compilation of document

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#305]
I have a number of projects that consist of large numbers of documents (in the 1000s) and a collection of supporting classes, function libraries, etc. that are used across them. These projects are of course under version control and, when pushed to a central repo, get built by a CI system that looks through all the documents, re-renders the ones that have been updated and ships the new PDFs off to a shared file server.

Each project has a Makefile which comes up with a list of sources in the project and checks whether they have been updated since the last build. Make is really good at this — provided you can supply it with a good list of dependencies for each target. For my SILE projects this is quickly becoming unwieldy. For example, given a target PDF one might assume that a like-named `.sil` file is a dependency along with the project's main lua library and some cross-project shared class or function library. Optionally if it exists, a like-named lua file could be a dependency:

``` Make
%.pdf: %.sil <project>.lua <toolkit>/class.lua $(wildcard $$*.lua)
```

But now suppose that _some_ of the `.sil` files also pull in custom bits:

``` TeX
\script[src=toolkit/specialfunction]
```

Now `toolkit/specialfunction.lua` should technically be listed as a dependency to build that PDF, but it shouldn't necessarily be listed as a dependency for _all_ the PDFs in a project, just the ones build from that particular source. Regenerating rendered PDFs is expensive.¹ Such a list could be maintained by hand, but that's a royal pain. Instead we must enter the world of auto-depenency-generation.

There are pretty [well established ways](http://make.mad-scientist.net/papers/advanced-auto-dependency-generation/) of doing this in the C/C++ world. For example one can run `gcc -MM` to generate a makefile snippet that lists all the dependencies of a source file such that make can know when to rebuild it or not. Some LaTeX compilers have similar solutions that parse documents for `\usepackage`, `\import`, etc. Others such as latexmk [parse the compilers log](http://tex.stackexchange.com/q/68277/5100) to determine what files were included and use those when checking for dependencies on the next build.² 

A quick hack would be to grep the source and look for script commands, but this would only be a band-aid as it would miss any conditional includes, nested includes from includes, etc. A true list of  dependencies can really only be achieved by parsing the source and processing all the functions. Ergo this can only be done properly by SILE itself.

I propose that:
- SILE should keep an internal table with a list of all files included while rendering a document. This would need to catch everything successfully resolved by Lua's `require()` function as well as image files, fonts specified via filename, and other resources referenced by the document. This should include the full relative path to the resource as parsed by SILE at render time, not just the module names passed around in Lua.
- Access to this table should be available from a command line flag that would write this file list to a dependency file that could  be parsed by external processes. The output should probably have an optional exclude filter for all of SILE's bundled resources such as `core/*`, `classes/*`, and `packages/*`.

This would enable a vastly simplified usage that might look like this:

``` Make
SRCS = $(wildcard *.sil)

%.pdf: %.sil
    sile $< -o $@

-include $(SRCS:.sil=.deps)

%.deps: %.sil
    sile $< --deps $@
```

The main issue here being one would have to keep the build artifacts around in order to avoid unnecessarily rebuilding PDFs in the future. Any run in a clean environment would require at least one render pass on all documents before it figured out what it didn't need to build next time.

To aleviate this overhead as well, a useful (if somewhat harder to implement) extension of this would be to:
- Introduce a dummy typesetter of some sort so that documents could be "processed" to the point that an accurate dependency table was generated but no actual output produces and the hard work of actually typesetting the content was skipped. Basically this would need to follow all of the scripting logic including recursing through all function and `process()` calls, but replacing all functions that do any typesetting work with some null function so no actual work is done except parsing out what external resources are called.

This would enable a builder to determine the dependency tree quickly and avoid having to do a full render pass in the event that it was starting "clean" (without the build artifacts from a previous run):

``` Make
%.pdf: %.sil $(shell sile --deps $$*.sil)
    sile $< -o $@
```

¹ <sub>One document stash I have takes the CI runner about 9 hours to re-generate all the PDFs and produces 1.8 Gigs of files that has to re-sync to over a dozen users. Re-rendering whatever documents were affected by a change is fine, re-rendering the whole stash just because some toolkit file was updated that only actually included half 5 documents is not okay.</sub>

² <sub>Much like LaTeX, SILE also has an issue with [circular dependencies](http://bruno.defraine.net/techtips/makefile-for-latex/), but that's slightly out of scope for this particular issue and more relevant for #230.</sub>

**Comment by simoncozens** [comment]
Well, at the moment, everything pulled in via `SILE.resolveFile` (.sil inputs and .lua packages) should appear in angle brackets on the terminal log. You can access the resolved fonts with the `--versions` command line. Then there's images.

What I would do, if i needed this, would be to write a package which wrapped `SILE.resolveFile`, `SILE.outputter.imageSize` and `SILE.shaper.debugVersions` to stash everything that it sees into a table, then dump the table out in the `debugVersions` bit.

**Comment by alerque** [comment]
Humph. I got half way through typing up this feature request all over again before the feeling of *déjà vu* led me to search open issues.
