### ISSUE TITLE
How to munge string content before processing?

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#306]
I know this is an advanced topic, but several times I've bumped into something that requires mucking around with the objects behind SILE's back and I have no idea what I'm actually doing. Perhaps a small section could be added to the documentation to point folks like me in the right direction.

The basic scenario is that I need some functions that can munge their content. Here is one example of where it would be useful:

``` TeX
\section{One line section header}

\section{Potentially two line section header: but wrapped on the colon if necessary}
```

Now lets say our section command was smart enough to wrap section headings only when necessary and insert a preferred breakpoints on any colons: 

``` Lua
-- Warning: pseudocode!
SILE.registerCommand("section", function(options, content)
   content = content.replace(": ", ":\penalty[penalty=-1] ")
   SILE.process(content)
end)*
```

Of course that's made up an the real content object isn't just a string. The question is, what would be the correct way and place to pre-process input such that a string replace could be done like this?

**Comment by simoncozens** [comment]
Have you had a look at the `inputfilter` package and `examples/inputfilter.lua`? (`chordmode.lua` is also an example of using input filtering) That might do what you want.

**Comment by alerque** [comment]
Doh. I know about both of these—in some former life before I loaded a bunch of other stuff into my FIFO brain.
