### ISSUE TITLE
How to define commands that behave differently at the start of a page vs. after other content?

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#310]
Some blockquote citation styles dictate indenting paragraphs except those following citations. This is easy enough to do in SILE except for when page breaks get involved because then suddenly I _don't_ want the indent restriction. For example ideally the paragraph on the second page here would start out indented:

```TeX
\begin[papersize=a6]{document}
\set[parameter=document.parindent,value=2em]
\define[command=quote]{\set[parameter=document.lskip,value=2em]{\noindent\process}\noindent}
\script[src=packages/lorem]

\lorem[words=70]

\quote{\lorem[words=70]}

\lorem[words=70]

\quote{\lorem[words=60]}

\lorem[words=70]
\end{document}
```
![selection_204](https://cloud.githubusercontent.com/assets/173595/14529175/f7fba530-025b-11e6-93e4-967c3f8232b2.png)

In there a way to define a `noindent` equivalent that sets the value when there is typeset output in the frame already but turns into a no-op if it happens to come at the beginning of a frame?

**Comment by simoncozens** [comment]
Call `SILE.typesetter:leaveHmode()` and count the contents of `SILE.typesetter.state.outputQueue`. If after turning the horizontal list into vboxes there aren't any vboxes on the output queue, then you're at the top of the frame.

**Comment by simoncozens** [comment]
In fact, let me do this in a package.
