### ISSUE TITLE
Is there a way to detect the context of a command from a nested one?

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#312]
Lets say I  have something like this:

```TeX
\begin[papersize=a6]{document}
\define[command=em]{\font[style=Italic]{\process}}
\define[command=em2]{\font[weight=800]{\process}}
\define[command=blk]{\font[style=Italic,size=0.8em]{\process}}

This is a normal paragraph with an \em{emphasised bit} in the middle. Here italics is the right form of emphasis.

\begin{blk}
This is a block quote paragraph with an \em{emphasised bit} in the middle. Lets say it’s already in italics or in a font that does not have italics. So we need some other treatment. 
\end{blk}
\end{document}
```

The issue here the source text is coming from Markdown where there is only one kind of emphasis markup and the transformation to SILE knows little about the context.

What I really need is to be able to use the `\em` command throughout the document but have it behave slightly different depending on context. Ala cascading style sheets. Is there a way I can define the command such that it can pick up on the typsetter's context and switch depending on whether it was in or out of the block quote? Should I be setting scratch variables on begin/end and testing for those or is there a better way conceptually?

**Comment by simoncozens** [comment]
The easiest way would be to override `SILE.process` so that it maintains a context stack, and then query that.
