### ISSUE TITLE
Infinite loop when content does not fit running header

### ISSUE THREAD

**Issue by strepon** [simoncozens/sile#34]
At first, I'd like to say that SILE seems to be a tool which I wished to have for years:)) Something like TeX, but more flexible (frames!) and friendly (e.g. in Unicode and font support) is much appreciated and many thanks for that! I'll try to report what I'll find during my testing...

An infinite loop occurs when height of content of running header is greater than the header height. This code evaluates correctly:
```
\begin[papersize=a4, class=book]{document}
\script[src=packages/frametricks]
\right-running-head{First Line of Header \break \skip[height=12mm] Second Line of Header}
\showframe[id=all]

First page text
\break \skip[height=22cm]
Second page text

\end{document}
```
If you change the space in running header to `\skip[height=13mm]`, execution ends up in infinite loop.
(Tested in SILE 0.9.1, Ubuntu 14.04.)

**Comment by simoncozens** [comment]
Wow, good catch. I will investigate this tomorrow.

**Comment by simoncozens** [comment]
I now understand the bug. The problem is happening because the content overflows the running header's frame, which causes an end-of-page event. The book class's end-of-page handler is called, which tries to write out the running headers, which overflows and causes an end-of-page event...

But I don't know what the correct behaviour should be. Obviously an overfull header should not go through the main end-of-page handler, and it shouldn't cause an infinite loop at any cost; but I don't know if the overflowing content should be suppressed, or moved somewhere else, (Where?) or if we should give an error and give up.

**Comment by strepon** [comment]
I think all of the suggested solutions would work. However, from user's point of view, I would prefer a warning that does not abort document processing (approach like overfull warnings in TeX). The overflowing content can be suppressed or maybe can continue regardless of frame boundary if possible (or maybe an option for this? - like CSS property overflow visible vs. hidden).

By the way: your fast responses and bug fixes are really impressive, like a professional support:)) Thanks a lot!

**Comment by strepon** [comment]
The fix seems not to work for me. The example above (even if I keep the original length 12 mm which was OK) results in
```
<simple-test.sil>
! Couldn't get frame ID nil at simple-test
stack traceback:
        /usr/local/share/sile/core/utilities.lua:16: in function 'error'
        /usr/local/share/sile/core/frame.lua:173: in function 'getFrame'
        /usr/local/share/sile/core/frame.lua:128: in function 'isMainContentFrame'
        /usr/local/share/sile/core/typesetter.lua:248: in function 'initNextFrame'
        /usr/local/share/sile/core/typesetter.lua:312: in function 'leaveHmode'
        /usr/local/share/sile/core/typesetter.lua:421: in function 'typesetNaturally'
        /usr/local/share/sile/classes/book.lua:39: in function 'endPage'
        /usr/local/share/sile/core/typesetter.lua:252: in function 'initNextFrame'
        /usr/local/share/sile/core/typesetter.lua:312: in function 'leaveHmode'
        /usr/local/share/sile/core/typesetter.lua:102: in function 'typeset'
        /usr/local/share/sile/core/inputs-common.lua:25: in function 'process'
        /usr/local/share/sile/core/inputs-texlike.lua:98: in function 'process'
        /usr/local/share/sile/core/sile.lua:158: in function 'readFile'
        /usr/local/bin/sile:26: in main chunk
        [C]: in ?
```
