### ISSUE TITLE
Orphan penalty cannot be set by \set command

### ISSUE THREAD

**Issue by strepon** [simoncozens/sile#35]
SILE manual says (beginning of chapter 7) that orphan penalty can be set by
```
\set[parameter=typesetter.orphanpenalty, value=250]
```
However, this leads to an error:
```
! Setting typesetter.orphanpenalty must be of type integer, not string 250
```
(Tested in SILE 0.9.1, Ubuntu 14.04.)

**Comment by simoncozens** [comment]
Thanks for the report! This has actually been fixed in the repository, in commit 0e2826abb82c2d486970c2dcccbca198e4c04b00 and will be available in the next release.
