### ISSUE TITLE
Drop space stretchability inside ragged environments

### ISSUE THREAD

**Issue by simoncozens** [simoncozens/sile#352]
Another, hopefully better, way of solving #300, qv.

**Comment by alerque** [comment]
Here is an example of why this is a problem. On the right is SILE's stock behavior. in this title page scenario the default spacing is horrific. On the left I've replaced the ragged function with one that does not reset the value of spaceskip (as per what I wanted to do in #300). This may not be the right long term fix but you can see why it produces the expected rendering while the current behavior seems broken:

![selection_013](https://cloud.githubusercontent.com/assets/173595/19413393/4a0fcfe0-9334-11e6-9177-d3325e2d52ca.png)

**Comment by alerque** [comment]
Hm. That _helps_ the final metrics a little but it doesn't bring the output into the realm of sane. I can't put my finger on why yet, but expect me to re-open this or a similar issue when I can.
