### ISSUE TITLE
Need way to set PDF background color

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#353]
For print work the hard coded default of a white / clear background is fine, but there are situations where being able to set the page color from SILE would be useful. The ink color can be set pretty universally at the outset:

```Lua
local color = SILE.colorparser("#5a4129")
SILE.outputter:setColor(color)
```
A way to also set the page background would be nice. In my case applying to all pages would be preferred, but a current-page-only function might be useful other scenarios.

**Comment by simoncozens** [comment]
I'm not sure PDF has the concept of a background colour. So the first thing you do on a page is draw a big filled box of the appropriate colour, the full size of the page. That should give you enough information to implement what you want... :-)
