### ISSUE TITLE
silewin32.h missing from the release file

### ISSUE THREAD

**Issue by olivierberten** [simoncozens/sile#364]
... which prevents it to build...

By the way, it would be great if you could build the release tar files with gnutar instead of osx tar. See: http://lee.greens.io/blog/2014/05/06/fix-tar-errors-on-os-x/

**Comment by simoncozens** [comment]
Oh, bother. And bother again. OK, I have replaced the release file. Which I know is a terrible thing to do, but it will only make things better.
