### ISSUE TITLE
Will the real reference please stand up?

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#371]
I'm having trouble getting SILE to do math a 5 year old can handle. Specifically I want to note the beginning and end range of verse [starts] on a given page in the header. 

The concept I started with is simple enough: I'm keeping two registers per page. One for the first verse start seen and one for the last. In `endPage()` I'm throwing that info into the header.  Something like this:

![selection_252](https://cloud.githubusercontent.com/assets/173595/19079625/edb8b8d6-8a5c-11e6-83ab-aae8c522daa5.png)

As you can see that looks like it worked until you actually check the numbers, then it becomes apparent that insertions from the previous page and other pushBack material moves everything around and nothing actually starts or ends where my counters do.

What's the correct concept to go for here?

**Comment by DavidLRowe** [comment]
This observation may not be relevant, but it seems that the start and 
end verse numbers that appear in the headers are for the first verse 
number in the first full paragraph on the page and the last verse number 
in the last paragraph that starts on the page. I wonder if the counters 
are tagging the correct locations.

**Comment by alerque** [comment]
Interesting observation @DavidLRowe. I suspect that isn't entirely coincidence and the logic is that it coincides with when the page builder is getting triggered. The basic issue here is that my verse counter is being called when the verse marker  is created which gets processed a paragraph at a time (while the typesetter is in horizontal mode). When it leaves horizontal mode and looks for page breaks some of the content it already processed can get pushed back to the next page. Hence my counters are being set when the content is processed but there is no guarantee that said content actually ended up on the page being processed in `endPage()` (or that other content from previous pages hasn't been stuffed in the top).

I believe some sort of callback is going to be needed—perhaps tampering with `outputYourself()` for the verse markers—but I'm not really sure where to start.

**Comment by alerque** [comment]
I had a quick look at this, at this point it looks like I would have to search the node tree to find what markers had been output. My current thought is to implement some sort of callback in parallel to the `outputYourself()` routine that gets called when the pagebuilder is done (as in after all shaping is done but before `endPage()` is run) that could be used to keep track of stuff like this. Thoughts anybody?

**Comment by simoncozens** [comment]
You know `bible.lua` has code which does this, yes?

**Comment by simoncozens** [comment]
Sorry, I mean `chapterverse`

**Comment by alerque** [comment]
No. I did not. Looking into it now.

**Comment by alerque** [comment]
I'm kind of puzzled about this because I literally dropped those functions tit-for-tat in the same places I was running my own code doing seemingly the same thing, but one works and one doesn't. I'll pick it apart in more detail to see what conceptually is really different, but I'm guessing my variable scoping was off. In any case this doesn't need attention, at least not for the reasons opened the issue.
