### ISSUE TITLE
error in configure 

### ISSUE THREAD

**Issue by texrg** [simoncozens/sile#376]
in fedora  change to
dnf install .... libtool ....

10 page "the paper size, an optional argument may be added to the docmument declaration:"
document

**Comment by alerque** [comment]
I'm sorry but I'm not sure I follow what either of these two points were about. Is there something that needs to be explained for installation on Fedora? Is there a mistake in the documentation?

**Comment by texrg** [comment]
mistake in documentation.
in my opinion (linux install section) add libtool

on 10 page is type mistake.

**Comment by alerque** [comment]
I see at least the second bit now, so we'll correct that. Libtool should be part of whatever dev-tools package you normally need to build any packages for your system, so normally that wouldn't be explicitly listed as dependencies, but I'll review that part too. At some point I'll also roll a Fedora package too...

**Comment by texrg** [comment]
not, i must instal libtool on fedora

**Comment by alerque** [comment]
@texrg Had you previously build any other software or generated RPM's on this system before?

I did answer your email about 12 hours ago, but you should know that I am very busy with projects right now and won't be able to help extensively. You should be writing the users mailing list so that whoever is available and interested could chip in.

**Comment by texrg** [comment]
Yes, I create one small package in fedora. But this is very very complicated... and You must lot of time to editing /checking/replacing package. When You publish this is easyly, but first is very hard.
I'm not a sponsor. I'm not help You in packaging.

[I'm digging Your email from spam ;( ]

**Comment by alerque** [comment]
@texrg I wasn't asking you to package this, I was just trying to figure out why your system did not have that package so I could best fix the documentation. That being said this is an open source project — not a commercial endeavor — and I myself am just a volunteer helping out where I can.

Thanks for reporting the documentation issues. They are fixed now.
