### ISSUE TITLE
How convert word?

### ISSUE THREAD

**Issue by xor256** [simoncozens/sile#377]
I have trouble with my font. Is posible to read every words or every paragraph, convert it and return back to system?

for example triger for word.

function my_triger(s)
   return string.upper(s);
end

or only for first char in word

**Comment by simoncozens** [comment]
I'm not really sure what you're trying to do, but maybe the `inputfilter` package might help you. Look at `examples/inputfilters.sil` and the inputfilter section of the manual.

**Comment by mikolaj24** [comment]
@simoncozens  this inputfilters working?
i type:
./sile examples/inputfilters.sil and nothing happened. in example pdf not exist too.

This idea working with hyphenation too?

**Comment by alerque** [comment]
@mikolaj24 I don't see anything very  special about that particular example as far as system requirements go. It's also known to work in the test suite and across several systems.

What do you mean by "nothing happened"? Did you get any output at all? Does it output the version number and input file name to the console like it does for other runs? Does it show that it built page 1? Are you in your system examples folder where the user doesn't have write permissions? Can you build any Sile documents at all? Other examples?

**Comment by xor256** [comment]
You thing the arabic glyph i need changing in inputfilter? 
in my language similar in arabic each char is in 3 variants. first in word, inside nad last.

**Comment by simoncozens** [comment]
Arabic shaping will work automatically if you tell SILE that you are dealing with a right-to-left page. See `examples/arabic.sil`.

**Comment by alerque** [comment]
@xor256 You guys are working on the wrong end of the problem. You don't inputfilter for this. In fact you don't need Sile to understand the contextual forms of your glyphs at all. About all you need it to know is how to split your text into words. After that is passes the words off to Harfbuzz for shaping, and Harfbuzz uses the information in the font about contextual forms of glyphs to convert the series of letters into a series of glyphs with specific shapes.

**Comment by xor256** [comment]
@simoncozens my font is from left to right but all chars is in more than one version ;-)
Please open Your maind , look at other way http://omniglot.com/conscripts/fictional.htm

@alerque the trouble is "_and Harfbuzz uses the information in the font about contextual forms of glyphs to convert the series of letters into a series of glyphs with specific shapes._" 
My font have very few (little) characters but many ligatures. Look ant hangul. I have this same but my ligatures are millions. This is trouble.

Anybody can tell me how read utf-8 char and changing it? in this example inputfilter where put my code
for example I have table:
ai => ła
kai => zx
ka => zo
kaj => zl
ma => mo
etc

**Comment by alerque** [comment]
@xor256 What I said still stands. It doesn't matter if you have five ligatures or ten million. The software that handles them is still the same, and in this case it isn't SILE. Harfbuzz is responsible for identifying character sequences and returning them as a ligature glyph. It is also responsible for identifying contextual variants. The font tells it how to do this for your script.

You should not be manipulating your input text, you should be fixing your font.

**Comment by xor256** [comment]
Sometimes isnt possible create a font
