### ISSUE TITLE
Package for Ubuntu/Debian

### ISSUE THREAD

**Issue by PanderMusubi** [simoncozens/sile#38]
Please create a package for Debian/Ubuntu. See also https://bugs.launchpad.net/ubuntu/+bug/1413942 for distribution via Ubuntu.

**Comment by simoncozens** [comment]
I'd love to see this happen, but I tend to think this kind of distribution work that is best done by... well, the distributions. People working downstream within the distributions understand the relevant policies, dependency systems, packaging requirements and so on, and have the ability to get the packages into the distributions. As an upstream maintainer, I'm happy to be blissfully aware of all these details. :-)

Thank you for opening an Ubuntu bug for this; it isn't a SILE bug.

**Comment by PanderMusubi** [comment]
OK. Some projects have packagers in their midst or want to keep an eye on the package process and use such an issue for downstream requests for packaging. Hopefully it will be picked up by a packager. You could send out a request on FOSDEM. :wink: I will be attending your talk so see you there.

**Comment by simoncozens** [comment]
Now that I think about it, the thing which is going to complicate the packaging process is the libtexpdf library. The best thing way to package SILE would be to have libtexpdf split it out to its own package; but ideally dvipdfmx should also be using this library.

I have been trying to keep the dvipdfmx maintainers in the loop with what I have been doing, but a solution which works for both of us will need more work to make dvipdfmx use libtexpdf again. libtexpdf cut out some of the TeX-specific parts of the code (e.g. resolving paths using kpathsea) so these need to be moved back into dvipdfmx in the right places. I have done some work on this but it's not finished. So I would like to see that fixed before someone tries to package this.

See you next week!

**Comment by PanderMusubi** [comment]
To add to your documentation for installing from git on Ubuntu 14.10:

    $ sudo apt-get install lua5.1 liblua5.1-0-dev lua-lpeg lua-expat lua-lgi libfreetype6 libfontconfig1 fontconfig-config libharfbuzz0b libcairo2 libpangocairo libpango1.0 libpango1.0-dev build-essential automake autoconf libtool make
    $ ./bootstrap.sh
    $ ./configure
    $ make
    $ sudo make install
    $ sudo ldconfig

However, when I run the test I get:

    $ sile examples/test.sil 
    This is SILE 0.9.1
    <examples/test.sil><examples/macros.sil>/usr/bin/lua: /usr/local/share/sile/packages/insertions.lua:142: attempt to compare table with number
    stack traceback:
    	/usr/local/share/sile/packages/insertions.lua:142: in function 'insert'
    	/usr/local/share/sile/packages/footnotes.lua:24: in function '?'
    	/usr/local/share/sile/core/inputs-common.lua:27: in function 'process'
    	/usr/local/share/sile/core/inputs-texlike.lua:98: in function 'process'
    	/usr/local/share/sile/core/sile.lua:158: in function 'readFile'
    	/usr/local/bin/sile:26: in main chunk
    	[C]: ?

How do I fix this?

**Comment by PanderMusubi** [comment]
The above error was with lua 5.1. With lua 5.2, I get this error:

    $ sile examples/test.sil 
    This is SILE 0.9.1
    <examples/test.sil><examples/macros.sil>
    ! Overfull content for frame content
    
    ...
    
    ! Overfull content for frame content
    ^C/usr/bin/lua: core/utilities.lua:31: interrupted!
    stack traceback:
    	/usr/local/share/sile/lua-libraries/std/string.lua:172: in function </usr/local/share/sile/lua-libraries/std/string.lua:168>
    	(...tail calls...)
    	core/utilities.lua:31: in function <core/utilities.lua:30>
    	(...tail calls...)
    	core/harfbuzz-shaper.lua:66: in function 'shape'
    	core/hyphenator-liang.lua:93: in function 'hyphenate'
    	core/break.lua:409: in function 'doBreak'
    	core/typesetter.lua:154: in function 'boxUpNodes'
    	core/typesetter.lua:305: in function 'leaveHmode'
    	core/typesetter.lua:102: in function 'typeset'
    	core/inputs-common.lua:25: in function 'process'
    	core/inputs-texlike.lua:98: in function 'process'
    	core/sile.lua:158: in function 'readFile'
    	/usr/local/bin/sile:26: in main chunk
    	[C]: in ?

**Comment by simoncozens** [comment]
I will look into the lua 5.1 issue; for lua 5.2, I fixed the bug you're seeing last night, so a git pull should clear it.

**Comment by PanderMusubi** [comment]
Confirmed that it is fixed for 5.2. Thanks.
