### ISSUE TITLE
Parfillskip is not zero in book header

### ISSUE THREAD

**Issue by strepon** [simoncozens/sile#39]
I'm not sure if this is a bug, but the behaviour is a bit unexpected:
```
\begin[papersize=a5, class=book]{document}
\script[src=packages/frametricks]
\right-running-head{Line begin \hfill Line end}
\showframe[id=all]
Page one
\skip[height=15cm]
Page two
\end{document}
```
In output, the "Line end" text is not right-aligned. As typesetter log says, that is because glue 0pt plus 10000pt (value of ```typesetter.parfillskip```) is added after the text. It shouldn't happen and parfillskip should be zero - as it is actually defined in ```book.lua```:
```
SILE.settings.set("typesetter.parfillskip", SILE.nodefactory.zeroGlue)
```

**Comment by simoncozens** [comment]
Good catch! This was caused by the settings closure stuff in bug #30. While trying to maintain the correct font size/family/etc. for the running heads, we save away all the settings, including, of course, `typesetter.parfillskip`.

**Comment by simoncozens** [comment]
That explanation was clever, but wrong. It seems that more to the point, the paragraph needs to be explicitly ended (which adds parskip glue) /while/ parskip glue is zero. So adding a couple of calls to `\par` within the running head code fixes it. Thanks again for the bug report!
