### ISSUE TITLE
SILE cannot read from a named pipe

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#414]
For some reason the  Lua file handler is refusing to process input from a named pipe. This is really quite a useful thing to be able to do and we should probable make whatever adjustments need to be made to allow this. (Note would also allow a document to be passed in on `/dev/stdin` which is also a named pipe.)

Example to pre-process an file with a macro engine.

    sile -o out.pdf <(m4 source.sil)

This throws:

> ! /dev/fd/63 isn't a file, it's a named pipe! at /dev/fd/63

**Comment by alerque** [comment]
@rjmunro since you expressed a flicker of interest in this I would be curious if you had any input on my PR #441 and whether that covers your use cases and expected behavior or not.

**Comment by rjmunro** [comment]
I'm vaguely interested in sile, but don't have any actual use for it at the moment. I've moved further away from any design / publishing stuff in my recent work.

**Comment by alerque** [comment]
@rjmunro Fair enough, thanks for the feedback.
