### ISSUE TITLE
Add SILE versus Scribus paragraph to documentation

### ISSUE THREAD

**Issue by PanderMusubi** [simoncozens/sile#43]
Please, add a SILE versus Scribus paragraph to the documentation.

**Comment by simoncozens** [comment]
I don't know Scribus. If you do, please feel to write me a paragraph about it... :-)

**Comment by PanderMusubi** [comment]
For paragraph 1.3:

The other tool that people reach for when designing printed material on a computer is InDesign.

->

The other tool that people reach for when designing printed material on a computer is InDesign or similar DTP software such as Scribus.
