### ISSUE TITLE
Running SILE on windows 7?

### ISSUE THREAD

**Issue by elirecords** [simoncozens/sile#433]
Hi - I've downloaded SILE but try as I might, I can't work out how to run it (on windows 7). Please can you advise?

**Comment by simoncozens** [comment]
Tagging issues #410 and #82. I've just signed up for AppVeyor and am trying to create reproducible Windows builds using that. Stay tuned!

**Comment by alerque** [comment]
Thanks for the issue report @elirecords. A lot of work has been done on this and I _think_ there is a Windows installer that roughly works now. Progress on this is tracked in another issue though with extensive comments, so I think I'll close this as a duplicate. We'd love to hear your feedback on the experience on Windows as we get the kinks worked out.
