### ISSUE TITLE
New to Sile...issue with fonts

### ISSUE THREAD

**Issue by clintolsen** [simoncozens/sile#452]
Hi:

I'm grateful that someone else on a Mac put forth the effort to point out the Gentium problem. I installed that.

However, not being a fan of Gentium, I want to use a different font. The examples seem to show snippets of how to switch fonts, but if you want them to be the default for an entire document, I just didn't "get it."

I went to experiment with something like:

<pre>
$ cat hello.sil 
\begin{document}
\font[family=Times,size=10pt] 
Hello SILE!
\end{document}
</pre>

Sile processes this document, but I'm left with a file that just has rectangles where the glyphs for the fonts should be.

<img width="225" alt="hello_bad" src="https://cloud.githubusercontent.com/assets/4228550/23592000/175766e6-01af-11e7-9965-f91e9d7238c9.png">

The rectangles are beautiful :)

I'm sure I'm doing something trivially wrong.

At any rate, I'm excited to learn more about Sile. I've used various TeX systems and Lout over the years.

Thanks,

-Clint

**Comment by simoncozens** [comment]
OK, that's... odd. At the moment I can't tell if it's a font issue or a shaper issue or something in the middle.

Could you do me a favour and run with `sile --debug=versions,fonts`? Could you also run `./sile-e 'require("core/debug-output")' hello.sil` and paste the output?

**Comment by simoncozens** [comment]
Actually, don't worry. It does the same for me. I'll try and work out why.

**Comment by simoncozens** [comment]
OK, so it's because Times on the Mac is a dfont rather than an OpenType font, and harfbuzz doesn't yet support dfonts. Link: https://github.com/behdad/harfbuzz/issues/128

**Comment by khaledhosny** [comment]
One way around this is to load your fonts with Core Text on mac and use `hb_face_create_for_tables()`. This way you don’t even need the hackery in macfonts.m to get the font url, you can just read the table data from CTFont.

**Comment by khaledhosny** [comment]
Here is a [not-so-pretty code](https://gerrit.libreoffice.org/gitweb?p=core.git;a=blob;f=vcl/source/gdi/CommonSalLayout.cxx;h=c61fea0625d2edff2cb89134202a297339d51fd3;hb=HEAD#l41) from LibreOffice that does something similar, for inspiration.

**Comment by ClintO** [comment]
And what's the proper method of using a font with a space in it? For example, Century Schoolbook is two words obviously. I'm not sure what the `family=` syntax should be. I tried with and without double quotes and got a font loading error.

**Comment by simoncozens** [comment]
Oh boy - you are not having much luck! Sorry about this...

Your syntax looks OK, and "Font loading error" means that SILE could find the font OK but when it was passed to the PDF engine something went wrong. Could you do `--debug=fonts,versions` this time?

**Comment by clintolsen** [comment]
It's OK. I'm a professional when it comes to finding problems :) I think they modeled Sam Neill's character from Jurassic Park after me.

<pre>This is SILE 0.9.4
<hello.sil>
[fonts]	Looking for Century Schoolbook;10;400;;normal;;LTR
[fonts]	Resolved font family Century Schoolbook -> /Library/Fonts/Microsoft/Century Schoolbook

! Font loading error for {bidilevel=0,direction=LTR,family=Century Schoolbook,features=,hyphenchar=-,language=en,script=,size=10,style=,variant=normal,weight=400} at hello l.18, col.35
</pre>

**Comment by simoncozens** [comment]
Yeah, that's another crazy font type - an old-style Mac PostScript font with all the data in the resource fork. I'm not even going to try supporting that, sorry, and new installs of OS X have got rid of those fonts because of the ancient format; OpenType is the way forward.

You could convert it to a dfont, but (as above) that won't help you with SILE. You may have an OpenType version of Century Schoolbook in `/Library/Application Support/Apple/Fonts/iWork/CenturySchoolbook.ttc`. I would personally delete the PostScript version and use FontBook to install the OpenType version, but there you go.

Or you could try yet another different font and see what error you expose this time. :-)

**Comment by clintolsen** [comment]
I did find the fonts you mentioned under the iWork directory. Font book did complain about 4 minor issues with that copy of Century Schoolbook, but I did use it and disabled/removed the other.

**Comment by simoncozens** [comment]
And did it work?

**Comment by clintolsen** [comment]
Oh, sorry. Yes, it did seem to work fine.

**Comment by clintolsen** [comment]
Thanks for all your help! I look forward to learning more about Sile!

**Comment by alerque** [comment]
It looks like we could use an error message that actually points out what went wrong. I wouldn't have known what this was about either. The warning message should note that the font was found but is a type that cannot be loaded.
