### ISSUE TITLE
font features +xyz=2 results in wrong value

### ISSUE THREAD

**Issue by mhosken** [simoncozens/sile#459]
In src/justenoughharfbuzz.c in scan_feature_string there is this code:

````
    if (*cp1 == '+') {
      int param = 0;
      tag = read_tag_with_param(cp1 + 1, &param);
      features = realloc(features, (nFeatures + 1) * sizeof(hb_feature_t));
      features[nFeatures].tag = tag;
      features[nFeatures].start = 0;
      features[nFeatures].end = (unsigned int) -1;
      if (param >= 0)
        param++;
      features[nFeatures].value = param;
````

This adds one to all feature values if the form +feat=num is used. I think all that is needed is that the test become `if (param == 0)`.

**Comment by simoncozens** [comment]
Could you check whether this bug also affects XeTeX? The routine is borrowed from `XeTeX_ext.c`, so any fix should also be fed back there.

**Comment by DavidLRowe** [comment]
xetex has similar problem. Rename xtest.tex.txt to xtest.tex and run xetex xtest.tex to produce xtest.pdf (using Engs feature of Charis SIL).

[xtest.pdf](https://github.com/simoncozens/sile/files/911229/xtest.pdf)
[xtest.tex.txt](https://github.com/simoncozens/sile/files/911242/xtest.tex.txt)

**Comment by simoncozens** [comment]
Darn it. OK, I'll fix in SILE and let the XeTeX list know.

**Comment by simoncozens** [comment]
Oh, it looks like it's a deliberate design decision in XeTeX, albeit forced by backward compatibility:

```
                // for backward compatibility with pre-0.9999 where feature
                // indices started from 0
                if (param >= 0)
                    param++;
```
