### ISSUE TITLE
properly handle SVGs generated by SVGMath

### ISSUE THREAD

**Issue by akavel** [simoncozens/sile#468]
For #220, it would be nice if SVGs generated by SVGMath rendered correctly in SILE.

Sample such SVG, which didn't work for me: https://github.com/akavel/svgmath/blob/master/testdata/test13.out.svg

I tried a doc like below, with current codebase (7f677a1):
```
\begin{document}
\script[src=packages/svg]

\begin{script}
  local svg = require 'svg'

  local inp = assert(io.open('test13.svg'))
  local data = inp:read '*all'
  inp:close()

  local f = assert(io.opend('foo.tmp', 'w'))
  local fig, w, h = svg.svg_to_ps(data, 72)
  f:write(w, ' ', h, ' ', fig, ' ', data)   -- why doesn't '\n' work here?
  f:close()
\end{script}

Hello SILE! \include-svg-file[src=test13.svg] Included.

\end{document}
```

Initially, `foo.tmp` contained `0 0 [...]`, but after looking into nanosvg.h I noticed it doesn't accept XML namespaces. After `sed -i 's/svg://g' test13.svg` there was some more interesting stuff in `foo.tmp`, but still no image in the generated PDF.

Is it because the SVG seems to use mostly `<svg:text>` elements? Maybe nanosvg ignores them?

**Comment by akavel** [comment]
(continuing [discussion from #220](https://github.com/simoncozens/sile/issues/220#issuecomment-299346031))

Looking at [a list of elements described in SVG 1.1 spec](https://www.w3.org/TR/SVG/eltindex.html) vs. [what nanosvg](https://github.com/simoncozens/sile/blob/7f677a116732ad65beb58406034012c6cc85f8b4/src/nanosvg.h#L2583-L2626) supports, there seem indeed to be some seemingly non-stupid missing entries, e.g.: clipPath, marker, mask, ...

**Comment by alerque** [comment]
I don't think nanosvg is going to serve SILE very well. As mentioned in #446 the support is just too rudimentary for even fairly basic use cases importing a figure.

**Comment by akavel** [comment]
Ok, got some code which does the [parsing of svgmath-generated SVGs in pure Lua](https://github.com/akavel/silemath), and managed to get prototype rendering done in ZeroBrane Studio with love2d:

![](https://user-images.githubusercontent.com/273837/34343387-e0d91504-e9cc-11e7-8635-09efd1e72847.png)

(compare with third-party rendering of the SVG at: https://github.com/akavel/svgmath/blob/master/testdata/test13.out.svg)

Not all elements supported yet, but matrices, glyphs and simple lines seem to work ok now.

So, now mostly waiting till someone provides me with a Windows binary of SILE so that I can try:

1. moving/implementing the svg rendering  (just enough for svgmath) there,
2. integrating the whole pipeline in SILE.

Though I may have somewhat less time for that over the next 2 weeks.

**Comment by simoncozens** [comment]
Very interesting! I think long term we are going to want to render SVG to PDF drawing operators ourselves, or use a better library which does that, to keep things in vector format. Doing it ourselves means we can keep the text pipeline going through SILE and leverage the existing fonts/rendering support.

**Comment by akavel** [comment]
When rendering an equation, how can I output some unicode glyph *g* at some position *dx, dy* relative to "current cursor" in the PDF from Lua? I understand that

    pdf.add_content('q')

etc. is expected to let me draw curves, but I also need to render some glyphs. I tried using `pdf.setstring()` but I'm confused as to what can I put in the `font` argument? I tried some random hacks hoping to make it work:

```tex
\begin{document}
Sample inital text

\begin{script}

local pdf = require 'justenoughlibtexpdf'

local buf = 'A'
local font = SILE.font.cache(SILE.font.loadDefaults{}, SILE.shaper.getFace)
local f = pdf.loadfont(font)
if f< 0 then SU.error("Font loading error for "..options) end
font = f
pdf.setstring(100, 100, buf, string.len(buf), font, 0)

\end{script}

Sample final text

\end{document}
```

 but got some assertion fail in `dpxutil.c`:

```
This is SILE 0.9.5-unreleased
<../silemath/sample.sil>
[fonts] Looking for Gentium Plus;10;400;;normal;;LTR
[fonts] Resolved font family Gentium Plus -> C:/Windows/Fonts/GentiumPlus-R.ttf
Assertion failed!

Program: C:\dnload\lua-etc\ZeroBraneStudio\bin\lua.exe
File: dpxutil.c, Line 299

Expression: ht && key

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
```

Not sure what else I can try...

**Comment by akavel** [comment]
Ok, got some kind of even more slightly misaligned result by virtue of some unholy abomination of code - but hey, it worked! :D 😄 😂 will need a hell of a cleanup :) and integration work, obviously, for now it's just a one-off prototype of the final element of the pipeline. I cannot upload the code yet as I'm in travel, but here's a teaser screenshot:

![](https://i.imgur.com/Oqgiyut.jpg)

**Comment by akavel** [comment]
Ok, to reduce the bus factor a bit, the code of the prototype is now at: https://github.com/akavel/silemath/blob/master/sample.sil. 

- I'd be especially interested to learn if the [renderGlyph function](https://github.com/akavel/silemath/blob/872f3950c58d4f02564103d0b3fd780feecff024/sample.sil#L28-L45) can be simplified in some way.
- Also, the `<text>` nodes in SVGs generated by svgmath have `text-anchor="middle"`, so their horizontal position should be tweaked, but I couldn't yet find out how to do that properly (moving them by `-shape[1].width/2`  didn't work for me for now, it broke things more than fixed).

**Comment by akavel** [comment]
Ok, given that I have this sub-problem resolved in principle now, I'm closing this sub-issue and will get back to reporting/discussing in the main #220 issue.
