### ISSUE TITLE
Couldn't find face Gentium at hello

### ISSUE THREAD

**Issue by kstenerud** [simoncozens/sile#469]
```
$ brew cask install font-gentium-plus
==> Tapping caskroom/cask
Cloning into '/usr/local/Homebrew/Library/Taps/caskroom/homebrew-cask'...
remote: Counting objects: 3726, done.
remote: Compressing objects: 100% (3702/3702), done.
remote: Total 3726 (delta 39), reused 600 (delta 20), pack-reused 0
Receiving objects: 100% (3726/3726), 1.26 MiB | 1.90 MiB/s, done.
Resolving deltas: 100% (39/39), done.
Tapped 0 formulae (3,735 files, 3.9MB)
==> Creating Caskroom at /usr/local/Caskroom
==> Downloading http://software.sil.org/downloads/r/gentium/GentiumPlus-5.000.zip
######################################################################## 100.0%
==> Verifying checksum for Cask font-gentium-plus
==> Installing Cask font-gentium-plus
==> Moving Font 'GentiumPlus-I.ttf' to '/Users/karl/Library/Fonts/GentiumPlus-I.ttf'.
==> Moving Font 'GentiumPlus-R.ttf' to '/Users/karl/Library/Fonts/GentiumPlus-R.ttf'.
🍺  font-gentium-plus was successfully installed!
```

```
$ sile hello
This is SILE 0.9.4
<hello.sil>

! Couldn't find face Gentium at hello
```

**Comment by alerque** [comment]
SIL International (no relation to SILE the typesetter) which developed and distributes that font has recently re-arranged everything on their websites including download locations for resources. I suspect the homebrew-fonts need some updates for all SIL related fonts. That's something I can look into and probably fix, but it isn't diretly a SILE issue.

**Comment by alerque** [comment]
I submitted an update to the homebrew casks (https://github.com/caskroom/homebrew-fonts/pull/1133) because it needed doing anyway, but that wasn't actually your problem.

See also #467 and #369.

**Comment by simoncozens** [comment]
Yes, this is #369. In the repository we have moved to Gentium Plus as the default, but obviously we can't retroactively fix released versions. Try setting a font explicitly.

**Comment by kstenerud** [comment]
OK, I think this can be closed then
