### ISSUE TITLE
Unexpected float behaviour

### ISSUE THREAD

**Issue by ralsina** [simoncozens/sile#478]
I am experimenting how to typeset bullet lists and one of the experiments produced a weird result

```
\begin[class=book]{document}
\script[src=packages/frametricks]

\float{•} item 1

\float{•} item 2

\end{document}
```

This ends placing everything in the same line :-)

![image](https://user-images.githubusercontent.com/1579/27840928-7f796ce6-60d3-11e7-831a-178f578810a4.png)

**Comment by simoncozens** [comment]
Yeah. I wouldn't currently recommend using \float for anything. It's a horrible experimental hack that didn't really work. :(

**Comment by ralsina** [comment]
Ack

**Comment by atlaskerr** [comment]
@simoncozens could you point me in the right direction on how a bullet list can be implemented in sile?

**Comment by simoncozens** [comment]
Have a look at this thread: https://groups.google.com/forum/#!msg/sile-users/snHalhGCeD0/87xqZQsoBgAJ

**Comment by alerque** [comment]
@atlaskerr You might also review the [package I'm currently using for lists](https://github.com/alerque/casile/blob/master/lists.lua). It handles multiple levels of indent (nested lists) list items can be bulleted or numbered using a counter.
