### ISSUE TITLE
EOL bug

### ISSUE THREAD

**Issue by mnjames** [simoncozens/sile#481]
*nix systems use the U+000A end-of-line (EOL) marker (LF). Mac systems use the U+000D marker (CR). Windows, bless it's heart, uses both CR+LF.

.sil documents saved with either CR or LF EOL markers and then compiled into pdf documents work fine. However, .sil files saved on Windows machines using CR+LF create pdfs with squares in every position there was an EOL in the original file. I'm guessing one of the EOL markers is being read as such, and the other is being sent to the typesetter as a character.

[simple.pdf](https://github.com/simoncozens/sile/files/1214398/simple.pdf)

**Comment by simoncozens** [comment]
Hah. I don't see squares, but instead the justification is broken. I think we need to change the string patterns in the typesetter. Try this:

**Comment by mnjames** [comment]
Worked great. Thanks!
