### ISSUE TITLE
Any chance of a release?

### ISSUE THREAD

**Issue by DomT4** [simoncozens/sile#482]
Hey folks,

Been doing a little work to tidy up Homebrew's `lua` handling in formulae. If the person who first asked me about this years ago is still around, yup, it's still me handling `lua` despite having stepped down as a maintainer 😸.

The current release, when built from source, seems to have a bunch of old linkage to `icu4c` and I can't really work out where that's coming from, but it is fixed in the master branch _somewhere_. I'll keep looking at it but given it has been nearly a year since the last release of `sile` I thought I'd at least run the question up the flagpole as to whether a release is imminent.

Ref: https://github.com/Homebrew/homebrew-core/pull/12326

**Comment by alerque** [comment]
Hey @DomT4 — that would be me. Yes I'm still around.

Yes there are some subtle but important changes that affect dependencies in the master branch. We can probably cut a release in the not too distant future. I'll look into what else we should cleanup for that. If nothing else I think some of the changes since the last release need documenting.

**Comment by DomT4** [comment]
Thanks for the update, and for the post over in the Homebrew PR. I'll keep an eye on progress here & also try to chase up with `lua-zlib` as to their slightly unusual rockspec.

**Comment by ilovezfs** [comment]
@alerque gentle ping on this.

**Comment by alerque** [comment]
@DomT4 0.9.5 is out. Note there are a couple new lua dependencies @simoncozens added at the last minute. He also asked me about homebrew packaging. I don't have access to a working Mac at all right now so my contribution is limited to packaging for Arch Linux.

**Comment by alerque** [comment]
See also #143.

**Comment by vbgl** [comment]
Thanks for the release! The package description in `nixpkgs` has just been updated (https://github.com/NixOS/nixpkgs/pull/53829): it can be used for installing `sile` on linux, osx, etc.

**Comment by DomT4** [comment]
@alerque Just FYI I'm no longer involved with or contributing to Homebrew. I see someone grabbed the update in https://github.com/Homebrew/homebrew-core/pull/35960; probably didn't need the `expat` or `zlib` changes but that's Homebrew's problem to deal with these days, unless y'all get complaints about it and want to submit the change.
