### ISSUE TITLE
show-off file: 404 not found

### ISSUE THREAD

**Issue by jake-low** [simoncozens/sile#483]
The "show-off file" referenced in README.md doesn't exist. My browser (safari) downloads it anyway for some reason, creating a plain text file with the words "404 not found" in it, which then fails to open in preview with a warning about the PDF being broken.

P.S. looks like a cool project though! I had a look at the `showoff.sil` file. 👍

**Comment by simonsarris** [comment]
It was deleted, for now you can view:

https://github.com/simoncozens/sile/blob/558d35d45e1fee89860d51680563735e076a78e5/examples/showoff.pdf
