### ISSUE TITLE
Linespacing fit-font mode calculates based on wrong line

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#490]
Setting the `linespacing.method` to `fit-font` seems works pretty well at first blush, but has an unintended consequence of calculating the height of the current line and using as the height of the _next_ line. Here is an MWE:

``` TeX
\begin[papersize=a6]{document}
\nofolios
\script[src=packages/linespacing]
\set[parameter=linespacing.method,value=fit-font]
\noindent
\font[size=3em]{T}his is a test that shows the linespacing for the first line will be applied to the second line of text. On the other hand the third line of text will be spaced based on the height of the second line.
\end{document}
```

The output is something like this:

![selection_417](https://user-images.githubusercontent.com/173595/31427089-b48b4cfe-ae6e-11e7-9e17-bf52cdea8d23.png)

**Comment by alerque** [comment]
Never fine bug reports before coffee in the morning.

Duh. That space is because it was looking at _potential_ descenders in the font. Of course my real world case and then this MWE didn't have descenders, but this is working as documented.

**Comment by simoncozens** [comment]
That's the difference between fit-font and fit-glyph.
