### ISSUE TITLE
Question: how can I draw a bounding box around pushHbox?

### ISSUE THREAD

**Issue by akavel** [simoncozens/sile#515]
To improve the prototype implementation of math support (#220), I need to do various tweaks and fixes to layout and rendering of the generated hbox. But I'm now having trouble observing/pinpointing what exactly is wrong. Ability to force SILE to draw a "debugging" bounding box around the hbox (generated with `SILE.typesetter:pushHbox(...)`) would be very useful. Does SILE provide some feature which could let me do something like that?

**Comment by simoncozens** [comment]
Good news! There is a `debugHbox` call in the outputter.

Bad news! I never actually implemented it for libtexpdf.

Good news! I'll go and do that now.

**Comment by simoncozens** [comment]
See a4c4c5f in the devel branch.

**Comment by alerque** [comment]
Besides splitting this commit to a feature branch I added debug output to the main registered hbox command so that `sile -d hboxes file.sil` can be used to debug hboxes created using the SILE `hbox()` command. Of coures any hbox nodes of your own creation will need their own treatment, but this makes it easy to see some stuff by default.

**Comment by akavel** [comment]
Umm; the commit message mentions to use it like:

    SILE.outputter.debugHbox(self, self:scaledWidth(line))

but what is the `line` there? I don't see such parameter in params to `outputYourself` in `SILE.typesetter:pushHbox` ?

**Comment by alerque** [comment]
@akavel If you look at the branch I made for this feature addition I _used_ the new function in the plain class so any calls to `SILE.call("hbox", ...)` can use this debugging out of the box by setting the debug flag at run time using `sile -d hboxes ...`. You can see from my commit maybe how the usage works.

**Comment by akavel** [comment]
Ummmm; do I understand correctly that the `debugHbox` call should be made at the *end* of the `outputYourself` function? That totally surprised me, I thought it should be called at the beginning (especially because "before I potentially broken anything in my outputYourself code"); only from its weird placement and samples by @alerque I started to see that apparently it has to be done at the end.

After some thinking I realize that's probably to make sure that the debugHbox overdraws whatever was drawn by the outputYourself; but I didn't expect this. And still I have doubts regarding my breaking some stuff. Now I see pros & cons of both versions. Wish it was possible to unify them somehow.
