### ISSUE TITLE
Bug: packages/ruby.lua may make a paragraph unintended unexpectedly

### ISSUE THREAD

**Issue by Yoxem** [simoncozens/sile#524]
I've found that packages/ruby.lua will set the "parindent" to be 0pt unexpectedly when use \ruby on the 1st word of a paragraph.

example of a indented paragraph:

> \begin[class=jplain]{document}
> \script[src=packages/font-fallback]
> \script[src=packages/ruby]
> \font[family=Noto Serif CJK JP,language=ja]
> 
> \font[size=24pt,weight=600]{はしがき}\par
> 私は、その男の写真を三葉、見たことがある。
> 
> 一葉は、その男の、幼年時代、とでも言うべきであろうか、十歳前後かと推定される頃の写真であって、その子供が大勢の女のひとに取りかこまれ、（それは、その子供の姉たち、妹たち、それから、従姉妹たちかと想像される）庭園の池のほとりに、荒い縞の袴をはいて立ち、首を三十度ほど左に傾け、醜く笑っている写真である。醜く？　けれども、鈍い人たち（つまり、美醜などに関心を持たぬ人たち）は、面白くも何とも無いような顔をして、
> \end{document}
> 

![default](https://user-images.githubusercontent.com/184107/37359340-4b7d9d56-2728-11e8-8791-50bedf387aad.png)

example wile ruby is added to the beginning of a paragraph:

> \begin[class=jplain]{document}
> \script[src=packages/font-fallback]
> \script[src=packages/ruby]
> \font[family=Noto Serif CJK JP,language=ja]
> 
> \font[size=24pt,weight=600]{はしがき}\par
> 
> % add ruby to the 1st word of a paragraph
> \ruby[reading=わたし]{私}は、その男の写真を三葉、見たことがある。
> 
> 一葉は、その男の、幼年時代、とでも言うべきであろうか、十歳前後かと推定される頃の写真であって、その子供が大勢の女のひとに取りかこまれ、（それは、その子供の姉たち、妹たち、それから、従姉妹たちかと想像される）庭園の池のほとりに、荒い縞の袴をはいて立ち、首を三十度ほど左に傾け、醜く笑っている写真である。醜く？　けれども、鈍い人たち（つまり、美醜などに関心を持たぬ人たち）は、面白くも何とも無いような顔をして、
> \end{document}

![default](https://user-images.githubusercontent.com/184107/37360039-188e6284-272a-11e8-9126-9b14373b332b.png)

I hope the bug can be fixed.

**Comment by simoncozens** [comment]
Confirmed. I'll take a look at this.

**Comment by mnjames** [comment]
This reminds me of an issue I wrote Simon an email about yesterday off-list, about a place where using a user defined command (\v in this case) caused indenting to stop working.

Meaning I'm wondering if the issue here isn't a ruby.lua issue, but a beginning a paragraph with ANY command issue.

**Comment by simoncozens** [comment]
No, this is a separate issue. The `ruby` package sets the ruby text in a hbox with no indent:

```lua
  SILE.call("hbox", {}, function ()
    SILE.settings.temporarily(function ()
      SILE.call("noindent")
      SILE.call("ruby:font")
      SILE.typesetter:typeset(reading)
    end)
  end)
```

But it looks like the `noindent` call might be "leaking".
