### ISSUE TITLE
pcf fonts not supported?

### ISSUE THREAD

**Issue by oimaasi** [simoncozens/sile#534]
Running Arch Linux with the latest non-git version from AUR installed.
I want to type some unichar icons with Siji font. But the font is not loading

```
! Font loading error for {bidilevel=0,direction=LTR,family=Wuncon Siji,features=,hyphenchar=-,language=en,script=,size=10,style=,variant=normal,weight=400}
```

I got a similar error message when trying to use the Terminus font. Both are pcf fonts, so I am wondering if bitmap fonts are generally not supported or am I missing something here?

BTW, what font did you use to produce the unichar example on page 26 of the manual?

```
'\unichar{U+263A}
```

**Comment by simoncozens** [comment]
Yes, you're right, there's no support for bitmap fonts - SILE is OpenType only. To be honest, because of the way that SILE is heavily dependent on Harfbuzz for its shaping, I don't see that changing any time soon; sorry.

The Unichar example uses the [Symbola font](http://users.teilar.gr/~g1951d/).
