### ISSUE TITLE
Brew emits error upgrading sile

### ISSUE THREAD

**Issue by clintolsen** [simoncozens/sile#559]
Apologies as I'm not a brew expert. If I should go bug them, let me know. My previous `reinstall` command no longer works.

So, instead I ran (totally a guess):

```
$ brew upgrade sile
[lots of output]
Error: Permission denied @ unlink_internal - /usr/local/share/ghostscript/9.05/Resource/Font/logo10.pfb
```

I'm not sure if this constitutes a real install problem. Sile appears to be there shows version 0.9.5.1.

**Comment by simoncozens** [comment]
I don't think this is a SILE problem at all, as SILE does not depend (directly or indirectly) on ghostscript - see `brew deps sile`.

What is happening is that after you do a `brew upgrade`, Homebrew performs a `brew cleanup` to tidy up all your installed packages, and this is where it's finding an error - so after the SILE part has already happened.
