### ISSUE TITLE
Long words are rendered over the right margin in justified paragraph(s)

### ISSUE THREAD

**Issue by neofob** [simoncozens/sile#56]
Sometimes, a long word is rendered over the right margin. 

The word "insignificant" is rendered over the right margin in the below paragraph.

The macros \ldquo{} and \rdquo{} are for unicode U+201C and U+201D.

Example of paragraph that can cause this issue (excerpt from "A Vindication of the Rights of Woman" by Mary Wollstonecraft).

\begin[class=book, papersize=129mm x 198mm]{document}
\define[command=em]{\font[family="Garamond Premier Pro",style=italic,
features=+swsh:+dlig:+hlig]{\process}}
% requirement packages
\define[command=smcp]{\font[family="Garamond Premier Pro",features=+smcp]{\process}}

How grossly do they insult us, who thus advise us only to render
ourselves gentle, domestic brutes!  For instance, the winning
softness, so warmly, and frequently recommended, that governs by
obeying.  What childish expressions, and how insignificant is the
being\mdash{}can it be an immortal one?  who will condescend to govern by
such sinister methods! \em{\ldquo{}Certainly,\rdquo{}} says Lord Bacon, \em{\ldquo{}man is of
kin to the beasts by his body: and if he be not of kin to God by
his spirit, he is a base and ignoble creature!\rdquo{}}  Men, indeed,
appear to me to act in a very unphilosophical manner, when they try
to secure the good conduct of women by attempting to keep them
always in a state of childhood.  Rousseau was more consistent when
he wished to stop the progress of reason in both sexes; for if men
eat of the tree of knowledge, women will come in for a taste:  but,
from the imperfect cultivation which their understandings now
receive, they only attain a knowledge of evil.

\end{document}

**Comment by strepon** [comment]
I'd say this is matter of settings. By changing ```linebreak.emergencyStretch``` I got rid of all such overflowing words.

**Comment by simoncozens** [comment]
Yep. The documentation should probably mention overfull hboxes.

**Comment by neofob** [comment]
How do I *change*  `linebreak.emergencyStretch`?
The document `sile.{sile,pdf}` only lists a series of `linebreak.*` settings without examples.

**Comment by simoncozens** [comment]
At the top of chapter 7:

The interface to changing settings from within a SILE document is the `\set` commmand. It take two options: a *parameter* option which expresses which setting is being changed, and a *value* option which expresses the value to which the setting is being changed. As an example:

```
\set[parameter=typesetter.orphanpenalty, value=250]
```

**Comment by neofob** [comment]
I try but it doesn't work. What is the valid value range for `linebreak.emergencyStretch`?
`\set[parameter=linebreak.emergencyStretch, value=5]`

**Comment by strepon** [comment]
You need to set also units: ```\set[parameter=linebreak.emergencyStretch, value=0.5cm]```

**Comment by PanderMusubi** [comment]
Once I made a script for LaTeX to semi-automatically tune these values for difficult paragraphs or whole documents. I can try to port that to SILE. What are all the variables concerning this problem and hyphenation?

**Comment by simoncozens** [comment]
I've added this to the documentation:

> This does not mean that text will always exactly fill the width of the column. SILE will choose line breaks and alter the spacing between words up to a certain extent, but when it has done its best, it will typeset the least bad solution; this may involve some of the words jutting slightly out into the margin.
