### ISSUE TITLE
Manual §2.2.2 code fragment displays undef box

### ISSUE THREAD

**Issue by jamadagni** [simoncozens/sile#561]
The manual [§2.2.2](https://github.com/simoncozens/sile/blob/v0.9.4/documentation/sile.sil#L274) has the following simple code:

    \listitem{\code{apt-get install liblua5.2-dev lua-expat lua-lpeg
            libharfbuzz-dev libfreetype6-dev libfontconfig1-dev libpng-dev}}

but where an unsightly undef box is displayed at the linebreak:

![code-undef-box](https://user-images.githubusercontent.com/948170/54875406-8e051e00-4e24-11e9-90e4-12e7fcb3e81e.png)

Further, the text gets copied to the clipboard as:

`• apt-get install liblua5.2-dev lua-expat lua-lpeglibfontconfig1-dev libpng-dev
libharfbuzz-dev libfreetype6-dev`

Note the absence of space after `lua-lpeg`, and reordering of the `libharfbuzz-dev libfreetype6-dev` to the end. Apart from the loss of space which would cause "package not found" error, the order may not be significant here but it may be significant elsewhere such as in order of libraries in compiler commands, input vs output options etc.

**Comment by jamadagni** [comment]
Hello. You have added the documentation label but this isn't just a documentation error. The .sil file seems fine. It's the output that has problems.

**Comment by alerque** [comment]
This is a result of tabs not being replaced with spaces inside paragraphs. My variant on #492 would fix this.
