### ISSUE TITLE
`roman` counter mode outputs upper case numbers through ICU

### ISSUE THREAD

**Issue by Darkyenus** [simoncozens/sile#571]
[`SILE.formatCounter`](https://github.com/simoncozens/sile/blob/master/packages/counters.lua#L40) attempts to format counter value through ICU, if available. SILE specifies, that `roman` displays lower case roman numerals, while `Roman` displays upper case roman numerals. However, ICU has [different definition](https://www.unicode.org/repos/cldr/tags/latest/common/bcp47/number.xml) with `roman` being upper case and `romanlow` being lowercase. This leads to a bug and inconsistency.

A temporary workaround is to specify `romanlow` explicitly, but this, of course, creates an unneeded dependency on ICU (though I am not sure if it can be missing, but it seems like it).

**Comment by alerque** [comment]
My gut level reaction is to fix this by normalizing on the already documented `roman` and `Roman`, and fixing this by passing the expected equivalent value to ICU. I can fix that if this sounds acceptable.

I recently ran into a bug in an editor plugin (https://github.com/vim-pandoc/vim-markdownfootnotes/issues/11) that is documented to use that notation as well. It's problem is different and doesn't involve ICU, but it does seem to be `romanlow` is kind of a strange nomenclature and I'd be happy to not inflict it on SILE users.
