### ISSUE TITLE
inputs-common seems to be polluting global namespace

### ISSUE THREAD

**Issue by Darkyenus** [simoncozens/sile#602]
I am not sure if this is or isn't intentional, and I might be completely wrong as I am not a good lua programmer, but some code in `inputs-common.lua` seems to mistakenly using [global `content`](https://github.com/simoncozens/sile/blob/master/core/inputs-common.lua#L60). ([Two places](https://github.com/simoncozens/sile/blob/master/core/inputs-common.lua#L36) actually.)

I am writing a PR in which I can fix it, but I am not sure if it isn't intentional. I haven't find anything indicating that it is though.

**Comment by simoncozens** [comment]
Yeah, that’s a bug. Oops.
