### ISSUE TITLE
French conventions with punctuation not respected

### ISSUE THREAD

**Issue by OlivierNicole** [simoncozens/sile#621]
I don't know whether this is implemented yet, but I realized that SILE doesn't get the right space before double punctuation signs in French language settings:
```
\begin{document}
\font[family=Linux Libertine, language=fr, size=15pt]
\glue[width=1.1cm]La peine de mort est nécessaire, disent les partisans de l’antique et barbare routine ; sans elle il n’est point de frein assez puissant pour le crime. Qui vous l’a dit ? Avez-vous calculé tous les ressorts par lesquels les lois pénales peuvent agir sur la sensibilité humaine ? Hélas ! avant la mort, combien de douleurs physiques et morales l’homme ne peut-il pas endurer !
\end{document}
```
This code creates an orphan interrogation mark at the beginning of a line:
![Capture d’écran_2019-05-25_23-38-33](https://user-images.githubusercontent.com/14031333/58374861-42671180-7f46-11e9-8dca-be8223c49d78.png)

If you remove the spaces before punctuation in the source, there is no more orphans, but the space before double punctuation signs is too small (there is supposed to be a space before them, more or less thin depending on the typesetting school, but definitely larger than in English).

**Comment by simoncozens** [comment]
Thanks for this report - a really good one to look at, and it is giving me the impetus to clean up and document language-specific tokenization. To get French working optimally, I will need to

- [*] Clean up the Unicode node maker.
- [ ] Test and refactor other languages which have their own node makers.
- [ ] Document how the node maker workers and how it can be extended on a language-specific basis.
- [ ] Write a French node maker.

**Comment by OlivierNicole** [comment]
I'll be happy to help with French-specific advice if needed. I would also help with the code, but I probably need to get a bit more acquainted with it first.

**Comment by simoncozens** [comment]
How does this look?

![Screenshot 2019-05-26 at 14 24 42](https://user-images.githubusercontent.com/106728/58382435-05406500-7fc2-11e9-91af-e8f277c84eb2.png)

See bug-621 branch if you want to play with it.

**Comment by OlivierNicole** [comment]
It seems indeed than I no longer have the orphan interrogation mark. Great!

With this font, I find myself a bit happier with the setting `punctuationsspace` at `0.3en`, since with `0.5en` some of the spaces look larger before the punctuation mark than after, which definitely looks awkward. I don't know if that setting will be very portable across other font sizes and families, however.

I also have a question: would it be possible to insert the space in front of double punctuation marks (“?!:;”) even when there is no space in the source? I believe LaTeX French settings do that. Ideally, the behaviour would be the same regardless of the presence of space, even if it is a non-breakable or a thin non-breakable space, to accomodate various typing methods (aficionados of the BÉPO keyboard layout like myself are used to put non-breakable space before their double punctuations). But I understand if this is a bit far-fetched.

**Comment by simoncozens** [comment]
Well, since it's a setting, people can set it to whatever they like.

I'm not sure what you mean about spacing double punctuation marks. Before I ask that, a related question: if the document input has `hélas!` (with no space) and the language is set to French, should we artificially insert a space so that the output is `hélas !`? (Or could/should that be an option?)

When it comes to inserting spaces before double punctuation marks, do you mean `hélas!!` should become `hélas ! !` - or something else?

**Comment by OlivierNicole** [comment]
> if the document input has `hélas!` (with no space) and the language is set to French, should we artificially insert a space so that the output is `hélas !`? (Or could/should that be an option?)

That would possibly be desirable, as it has been the behaviour of LaTeX for a long time (with a localization such as Babel or Polyglossia set to French). But since many French people are used to type spaces before punctuation, it could also be desirable that there be no difference between `Hélas !` and `Hélas!`.


> When it comes to inserting spaces before double punctuation marks, do you mean `hélas!!` should become `hélas ! !` - or something else?

Oh sorry, by “double punctuation mark” I meant a punctuation mark whose glyph is in two parts, so one of `? ! : ;`. But no, `hélas!!` should rather become `hélas !!`.

**Comment by OlivierNicole** [comment]
By the way, I've been wondering: what does ICU mean, in the context of SILE?

**Comment by simoncozens** [comment]
> That would possibly be desirable, as it has been the behaviour of LaTeX for a long time (with a localization such as Babel or Polyglossia set to French). But since many French people are used to type spaces before punctuation, it could also be desirable that there be no difference between `Hélas !` and `Hélas!`.

OK, will work on that.

> By the way, I've been wondering: what does ICU mean, in the context of SILE?

It's a library for handling Unicode - http://site.icu-project.org

**Comment by simoncozens** [comment]
I think I understand the problem now. The behavior should be:

* only applied to "high" punctuation. Low punctuation e.g. `commas, points.` should be left alone.
* also apply to guillemets.
* A thin, non-breakable space inserted between the first non-punctuation character and the first punctuation character.
* If there is a sequence `<nonspace> <space> <high punctuation>` then the space should be replaced by a non-breakable thin space.

Is that correct?

**Comment by OlivierNicole** [comment]
Yes, it seems correct to me!

Le 26 mai 2019 19:59:46 GMT+02:00, Simon Cozens <notifications@github.com> a écrit :
>I think I understand the problem now. The behavior should be:
>
>* only applied to "high" punctuation. Low punctuation e.g. `commas,
>points.` should be left alone.
>* also apply to guillemets.
>* A thin, non-breakable space inserted between the first
>non-punctuation character and the first punctuation character.
>* If there is a sequence `<nonspace> <space> <high punctuation>` then
>the space should be replaced by a non-breakable thin space.
>
>Is that correct?
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/simoncozens/sile/issues/621#issuecomment-496019409

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.
