### ISSUE TITLE
Some language files need regenerating at build time

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#633]
I just tried to add some English language features and hit a wall ... Turkish counterparts worked fine but English refused to be extended.

It turns out some languages (looking at you English) get their hyphenation patterns "compiled" (actually serialized?) using `serpent`. The result is currently hard coded into the git repository.

Any compiled or serialized resources need to be removed from the repository and proper rules for regenerating them added to the makefile.

Additionally it looks like maybe the bits that can be optimized that way need to be separated from other code because even using the built in language compile function doesn't seem to handle anything from the language file except the hyphenation patterns, discarding other language specific stuff that might be added there.

**Comment by alerque** [comment]
@simoncozens Is serializing the hyphenation data really gaining us anything? Load time? Was this an experiment or is there really a measurable difference? A few quick tests of my own show no discernible benchmark difference, but I'm not sure I know what I'm actually testing because I'm not sure what situation it was supposed to help.

**Comment by simoncozens** [comment]
At one point it sped up load time. But subsequent work on the hyphenation pattern loader may have made it redundant. If your benchmarks show little difference, let's KISS and get rid of it.

**Comment by alerque** [comment]
I had to iterate `/sile -e 'SILE.languageSupport.loadLanguage("en")' <<< nil` 1000 times before I started coming up with any measurable difference, and even then it sometimes disappeared in the system noise. It wouldn't be hard to setup building things like this at build time but it would mean strict separation of things that could and couldn't be serialized this way — which we don't have in the current language file usage.
