### ISSUE TITLE
Line height metrics differ between local & Travis

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#639]
While working on #592 I've run into a baffling difference in font metric calculations between systems. Perhaps @simoncozens (or @khaledhosny or @behdad) you have ideas?

I've gotten everything coming out the same across platforms and most library versions, but for some reason when we compute line height metrics for *Libertinus Serif* or *Noto Sans CJK* we are coming up with different answers on some systems (Arch Linux and OSX give the same answer) vs. others (Travis running Ubuntu Xenial gives a different answer). I've tried with multiple versions of Harfbuzz on Travis (and currently using the latest 2.5.1 matching my Arch Linux) and the line height metrics are still different. 

* Same font files (Libertinus 6.9, etc.)
* Same Harfbuzz version (and the Harfbuzz's metrics are used, not Freetype's)
* Both local and Travis using fontconfig to find fonts (not the same version, but all this does is pass the font file off to Harfbuzz right?)
* Of course the same SILE code & shaper

What else is there that could affect our line height calculations only for these fonts and not for all others? 

Note only lines in which the _tallest_ thing in the line is these fonts matter. The fonts can be included in the document and text rendered, as long as _something_ on the line is larger than these fonts.

By example this works:

```tex
\font[family=Gentium Plus,size=15pt]{Gentium \font[family=Libertinus Serif,size=12pt]{Libertinus}!}
```

But this fails:
```tex
\font[family=Gentium Plus,size=12pt]{Gentium \font[family=Libertinus Serif,size=15pt]{Libertinus}!}
```

...And by fails I man the line metrics are ~0.2pt different in the version where Libertinus sets the pace.

**Comment by simoncozens** [comment]
OK, so one commonality is that Libertinus Serif and Noto Sans CJK are CFF fonts.

I'm trying to replicate a Travis environment locally with docker. Meanwhile, let's think how to reduce this to its simplest form:

* The problem is differing leading calculations
* Leading is calculated on baselineskip (which is constant) and the *depth* of the previous line.
* 0.2pt is about the right order of magnitude for a change in depth.
* How do we compute the depth of a glyph?

```
      double height = extents.y_bearing * point_size / upem;
      double tHeight = extents.height * point_size / upem;
      lua_pushnumber(L, -tHeight - height);
```

Here's something run from the SILE repl which may help diagnose:

```
SILE.shapers.harfbuzz:shapeToken("a",SILE.font.loadDefaults({filename=".fonts/LibertinusSerif-Regular.otf"}))
```

**Comment by alerque** [comment]
Running `./sile <<< 'SILE.shapers.harfbuzz:shapeToken("a",SILE.font.loadDefaults({filename=".fonts/LibertinusSerif-Regular.otf"}))'` locally I get:
```lua
{1={depth=0.1,gid=66,glyphAdvance=4.57,height=4.39,index=0,name=a,text=a,width=4.57}}
```
Travis is producing:
```lua
{1={depth=0.1,gid=66,glyphAdvance=4.57,height=4.56,index=0,name=a,text=a,width=4.57}}
```

**Comment by simoncozens** [comment]
Looking very harfbuzzy, then. Here's the MWE as a C file:

```C
/* gcc -o test-hb test-hb.c `pkg-config --libs --cflags harfbuzz` */
#include <stdio.h>
#include <assert.h>
#define MAXBUFLEN 1000000
#include <hb.h>
#include <hb-ot.h>

int main() {
  char font_s[MAXBUFLEN + 1];
  FILE *fp = fopen(".fonts/LibertinusSerif-Regular.otf", "r");
  assert(fp);
  size_t font_l = fread(font_s, sizeof(char), MAXBUFLEN, fp);
  assert(!ferror(fp));
  font_s[font_l++] = '\0';
  hb_blob_t* blob = hb_blob_create(font_s, font_l, HB_MEMORY_MODE_WRITABLE, (void*)font_s, NULL);
  hb_face_t* hbFace = hb_face_create(blob, 0);
  hb_font_t* hbFont = hb_font_create (hbFace);
  unsigned int upem = hb_face_get_upem(hbFace);
  hb_font_set_scale(hbFont, upem, upem);
  hb_glyph_extents_t extents = {0,0,0,0};
  hb_font_get_glyph_extents(hbFont, 0x61, &extents);
  printf("Height = %i\n", extents.y_bearing);
  return 0;
}
```

I get `Height = 439` on this Mac.

**Comment by alerque** [comment]
Running this [across different HB versions compiled on Travis](https://travis-ci.com/alerque/sile/builds/115551390) I get the following:

* [Harfbuzz 2.5.1](https://travis-ci.com/alerque/sile/jobs/208051471#L1827)
    ```lua
    {1={depth=0.1,gid=66,glyphAdvance=4.57,height=4.56,index=0,name=a,text=a,width=4.57}}
     ```

* [Harfbuzz 1.4.2](https://travis-ci.com/alerque/sile/jobs/208051472#L1747)
    ```lua
    {1={depth=0.1,gid=66,glyphAdvance=4.57,height=4.56,index=0,name=a,text=a,width=4.57}}
    ```

* [Harfbuzz 1.1.3](https://travis-ci.com/alerque/sile/jobs/208051473#L1622)
    ```lua
    {1={depth=0.1,gid=66,glyphAdvance=4.57,height=4.56,index=0,name=a,text=a,width=4.57}}
    ```

Hey at least it's consistent.

**Comment by alerque** [comment]
I get `Height = 439` on my Arch Linux too.

**Comment by simoncozens** [comment]
@ebraminio? Something funky going on with CFF get_extents.

**Comment by alerque** [comment]
Just for grins, I'll throw our old mystery issue with Graphite enabled metrics in here too in the off chance it might actually be related, see #386.

**Comment by simoncozens** [comment]
I was just thinking about Graphite...

**Comment by simoncozens** [comment]
I now have a running Travis image as a docker container.  OK, here we go:

Travis:
```
# /usr/local/bin/hb-shape  --version
hb-shape (HarfBuzz) 2.5.1
Available shapers: ot,fallback
# md5sum .fonts/LibertinusSerif-Regular.otf
3409bacd6d3a6a75087494c4b8e26b6d  .fonts/LibertinusSerif-Regular.otf

#  hb-shape --shapers=ot --show-extents .fonts/LibertinusSerif-Regular.otf 'a'
[a=0+457<27,456,437,-466>]
```

Mac:
```
$ hb-shape --version
hb-shape (HarfBuzz) 2.5.1
Available shapers: graphite2,ot,coretext,fallback
$ md5sum .fonts/LibertinusSerif-Regular.otf
3409bacd6d3a6a75087494c4b8e26b6d  .fonts/LibertinusSerif-Regular.otf

$ hb-shape --shapers=ot --show-extents .fonts/LibertinusSerif-Regular.otf 'a'
[a=0+457<36,439,419,-449>]
```

After rebuilding on the Mac without graphite:

```
$ hb-shape --version
hb-shape (HarfBuzz) 1.9.0
Available shapers: ot,fallback
$ hb-shape --shapers=ot --show-extents .fonts/LibertinusSerif-Regular.otf 'a'
[a=0+457<36,439,419,-449>]
```

What the ...?

**Comment by simoncozens** [comment]
I'll post in Harfbuzz repo.

**Comment by ebraminio** [comment]
> @ebraminio? Something funky going on with CFF get_extents.

get_extents can use freetype callbacks, Travis CI is known to have old versions of freetype and they versions can be different so test with `--font-funcs ot` and see what happens.

**Comment by simoncozens** [comment]
```

    /* Harfbuzz's support for OT fonts is great, but
       there's currently no support for CFF fonts, so
       downgrade to Freetype for those. */
    if (strncmp(font_s, "OTTO", 4) == 0 || strncmp(font_s, "ttcf", 4) == 0) {
      hb_ft_font_set_funcs(hbFont);
    } else {
      hb_ot_font_set_funcs(hbFont);
    }
```

This comment is no longer true.

**Comment by ebraminio** [comment]
> This comment is no longer true.

Yep

**Comment by ebraminio** [comment]
Just curious to know, is it possible for sile to go without CoreText and Freetype and ship [an embedded version or not] of harfbuzz? Also cool if you can use `hb_blob_create_from_file` for font file reading!
