### ISSUE TITLE
Lua coverage check broken

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#642]
My local test stuff broke the Lua coverage testing. I think I know what to do...

**Comment by alerque** [comment]
Quick question @simoncozens should coverage be done just on the test suite or should I include the docs and examples in that run? (Old behavior was just the tests).

**Comment by alerque** [comment]
I'm not actually sure this is fixed. I got coverage information locally and in Travis logs, but I haven't seen and of the coverage bot messages on PRs yet. Reopening until we confirm we're actually seeing feedback from the process.

**Comment by simoncozens** [comment]
I got one in #641.

**Comment by alerque** [comment]
I guess it needs the latest master to have had coverage before it can start reporting on PRs. :smirk:
