### ISSUE TITLE
Changing footnote font

### ISSUE THREAD

**Issue by san-sang** [simoncozens/sile#655]
I specify the font at the beginning of the document by 
`\font[size=12pt,family=Noto Serif CJK SC,language=zh]
`
However, while normal texts are rendered properly, the footnotes don't seem to be able to use the specified font, so the CJK characters there can't be rendered.  How could I configure the font for footnotes?

What I am doing now is to modify footnotes.lua:
`SILE.Commands["font"]({size = "9pt",family="Noto Sans CJK SC"}, function() `

But I am sure there must be better and more flexible ways.

Also, I noticed that the following change to footnotes.lua doesn't work, but similar things work in mytext.sil. Why?
`SILE.Commands["font"]({size = "9pt",src="/path/to/my.ttf"}, function() `

**Comment by alerque** [comment]
When SILE renders footnotes it calls a command to style them. What you need to do to change the font is redefine that command to apply the styles you want. This could include more than just the font, but that's probably the main usage.

The default command it uses is defined like this:

```lua
SILE.registerCommand("footnote:font", function(options, content)
  SILE.call("font", {size = "9pt"}, function()
    SILE.process(content)
  end)
end)
```

You can define this yourself in your document using Lua by copying that definition into a `\script` tag, or you can do it in the TeX like syntax with something like this:

```tex
\define[command=footnote:font]{\font[size=9pt]{\process}}
```

**Comment by alerque** [comment]
By the way, you should not be using the `SILE.Commands["command"]({}, ...)` syntax any more. Instead use `SILE.call("command", {}, ...)`. This will play a lot nicer with SILE's internals now, including things like giving proper error messages for when things don't work. This syntax allows us to add hooks before and after commands to keep track of what functions are being run where.

**Comment by alerque** [comment]
About your other font issue, if you want to manually specify a font by path and file name I think you need the `filename` argument, not `src`, i.e. in Lua it would look like this:

```lua
SILE.call("font", { size = "9pt", filename = "/path/to/my.ttf" }, ...)
```

Or in TeX-like syntax:

```tex
\font[size=9pt,filename=/path/to/my.ttf]{...}
```

**Comment by san-sang** [comment]
Thank you for the explanation and it helps.
Also, in order to specify the font by file, the key should be "filename" instead of "src", as I wrongly put it above.
