### ISSUE TITLE
Update to docs for building on OS X required

### ISSUE THREAD

**Issue by deepakjois** [simoncozens/sile#74]
I just tried building on OS X, by following the instructions. I was trying to build directly from the repository. I had to do these things in addition:

* It seems that the correct way to refer to lpeg is `LPeg`
* I also had to `brew install automake libtool` 

It would be nice to add this to the docs

**Comment by simoncozens** [comment]
I've added the additional homebrew dependencies, but I'm a bit confused about `lpeg`/`LPeg`. This works for me:

```
$ luarocks install lpeg
Installing https://rocks.moonscript.org/lpeg-0.12.2-1.src.rock...
Using https://rocks.moonscript.org/lpeg-0.12.2-1.src.rock... switching to 'build' mode
...
```

**Comment by deepakjois** [comment]
Strange, now it works for me as well. Yesterday it wasn’t. Closing.
