### ISSUE TITLE
\thisframeRTL from bidi package not working across page boundaries

### ISSUE THREAD

**Issue by deepakjois** [simoncozens/sile#77]
Here is the source for an article in Urdu that spans across multiple pages.

https://gist.github.com/deepakjois/79e89961b60de2e61e44

Note the call to `\eject\par` followed by `\thisframeRTL` in the middle. If I remove that, the next page is typeset LTR.

**Comment by simoncozens** [comment]
That's by design - `\thisframe...` really does mean *this* frame. What we probably need is an option on the document class (perhaps the `plain` class) which declares all its default frames to be RTL. Would you be interested in trying to implement that?

**Comment by deepakjois** [comment]
Yes, sure I could give it a try.

**Comment by simoncozens** [comment]
I've just implemented this in the simplest way possible with 97aedbe
