### ISSUE TITLE
when run sile it failed

### ISSUE THREAD

**Issue by Passw** [simoncozens/sile#84]
```
/usr/local/bin/lua: /usr/local/share/sile/lua-libraries/cassowary.lua:653: attempt to call a nil value (global 'unpack')
stack traceback:
	/usr/local/share/sile/lua-libraries/cassowary.lua:653: in field '_init'
	/usr/local/share/sile/lua-libraries/std/container.lua:172: in field 'SimplexSolver'
	/usr/local/share/sile/core/frame.lua:3: in main chunk
	[C]: in function 'require'
	/usr/local/share/sile/core/sile.lua:33: in main chunk
	[C]: in function 'require'
	/usr/local/bin/sile:5: in main chunk
	[C]: in ?
```

```
 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.04
Release:	15.04
Codename:	vivid
```

```
lua -v
Lua 5.3.0  Copyright (C) 1994-2015 Lua.org, PUC-Rio
```

**Comment by simoncozens** [comment]
Thanks for the bug report. This looks like a problem with the cassowary module. I have not yet tested either SILE or cassowary on Lua 5.3.0 yet, but I wonder if that is the problem. I think Lua's concept of number changed in 5.3, so I would expect some problems. I don't have a 5.3 set up here for testing at the moment, so will do some investigation on this next week.

**Comment by Passw** [comment]
@simoncozens Thanks for your quick response.  I have just re-compiled and installed ```lua``` with https://github.com/lua/lua ```git checkout 5.1.x```. And now, ```sile``` works well :+1:

**Comment by simoncozens** [comment]
I've just added some commits (b1aa7bd, 8dc4b65, 5593b00) for Lua 5.3 support.

**Comment by Passw** [comment]
I have just updated it to Lua5.3 , it works well. Nice ~~
