### ISSUE TITLE
Vertical writing and PDF

### ISSUE THREAD

**Issue by shirat74** [simoncozens/sile#90]
Thank you for your great effort!

I want to comment something on tate support.

In PDF, two writing modes are supported: horizontal and vertical. SILE's tate outputs (e.g., examples/japanese.pdf) look OK at first sight but it seems that they are using horizontal mode even for vertical text. Proper vertical writing support should use Identity-V CMap to enable vertical writing mode.

**Comment by simoncozens** [comment]
Note to self - I think if I arrange for `layout_dir = 1` to be added to the table passed to `loadfont` when loading a vertical font, this should pass the right option to `texpdf_dev_load_native_font`, and everything will work.

**Comment by shirat74** [comment]
I think you need to use texpdf_dev_set_dirmode() too. Dvipdfmx (and libtexpdf) has text writing mode and font writing mode independently.

**Comment by simoncozens** [comment]
Yes, I've done some simple tests and those two functions make it work nicely - until I want to get back into tate mode (e.g. for rotated Latin text). I think to make it work properly, nodes will need to know their writing direction, which is something I wanted to implement anyway to simplify the current madness of `outputYourself`.

Thank you for the pointers - I can work on this now, but I will need to re-structure the way that nodes operate first!

**Comment by simoncozens** [comment]
This is now implemented in 002ca90 and the following commits.
