### ISSUE TITLE
Throw error message on missing fonts

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#95]
At the risk of moving towards the pointless verbosity of LaTeX compilers, I think SILE needs to throw an error to the console when a font specified in a document is not found on the system. Currently the console is silent on the matter and only reviewing the document and knowing what it should look like would tip anybody off to a problem.

Thankfully in some cases this is blanant. For example the `example/test.sil` looks like this when compiled on my system:

![test pdf_014](https://cloud.githubusercontent.com/assets/173595/8225769/30a64096-15a1-11e5-8133-09023bdcf983.png)

I've never heard of it, but something tells me that isn't _Frutiger LT Std_. Just saying.

As a side issue I'm curious how the callback system actually worked. That's the keycaps variant of Linux Biolinum there, but that font isn't in my usual desktop stack for anything. If you ask fontconfig what font to use, it gives a pretty plain fallback:

    # fc-match 'Frutiger LT Std'
    DejaVuSans.ttf: "DejaVu Sans" "Book"

My suggestion would be to throw an error along the lines of 

    # sile examples/test.sil
    This is SILE 0.9.2
    <examples/test.sil><examples/macros.sil>
    Warning: Font 'Frutiger LT Std' not available, falling back to 'Linux Biolinum Keyboard O'
    [1] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14] [15] [16] [17] [18] [19] [20] [21] [22] [23] [24] [25] [26] [27] [28]

**Comment by simoncozens** [comment]
Your wish is my command!

**Comment by alerque** [comment]
Wow, spiffy. I will stop hunting for where that would be done. Eventually my lua will be up to speed to make meaningful contributions.

**Comment by pkulchenko** [comment]
Simon, it turned out that font family is not enough as `Bodoni MT` seems to be substituted for many (absent) fonts on my (Windows) machine and this leads to font overlaps (as the font resolver loads `Bodoni MT Poster Compressed`, but the family is reported as `Bodoni MT`):

```
[fonts] Resolved font family Frutiger FT Std -> C:/Windows/fonts/BOD_PSTC.TTF
[fonts] Resolved font family Inconsolata -> C:/Windows/fonts/BOD_PSTC.TTF
[fonts] Resolved font family Monaco -> C:/Windows/fonts/BOD_PSTC.TTF
[wxlua-output]  Set font        Frutiger FT Std;20;200;normal;normal;    => Bodoni MT
```

Here is the output from `FcNameUnparse` for the substituted font:

```
Bodoni MT,Bodoni MT Poster Compressed-20:familylang=en,en:style=Poster Compressed,Normal,obyÄejnÃ©,Standard,ÎšÎ±Î½Î¿Î½Î¹ÎºÎ¬,Regular,Normaali,NormÃ¡l,Normale,Standaard,Normalny,ÐžÐ±Ñ‹Ñ‡Ð½Ñ‹Ð¹,NormÃ¡lne,Navadno,Arrunta:stylelang=en,ca,cs,de,el,en,fi,hu,it,nl,pl,ru,sk,sl,eu:fullname=Bodoni MT Poster Compressed:fullnamelang=en:slant=0:weight=50:width=63:foundry=monotype:file=C\:/Windows/fonts/BOD\_PSTC.TTF:index=0:outline=True:scalable=True:charset=  |>^1!|>^1!P0oWQ |>^1!|>^1!|>^1!!!!%#gfN8.!!B7%ggR6OF3y?4!!K?&   !!!)$      9;*l$ !!!.%      !!!!# !!#0GM>RAd#y#fx!!!!5  !!!W?  !!#3H !!!!n      !!#6I<UKaX!!!?+!!!%#!!!!X    !!#AL      !!!1& !!+u{!!!!)       :lang=aa|ay|bi|br|ch|co|da|de|en|es|et|eu|fi|fj|fo|fr|fur|fy|gd|gl|gv|ho|ia|id|ie|io|is|it|lb|mg|nb|nds|nl|nn|no|nr|nso|oc|om|pt|rm|sma|smj|so|sq|ss|st|sv|sw|tl|tn|tr|ts|uz|vo|vot|wa|xh|yap|zu|an|crh|fil|ht|jv|kj|ku-tr|kwm|li|ms|ng|pap-an|pap-aw|rn|rw|sc|sg|sn|su|za:fontversion=137626:fontformat=TrueType:decorative=False:hash=sha256\:d0efcbb58042808781f33898dc0fbe5342da22d813415a4dcb394872b1d19afa:postscriptname=BodoniMTPosterCompressed
```

It seems like access to "fullname" would provide the information needed. Also having access to NameUnparse results may be useful as well in case any additional fields may be needed.

```
    fullname       FC_FULLNAME            String  Font face full name where
                                                  different from family and
                                                  family + style
```

I got it all working with the following diff:

```diff
diff --git a/src/justenoughharfbuzz.c b/src/justenoughharfbuzz.c
index 84724c3..0c459b2 100644
--- a/src/justenoughharfbuzz.c
+++ b/src/justenoughharfbuzz.c
@@ -61,7 +61,7 @@ void calculate_extents(box* b, hb_glyph_info_t glyph_info, hb_glyph_position_t g
 
 int face_from_options(lua_State* L) {
   FT_Face face;
-  FcChar8 * font_path;
+  FcChar8 * font_path, * name_unparse, * fullname, * familyname;
   FcPattern* p;
   FcPattern* matched;
   FcResult result;
@@ -145,15 +145,28 @@ int face_from_options(lua_State* L) {
   FcPatternGetInteger(matched, FC_WEIGHT, 0, &weight);
 
   /* Find out which family we did actually pick up */
-  if (FcPatternGetString (matched, FC_FAMILY, 0, &family) != FcResultMatch)
+  if (FcPatternGetString (matched, FC_FAMILY, 0, &familyname) != FcResultMatch)
     return 0;
+  if (FcPatternGetString (matched, FC_FULLNAME, 0, &fullname) != FcResultMatch)
+    return 0;
+
   lua_newtable(L);
   lua_pushstring(L, "filename");
   lua_pushstring(L, (char*)font_path);
   lua_settable(L, -3);
 
   lua_pushstring(L, "family");
-  lua_pushstring(L, (char*)(family));
+  lua_pushstring(L, (char*)(familyname));
+  lua_settable(L, -3);
+
+  lua_pushstring(L, "fullname");
+  lua_pushstring(L, (char*)(fullname));
+  lua_settable(L, -3);
+
+  name_unparse = FcNameUnparse(matched);
+
+  lua_pushstring(L, "unparsed");
+  lua_pushstring(L, (char*)name_unparse);
   lua_settable(L, -3);
 
   FcPatternDestroy (matched);
```

Not sure about the quality as I was just following what you already had. `free(name_unparse)` may need to be added according to the examples I saw.
