### ISSUE TITLE
Has a different suffix been considered to differentiate SILE file formats?

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#98]
Currently as I understand it there are two input formats: one vaguely resembling the LaTeX syntax and the other being strict XML. According to the manual the first character of the file (`c === '<'`) decides how the file should be parsed. I just started a [SILE syntax plugin for vim](https://github.com/alerque/vim-sile) and before I got very far realized that the rules were going to have to operate in dual modes. This is doable in vim but will be an extra hassle. It occurred to me that not all editors will be this forgiving and there might be other situations where another method would be desirable.

Has using different extensions (say `*.silx` or `*.slx`) been considered as an alternate way to identify XML variants of the intput without having to open the file and parse some of the contents?

This is more of a brainstorm that a request as I haven't researched what the options are, but in the long run it seems like this might ease some implementation pain points as many other programs may want to interact with SILE data files.

**Comment by simoncozens** [comment]
I think it's fine to assume that a `.sil` file will be TeX-like. SILE doesn't care about extensions–you can (and probably should) run `sile whatever.xml`, but if appends `.sil` as a default if you don't provide an extension. So in that sense, the extension for XML flavour SILE inputs is `.xml`. Or `.usx` or whatever you like. :-)
