### ISSUE TITLE
Comments should be allowed at beginning of file

### ISSUE THREAD

**Issue by alerque** [simoncozens/sile#99]
Right now the parser dies if `\begin{document}` is not the first line of the file. This should be relaxed to allow comments to be the first line.

On a more tentative note that could be related—I haven't looked at how this is parsed yet but I hope to find that a script can be injected in a document early enough that it can be responsible for setting the initial document class and paper settings without them needing to be set in the document markup.

**Comment by simoncozens** [comment]
You're probably right about comments at the start of the document, but what you want in terms of injecting a script can be done with the `-I` command line flag. That allows you to load up a SILE wrapper around your input file; if the wrapper defines class/paper size/commands then your input can then be plain XML, e.g. `sile -I docbook examples/article-template.xml`
